<div class="line_gray line_page width_common page_anh_video">
    <?php
    $arrData = $this->arrData;
    $data = $this->data;
    $arrDataRV = $this->arrDataRV;
    $notEmptyDataRV = !empty($arrDataRV);
    $thumbNail = '';
    ?>
    <div class="block_top_anh_video width_common">
        <?php
        if (!empty($data))
        {

            if ($arrDataRV['video_id'] > 0)
            {
                //Check show quang cao eclick
                $isShowAds = ($data['privacy'] != 0) ? true : false;
            }
            else
            {
                //Check show quang cao eclick
                $isShowAds = (($data['privacy'] & 32) != 32) ? true : false;
            }
            if ($arrDataRV['have_license'] == 1)// && in_array($data['category_id'], $arrCate))
            {
                $isLicense = true;
            }
            else
            {
                $isLicense = false;
            }
            if ($isShowAds)//Show qc 3D world cup
            {
                $zoneId = $this->configView['eclick']['ads']['zone'];
            }
            else
            {
            $zoneId = "";
            }
            $urlInfo = $this->config['url'] . '/video/vne-info/id/' . $data['article_id'] . '/type/1/gf/1/exclude/' . implode(',', $this->arrEx);
            $data['share_url'] = $this->ShareurlSeagame($data['share_url']);
            ?>
            <div id="col_left" class="col_left_anh_video">
                <div class="block_image_left block_video_left">
                    <div class="block_flash_video" style="position: relative;">
                        <?php
                        if ($notEmptyDataRV)
                        {
                            //Check thumbnail
                            if (!empty($data['thumbnail_url']))
                            {
                                $thumbNail = $this->ImageurlArticle($data, 'size4', -1);
                            }//end if
                            //Suggest video, loai tru video dang xem, video lien quan
                            $moreUrl = $this->configView['url'] . '/video/vne-more/id/' . $data['article_id'] . '/type/1/exclude/' . implode(',', $dataExclude);
                            $flashVars = 'xmlPath=&mAuto=true&autoHide=true&tracktype=video&typeview=1&playerid=videoplayer&trackurl=' . $arrDataRV['url'] . '&objectid=' . $arrDataRV['object_id'] . '&id=' . $data['article_id'] . '&type=201&thumburl=' . $thumbNail . '&tracklink=' . $share_url . '&suggestionurl=' . $moreUrl . '&videoid=' . $arrDataRV['object_id'] . '&videotype=201&adszoneid=' . $zoneId . '&tracktitle=' . $data['title_format'];
                        }
                        else
                        {
                            $urlInfo = $this->configView['url'] . '/video/vne-info/id/' . $data['article_id'] . '/type/1/gf/1/exclude/' . implode(',', $dataExclude);
                            $flashVars = 'asseturl=' . $this->configView['flash'] . '/asset.swf&xmlPath=' . $urlInfo . '&local=embed&mAuto=true&autoHide=true&trackurl=&tracktype=&stream=';
                        }//end if
                        ?>
                        <div class="embed-container">
                            <object width="100%" height="100%" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="videoplayer" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0">
                                <param name="movie" value="<?php echo $this->configView['flash'] ?>/fptplayer.swf">
                                <param name="allowScriptAccess" value="always" />
                                <param name="quality" value="high">
                                <param name="bgcolor" value="#000000">
                                <param name="wmode" value="transparent">
                                <param name="flashvars" value="<?php echo $flashVars; ?>">
                                <param name="allowfullscreen" value="true">
                                <embed bgcolor="#000000" width="100%" height="100%" name="videoplayer" flashvars="<?php echo $flashVars; ?>" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" src="<?php echo $this->configView['flash'] ?>/fptplayer.swf">
                            </object>
                            <div id="block_video_html5" data-html5="1" data-video-zid="<?php echo $zoneId; ?>"  class="block_flash_video" style="display:none;width:100%;"></div>
                        </div>
                    </div>
                    <a class="txt_title" title="<?php echo $data['title']; ?>">
                        <?php echo $data['title']; ?>
                        <span class="no_wrap">
                            <?php echo $this->ArticleComment($data); ?>
                        </span>
                    </a>
                    <div class="txt_lead">
                        <?php echo $data['lead']; ?>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
        <div id="col_right" class="col_right_anh_video">
            <?php
            if (!empty($this->arrVideoRelate))
            {
                ?>
                <div class="list_hot_video_top">
                    <ul class="list_news">
                        <?php
                        foreach ($this->arrVideoRelate as $id)
                        {
                            $article = $this->objArticle->getArticleBasic($id);
                            if (empty($article))
                            {
                                continue;
                            }
                            $article['share_url'] = $this->ShareurlSeagame($article['share_url']);
                            ?>
                            <li>
                                <div class="block_image_news width_common">
                                    <?php
                                    if (!empty($article['thumbnail_url']))
                                    {
                                        ?>
                                        <div class="thumb">
                                            <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" >
                                                <img src="<?php echo $this->ImageurlArticle($article, 'size1', -1); ?>" alt="<?php echo $video['title_format']; ?>" title="<?php echo $video['title_format']; ?>" />
                                                <span class="play_icon"></span>
                                            </a>
                                            <?php echo $this->ArticleTypeIcon($article); ?>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                    <div class="title_news">
                                        <a class="txt_link" href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>">
                                            <?php echo $article['title']; ?>
                                            <span class="no_wrap">
                                                <?php echo $this->ArticleComment($article); ?>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="list_anh_video_inner width_common list_video_inner">
        <?php
        if (!empty($this->arrData))
        {
            ?>
            <ul class="list_anh_video" id="list_anh_video">
                <?php
                foreach ($this->arrData as $id)
                {
                    $article = $this->objArticle->getArticleBasic($id);
                    if (empty($article))
                    {
                        continue;
                    }
                    $article['share_url'] = $this->ShareurlSeagame($article['share_url']);
                    ?>
                    <li>
                        <?php
                        if (!empty($article['thumbnail_url']))
                        {
                            ?>
                            <div class="thumb_anh_video">
                                <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" >
                                    <img src="<?php echo $this->ImageurlArticle($article, 'size6', -1); ?>" alt="<?php echo $video['title_format']; ?>" title="<?php echo $video['title_format']; ?>" />
                                    <span class="play_icon"></span>
                                </a>
                                <?php echo $this->ArticleTypeIcon($article); ?>
                            </div>
                        <?php
                        }
                        ?>
                        <div class="title_news">
                            <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" class="txt_link">
                                <?php echo $article['title']; ?>
                                <span class="no_wrap">
                                    <?php echo $this->ArticleComment($article); ?>
                                </span>
                            </a>
                        </div>
                    </li>
                    <?php
                }
                ?>
            </ul>
            <?php
            if (count($this->arrData) >= LIMIT_LIST_VIDEO)
            {
                ?>
                <div class="more_btn">
                    <a href="<?php echo $this->configView['url'] . '/category/othernews'; ?>" data-container="#list_anh_video" data-params="<?php echo $this->escape(Zend_Json::encode(array('category_id' => CATE_SEA_GAMES_VIDEO,  'limit' => LIMIT_MORE_NEWS + LIMIT_RELATED_VIDEO + 1, 'offset' => LIMIT_LIST_VIDEO + 1, 'exclude' => $this->arrEx))); ?>">Xem tiếp</a>
                </div>
                <?php
            }
        }
        ?>
    </div>
</div>
<script language="javascript" type="text/javascript">
    <?php
    if (!empty($data))
    {
        ?>
    $(document).ready(function() {
        try {
            if (FlashDetect.installed == false) {
                $.getJSON(
                    '<?php echo $this->configView['url']; ?>/video/vne-info/?callback=?',
                    {
                        id:<?php echo $data['article_id']; ?>,
                        typeHTML: 'html5'
                    },
                    function(response) {
                        if (response.error == 0) {
                            $("#videoplayer").hide();
                            var w = $(".embed-container").width();
                            var h = (w * 56.25) / 100;
                            var object = '<video id="video_<?php echo $data['article_id']; ?>" ads="' + encodeURI('{"schedule":[{"tag": "1,3,5","position": "pre-roll"}]}') + '"  poster="'+response.thumbnail_url+'" width="' + w + '" height="' + h + '" controls autoplay preload="none">'
                                + '<source src="' + response.media_url + '" type="video/mp4" />'
                                + '</video>';
                            $("#block_video_html5").html(object).show();
                            $.getScript('<?php echo $this->configView['vnecdn']['js']; ?>/vastvideo.js').done(function(script, textStatus) {
                                console.log("init Ad!");
                                var a = document.getElementById('video_<?php echo $data['article_id']; ?>');
                                console.log(a);
                                if (a) {
                                    initAdsFor('video_<?php echo $data['article_id']; ?>');
                                }
                                else {
                                    console.log("not found video player!");
                                }
                            });
                        }
                    }
                );
            }
        } catch (e) {
        }
    });
    $(window).resize(function() {
        var w = $(".embed-container").width();
        var h = (w * 56.25) / 100;
        $('video').attr('width', w).attr('height', h);
    });
    //tracking video
    var d = new Date();
    var t = d.getTime();
    var h = document.createElement('script');
    h.setAttribute('src', 'http://l.a.eclick.vn/media/video?ac=play&id=<?php echo $data['article_id']; ?>&type=200&siteId=5&player=1&articleId=<?php echo $data['article_id']; ?>&url=<?php echo $data['share_url']; ?>&showads=<?php echo $isShowAds; ?>&t='+t);
    h.setAttribute('type', 'text/javascript');
    h.setAttribute('charset', 'utf-8');
    document.getElementsByTagName('head')[0].appendChild(h);
    <?php } ?>
</script>