<?php header("Content-type: text/xml; charset=utf-8"); ?>
<?php echo '<?xml version = "1.0" encoding = "utf-8" ?>' ?>
<data>
    <items>
        <?php
        $arrData = $this->arrData;
        if(is_array($arrData) && count($arrData)>0)
        {
            foreach($arrData as $id)
            {								
                $data  = $this->objArticle->getArticleBasic($id);
				$share_url = $data['share_url'];
                // Reference article
                $arrDataReference = $this->objArticle->getObjectReferenceByArticleId(array('article_id' => $id,'limit' => 1,'offset' => 0));
                $duration = 0;
                //Valid data
                if (!empty($arrDataReference['data']))
                {
                    $arrDataReference = current($arrDataReference['data']);
                    $arrMetaData = Zend_Json::decode($arrDataReference['meta_data']);
                    if ($arrMetaData)
                    {
                        $duration = (int) $arrMetaData['duration'];
                    }
                }
            ?>
            <item>
                <title><![CDATA[<?php echo html_entity_decode($data['title']);?>]]></title>
                <thumbnail><![CDATA[<?php echo $this->ImageurlArticle($data, 'size2', -1);?>]]></thumbnail>
                <duration><?php echo $duration;?></duration>
                <link><![CDATA[<?php echo $share_url; ?>]]></link>
            </item>
            <?php
            }
        }
        ?>
    </items>
</data><?php die;?>