<!DOCTYPE html>
<html>
    <head>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="Vnexpress.net" />
        <meta name="dc.description" content="Tin nhanh video clip hình ảnh các môn thể thao: bóng đá quyền anh đua xe bóng chuyền cầu lông… đang diễn ra ở VN & thế giới.." />
        <meta name="dc.subject" content="Thể Thao - Vnexpress" />
        <meta name="dc.created" content="2001-02-26" />
        <meta name="dc.publisher" content="VnExpress" />
        <meta name="dc.rights.copyright" content="VnExpress" />
        <meta name="dc.creator.name" content="VnExpress" />
        <meta name="dc.creator.email" content="webmaster@vnexpress.net" />
        <meta name="dc.identifier" content="http://vnexpress.net" />
        <meta name="copyright" content="VnExpress" />
        <meta name="author" content="VnExpress" />
        <meta name="dc.language" content="vi-VN" />
        <meta name="robots" content="index,follow" />
        <meta http-equiv="content-language" content="vi"/>
        <meta name="geo.placename" content="Ha Noi, Viet Nam" />
        <meta name="geo.region" content="VN-HN" />
        <meta name="geo.position" content="21.030624;105.782431" />
        <meta name="ICBM" content="21.030624, 105.782431" />
        <meta name="revisit-after" content="days">
        <!-- iPad icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/72x72.png" sizes="72x72" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="144x144" />
        <!-- iPhone and iPod touch icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" sizes="57x57" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="114x114" />
        <!-- Nokia Symbian -->
        <link rel="nokia-touch-icon" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" />
        <!-- Android icon precomposed so it takes precedence -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="1x1" />
        <!-- InstanceBeginEditable name="doctitle" -->
        <?php
        if (!$this->notRefreshPage)
        {
            ?>
            <meta http-equiv="REFRESH" content="1800" />
            <?php
        }
        ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta content="VnExpress" property="og:site_name" />
        <meta content="<?php echo $this->escape($this->ogType); ?>" property="og:type" />
        <meta content="<?php echo $this->escape($this->ogTitle); ?>" itemprop="headline" property="og:title" />
        <meta content="<?php echo $this->ogUrl; ?>" itemprop="url" property="og:url" />
        <meta content="<?php echo $this->ogImage; ?>" itemprop="thumbnailUrl" property="og:image" />
        <meta content="<?php echo $this->escape($this->ogDescription); ?>" itemprop="description" property="og:description" />
        <link rel="alternate" href="<?php echo $this->configView['url']; ?>" hreflang="vi-vn" />
        <?php
        $isDetailArticle = isset($this->articleTrackingId) && is_numeric($this->articleTrackingId) && $this->articleTrackingId > 0;
        $isCategoryPolyAds = isset($this->intCateIdPolyAds) && is_numeric($this->intCateIdPolyAds) && $this->intCateIdPolyAds > 0;
        //Proccess category id
        $tt_category_id = $isCategoryPolyAds ? $this->intCateIdPolyAds : WORLD_CUP;
        $tt_article_id = $isDetailArticle ? $this->articleTrackingId : $tt_category_id;
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <!-- JS -->
        <script type="text/javascript">
            /*GA - Tracking pageview*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_setDomainName', 'vnexpress.net']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['a._setAccount', 'UA-249346-22']);
            _gaq.push(['a._trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-37']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-29374284-26']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();

            var site_id = <?php echo SITE_ID; ?>;
            var img_url = '<?php echo $this->configView['images']; ?>';
            var css_url = '<?php echo $this->configView['css']; ?>';
            var base_url = '<?php echo $this->configView['url']; ?>';
            var device_env = <?php echo DEVICE_ENV; ?>;
            var article_id = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>;
            var vne_url = '<?php echo $this->configView['url_vne']; ?>';
            var interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = <?php echo ACTIVE_CAPCHA; ?>;
            document.domain = '<?php echo DOMAIN_VNE ?>';
            var application_env = '<?php echo APPLICATION_ENV; ?>';
        </script>
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/general.css" media="all" />
        <?php echo $this->headLink(); ?>
        <!-- JS -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/libs/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutils.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['js']; ?>/owl.carousel.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->configView['polyads']['core']; ?>/MobileShowAds.js"></script>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="box_col_left" class="block_more_info hiddenweb">
            <div class="box_width_common">
                <div class="btn_control_col_left"><img src="<?php echo $this->configView['images']; ?>/graphics/img_left_panel.gif" alt="" /></div>
                <div class="block_scoll_menu">
                    <div class="block_search">
                        <form action="http://timkiem.vnexpress.net/thethao" method="get" target="_blank" id="search">
                            <input type="text" name="q" value="Tìm kiếm" maxlength="80" class="input_search" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''"/>
                            <input type="submit" value="" class="icon_menu_phone btn_search" />
                        </form>
                        <div class="clear">&nbsp;</div>
                    </div>
                    <ul class="list_item_panel">
                        <li><a href="<?php echo $this->configView['url']; ?>" class="bg_666"><span class="icon_menu_phone ico_menu_35">&nbsp;</span>World Cup 2014</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/tin-tuc'; ?>" class=""><span class="icon_menu_phone ico_menu_02">&nbsp;</span>Tin tức</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/binh-luan'; ?>" class=""><span class="icon_menu_phone ico_menu_26">&nbsp;</span>Bình luận</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/ben-le'; ?>" class=""><span class="icon_menu_phone ico_menu_27">&nbsp;</span>Bên lề</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/photo'; ?>" class=""><span class="icon_menu_phone ico_menu_28">&nbsp;</span>Ảnh</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/video'; ?>" class=""><span class="icon_menu_phone ico_menu_29">&nbsp;</span>Video</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/lich-thi-dau'; ?>" class=""><span class="icon_menu_phone ico_menu_30">&nbsp;</span>Lịch thi đấu</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/32-doi'; ?>" class=""><span class="icon_menu_phone ico_menu_31">&nbsp;</span>32 Đội</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/lich-su'; ?>" class=""><span class="icon_menu_phone ico_menu_32">&nbsp;</span>Lịch sử</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/du-doan'; ?>" class=""><span class="icon_menu_phone ico_menu_33">&nbsp;</span>Dự đoán</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/dovui'; ?>" class=""><span class="icon_menu_phone ico_menu_41">&nbsp;</span>Đố vui</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/bang-diem'; ?>" class=""><span class="icon_menu_phone ico_menu_36">&nbsp;</span>Bảng điểm</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/vua-pha-luoi'; ?>" class=""><span class="icon_menu_phone ico_menu_36">&nbsp;</span>Vua phá lưới</a></li>
                        <li><a href="<?php echo $this->configView['url'], '/danh-sach-trung-thuong'; ?>" class=""><span class="icon_menu_phone ico_menu_36">&nbsp;</span>DS trúng thưởng</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/contactus?p=worldcup"  class="bg_666"><span class="icon_menu_phone ico_menu_21">&nbsp;</span>Liên hệ tòa soạn</a></li>
                        <li class="end"><a href="<?php echo $this->configView['url_vne']; ?>/contact.htm"  class="bg_666"><span class="icon_menu_phone ico_menu_22">&nbsp;</span>Thông tin tòa soạn</a></li>
                    </ul>
                    <div class="coppy_right_left width_common">
                        <div class="txt_coppy_right">
                            <p>© Copyright 1997- VnExpress.net, All rights reserved</p>
                            <p>® VnExpress giữ bản quyền nội dung trên website này.</p>
                        </div>
                        <div class="txt_lienhe"> Hotline:<br>
                            <a href="tel:012388801238">0123.888.0123 (Hà Nội)</a> <br>
                            <a href="tel:01292333555">0129.233.3555 (TP HCM) </a></div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div id="page">
            <div  class="banner_mobile_300x50 banner_mobile">
                <script type="text/javascript">try {Poly_Top();} catch (e) {}</script>
            </div>
            <div id="wrapper_page">
                <div id="wraper_header_device" class="hiddenweb">
                    <div class="width_common">
                        <div class="logovne">
                            <a href="<?php echo $this->configView['url_vne']; ?>">
                                <img src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/logo.png" alt="vnexpress logo" class="img_logo" />
                            </a>
                            <div class="right logo_wc"><a href="<?php echo $this->configView['url']; ?>"><img src="<?php echo $this->configView['images']; ?>/icons/logo_WC_mobile.gif" alt="" /></a></div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                </div>
                <div id="wrapper_header" class="hiden_device_all">
                    <div class="header_logo width_common">
                        <a href="<?php echo $this->configView['url_vne']; ?>">
                            <img class="left logo_web" alt="" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/img_logo_vne_web.gif">
                        </a>
                        <div class="banner_728x90 right">
                            <div class="box_category width_common hidden320">
                            </div>
                        </div>
                    </div>
                    <div id="main_menu">
                        <a href="<?php echo $this->configView['url'] ?>" class="<?php echo $this->intCategoryId == WORLD_CUP ? 'active' : ''; ?>">World Cup 2014</a>
                        <?php
                        if (!empty($this->breakCumbSub))
                        {
                            foreach ($this->breakCumbSub as $category)
                            {
                                if ($category['category_id'] == CATE_ID_LICHSU)
                                {
                                    continue;
                                }
                                $classHr = '';
                                if (in_array($category['category_id'], $this->arrActiveMenu))
                                {
                                    $classHr = 'active';
                                }
                                echo '<a class="', $classHr, '" title="', $category['catename'], '" href="', $category['link'], '">', $category['catename'], '</a>';
                            }
                        }
                        ?>
                        <a class="<?php echo ((isset($this->strCateCode)) && ($this->strCateCode == 'lich-thi-dau')) ? 'active' : ''; ?>" href="<?php echo $this->configView['url'], '/lich-thi-dau'; ?>">Lịch thi đấu</a>
                        <a class="<?php echo ((isset($this->strCateCode)) && ($this->strCateCode == 'team')) ? 'active' : ''; ?>" href="<?php echo $this->configView['url'], '/32-doi'; ?>">32 đội</a>
                        <a class="<?php echo ((isset($this->intCategoryId)) && ($this->intCategoryId == CATE_ID_LICHSU)) ? 'active' : ''; ?>" href="<?php echo $this->configView['url'], '/lich-su'; ?>">Lịch sử</a>
                        <a class="<?php echo ((isset($this->strCateCode)) && ($this->strCateCode == 'du-doan')) ? 'active' : ''; ?>" href="<?php echo $this->configView['url'], '/du-doan'; ?>">Dự đoán</a>
                        <a class="<?php echo ((isset($this->strCateCode)) && ($this->strCateCode == 'dovui')) ? 'active' : ''; ?>" href="<?php echo $this->configView['url'], '/du-doan'; ?>">Đố vui</a>
                    </div>
                </div>
                <div id="wrapper_container">
                    <div id="container">
                        <div class="breakumb_timer width_common hiddenweb">
                            <div class="timer_header">
                                <ul>
                                    <?php
                                    $isHome = isset($this->isHome) && ($this->isHome) ? 1 : 0;
                                    $isDetail = isset($this->isDetail) && ($this->isDetail) && $this->menuDetail['category_id'] == WORLD_CUP ? 1 : 0;
                                    if ((!empty($this->arrActiveMenu) && ($this->arrActiveMenu[0] == SITE_ID)) || $isHome || $isDetail)
                                    {
                                        unset($this->arrActiveMenu);
                                    }
                                    ?>
                                    <li class="start<?php //echo !empty($this->arrActiveMenu) ? ' have_cap2' : ''; ?>">
                                        <a href="<?php echo $this->configView['url']; ?>">
                                            <span class="icon_wc_mobile">&nbsp;</span>
                                            World Cup 2014
                                        </a>
                                        <span class="arrow_breakumb">&nbsp;</span>
                                    </li>
                                    <?php
                                    if (!empty($this->menuDetail) && $this->menuDetail['category_id'] != SITE_ID && !$isHome && !$isDetail)
                                    {
                                        switch ($this->strCateCode)
                                        {
                                            case 'lich-thi-dau':
                                                $this->menuDetail['catename'] = 'Lịch thi đấu';
                                                break;
                                            case 'du-doan':
                                                $this->menuDetail['catename'] = 'Dự đoán';
                                                break;
                                            case 'dovui':
                                                $this->menuDetail['catename'] = 'Đố vui';
                                                break;
                                            case 'lich-su':
                                                $this->menuDetail['catename'] = 'Lịch sử';
                                                break;
                                            case 'team':
                                                $this->menuDetail['catename'] = '32 đội';
                                                break;
                                            case 'bang-diem':
                                                $this->menuDetail['catename'] = 'Bảng điểm';
                                                break;
                                            case 'doi-bong':
                                                $this->menuDetail['catename'] = 'Đội bóng';
                                                break;
                                            case 'cau-thu':
                                                $this->menuDetail['catename'] = 'Cầu thủ';
                                                break;
                                            case 'tuong-thuat':
                                                $this->menuDetail['catename'] = 'Tường thuật';
                                                break;
										    case 'thong-ke':
                                                $this->menuDetail['catename'] = 'Thống kê';
                                                break;
                                            default :
                                                break;
                                        }
                                        ?>
                                        <!--<li class="cap2"><a href="<?php echo $this->menuDetail['link']; ?>/"><?php echo $this->menuDetail['catename']; ?></a><span class="arrow_breakumb">&nbsp;</span></li>-->
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                            <div class="block_clear_men"><a target="_blank" onclick="thethao.trackingImpression()" href="http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=20&mc=click&pli=10045207&PluID=0&ord=<?php echo time();?>"><img src="<?php echo $this->configView['images']; ?>/graphics/img_clearmen.png" /></a></div>
                        </div>
                        <?php echo $this->layout()->content; ?>
                        <div  class="banner_mobile_300x50 banner_footer_mobile width_common">
                            <script type="text/javascript">try{Poly_Footer();}catch(e){}</script>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div id="wrapper_footer">
                    <div id="footer">
                        <ul class="list_menu_small">
                            <li><a href="<?php echo $this->configView['url']; ?>">World Cup 2014</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/tin-tuc/'; ?>">Tin tức</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/binh-luan/'; ?>">Bình luận</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/ben-le/' ?>">Bên lề</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/photo/'; ?>">Ảnh</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/video/'; ?>">Video</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/lich-thi-dau/'; ?>">Lịch thi đấu</a></li>
                            <li><a href="<?php echo $this->configView['url'], '/32-doi/'; ?>">32 đội</a></li>
                            <li class="end"><a href="<?php echo $this->configView['url'], '/lich-su/'; ?>">Lịch sử</a></li>
                            <li class="end"><a href="<?php echo $this->configView['url'], '/du-doan/'; ?>">Dự đoán</a></li>
                            <li class="end"><a href="<?php echo $this->configView['url'], '/dovui/'; ?>">Đố vui</a></li>
                        </ul>
                        <div class="ft-bot">
                            <div class="coppy_right_small">
                                <div class="tttoasoan">
                                    <div class="txt_up width_common">
                                        <div class="width_50 "><img src="<?php echo $this->configView['vnecdn']['images']; ?>/icons/hotline.gif" alt="" ><a href="<?php echo $this->configView['url_vne']; ?>/contactus?p=worldcup"> Liên hệ tòa soạn</a></div>
                                        <div class="width_50"><img src="<?php echo $this->configView['vnecdn']['images']; ?>/icons/icon_thongtintoasoan.gif" alt="" ><a href="<?php echo $this->configView['url_vne']; ?>/contact.htm" target="_blank"> Thông tin tòa soạn</a></div>
                                    </div>
                                    <div class="txt_down width_common">
                                        <div class="width_50 "><b>0123.888.0123</b> (HN) </div>
                                        <div class="width_50"><b>0129.233.3555</b> (TP HCM)</div>
                                    </div>
                                </div>
                                <div class="coppy_right">
                                    <p>&copy; <span>Copyright 1997 VnExpress.net,</span> All rights reserved</p>
                                    <p>&reg; VnExpress giữ bản quyền nội dung trên website này.</p>
                                </div>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="block_close_menu">&nbsp; </div>
        </div>
        <a href="javascript:;" id="to_top">
            <img src="<?php echo $this->configView['vnecdn']['images']; ?>/icons/go_to_top_m.png" alt="totop"/>
        </a>
        <div id="slideshow_popup" style="background: #000000; display: none;"></div>
        <div class="clear"></div>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['js']; ?>/mwordcup.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/predict.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/cmt.widget.js"></script>

        <?php
        $pageFolder = ($this->intCategoryId > 0 ? $this->intCategoryId : WORLD_CUP);
        ?>
        <script language="javascript" type="text/javascript">
            var PageHot = 0; //1-Trang tin nổi bật, 0 là trang bình thường.
            var SITE_ID = <?php echo WORLD_CUP; ?>; //Id site Worldcup.
            var PAGE_FOLDER = <?php echo $this->isArticleHotVnE ? '20000' : $pageFolder; ?>; //Id của từng folder.
            var PAGE_DETAIL = <?php echo isset($this->intArticleId) ? 1 : 0 ?>; // 1: là bài chi tiết. còn lại đặt = 0.
            var PolyDate = <?php echo round(microtime(true) * 1000); ?>;
        </script>

        <div id="trackingLandingPage"></div>
        <script type="text/javascript">
            var timeTemp = '<?php echo time(); ?>';
            //document ready
            $(function() {
                common.initLoadMore();

                //Show parser
                if (typeof (Parser) != "undefined") {
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
            //Init tvschedule
            if (typeof (CalendarWorldcup) != "undefined")
            {
                CalendarWorldcup.calendar_parser_id = "calendar";
                CalendarWorldcup.calendar_parser_base_url = '<?php echo $this->configView['url']; ?>';
                CalendarWorldcup.parse();
            }
        </script>
        <script type="text/javascript" src="<?php echo $this->configView['polyads']['core']; ?>/m_r2.js"></script>
        <script type="text/javascript" src="<?php echo $this->configView['polyads']['url']; ?>/Vals/35/0/916/Val.js"></script>
        <script type="text/javascript">try{Poly_showads();}catch(e){}</script>
    </body>
</html>