<!DOCTYPE html>
<html>
    <head>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="Vnexpress.net" />

        <!-- iPad icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/72x72.png" sizes="72x72" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="144x144" />
        <!-- iPhone and iPod touch icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" sizes="57x57" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="114x114" />
        <!-- Nokia Symbian -->
        <link rel="nokia-touch-icon" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" />
        <!-- Android icon precomposed so it takes precedence -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="1x1" />
        <!-- InstanceBeginEditable name="doctitle" -->
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta content="VnExpress" property="og:site_name" />
        <meta content="<?php echo $this->escape($this->ogType); ?>" property="og:type" />
        <meta content="<?php echo $this->escape($this->ogTitle); ?>" itemprop="headline" property="og:title" />
        <meta content="<?php echo $this->ogUrl; ?>" itemprop="url" property="og:url" />
        <meta content="<?php echo $this->ogImage; ?>" itemprop="thumbnailUrl" property="og:image" />
        <meta content="<?php echo $this->escape($this->ogDescription); ?>" itemprop="description" property="og:description" />
        <?php
        $isDetailArticle = isset($this->articleTrackingId) && is_numeric($this->articleTrackingId) && $this->articleTrackingId > 0;
        $isCategoryPolyAds = isset($this->intCateIdPolyAds) && is_numeric($this->intCateIdPolyAds) && $this->intCateIdPolyAds > 0;
        //Proccess category id
        $tt_category_id = $isCategoryPolyAds ? $this->intCateIdPolyAds : WORLD_CUP;
        $tt_article_id = $isDetailArticle ? $this->articleTrackingId : $tt_category_id;
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/general.css" media="all" />
        <?php echo $this->headLink(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var site_id = <?php echo SITE_ID; ?>;
            var img_url = '<?php echo $this->configView['images']; ?>';
            var css_url = '<?php echo $this->configView['css']; ?>';
            var base_url = '<?php echo $this->configView['url']; ?>';
            var device_env = <?php echo DEVICE_ENV; ?>;
            var article_id = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>;
            var vne_url = '<?php echo $this->configView['url_vne']; ?>';
            var interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = <?php echo ACTIVE_CAPCHA; ?>;
            document.domain = '<?php echo DOMAIN_VNE ?>';
            var application_env = '<?php echo APPLICATION_ENV; ?>';
        </script>
        <!-- JS -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/libs/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutils.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
            /*GA - Tracking pageview*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_setDomainName', 'vnexpress.net']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['a._setAccount', 'UA-249346-22']);
            _gaq.push(['a._trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-37']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-29374284-26']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();
        </script>
    </head>
    <body>
        <div>
            <div id="wrapper_page">
                <div id="wrapper_container">
                    <div id="container">
                        <?php
                        $matchDetail = $this->matchDetail;
                        $team1 = $this->team1;
                        $team2 = $this->team2;
                        $this->flag_dd = isset($this->matchDetail['matchTime']) && !empty($this->matchDetail['matchTime']) && $this->matchDetail['matchTime'] <= 80 ? 1 : 0;
                        ?>
                        <div class="line_gray line_page width_common" id="container_live">
                            <div id="col_left">
                                <div class="page_trandau width_common">
                                    <?php
                                    echo $this->render('match/box/mheader.phtml');
                                    ?>
                                    <div class="vongloai_vongbang tab_content">
                                        <div id="tab_tuongthuat" class="content active">
                                            <?php
                                            if ($this->tuongThuat['relate_id'] > 0)
                                            {
                                                ?>
                                                <div class="box_width_common" id="box_details_news" data-liveblog-active="<?php echo ((($this->tuongThuat['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                                                    <div class="main_content_detail width_common">
                                                        <div class="title_news">
                                                            <h1><?php echo $this->tuongThuat['title_format']; ?></h1>
                                                        </div>
                                                        <div class="short_intro txt_666"><?php echo $this->tuongThuat['lead']; ?></div>
                                                        <div class="width_common fck_detail">
                                                            <?php echo $this->matchDetail['dataReport']; ?>
                                                        </div>
                                                        <div class="width_common">
                                                            <div class="live_post_dienbien">
                                                                <a href="<?php echo $this->strLinkTuongThuat; ?>" title="Diễn biến chính của trận đấu" class="short_live">Xem diễn biến chính của trận đấu</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <script type="text/javascript">
                                                    (function() {
                                                        var req = require.config({
                                                            context: 'body-content',
                                                            baseUrl: '<?php echo $this->configView['vnecdn']['js'], '/live'; ?>'
                                                        });
                                                        req(['livenews']);
                                                    })();
                                                    if (typeof (Parser) != "undefined") {
                                                        Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                                                        Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                                                        Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                                                        Parser.SITE_ID = <?php echo SITE_ID; ?>;
                                                        Parser.AUTO_PLAY = 1;
                                                        Parser.parseAll();
                                                    }
                                                    if (typeof(common.resizeImageDetail) != 'undefined') {
                                                        common.resizeImageDetail();
                                                        $(window).resize(function() {
                                                            common.delayFireOnce(1000).done(function() {
                                                                common.resizeImageDetail();
                                                            });
                                                        });
                                                    }
                                                </script>
                                                <?php
                                            }
                                            ?>
                                            <div class="box_category width_common space_box box_dudoan" style="border-bottom:none;">
                                                <div class="title_box_detailpage width_common">
                                                    <div class="txt_main_category"><a>Dự đoán</a></div>
                                                </div>
                                                <div class="content_box_category width_common">
                                                    <div class="block_dudoan category_guess_score">
                                                        <table>
                                                            <thead>
                                                                <tr>
                                                                    <td class="minutes" colspan="3"></td>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr class="current">
                                                                    <td class="main_team">
                                                                        <img width="40" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                                                        <p><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><?php echo $team1['name']; ?></a></p>
                                                                    </td>
                                                                    <td class="score">
                                                                        <div class="width_common">
                                                                            <?php
                                                                            if ($this->flag_dd || ($matchDetail['status'] == 2)) //thoi gian dang dien ra <80 or tran dau da ket thuc
                                                                            {
                                                                                ?>
                                                                                <div class="width_common">
                                                                                    <span class="box no-border"><?php echo $this->matchDetail['goal1']; ?></span>
                                                                                    <span class="box no-border">-</span>
                                                                                    <span class="box no-border"><?php echo $this->matchDetail['goal2']; ?></span>
                                                                                </div>
                                                                                <?php
                                                                            }
                                                                            if ($matchDetail['status'] == 1 || $this->flag_dd)
                                                                            {
                                                                                ?>
                                                                                <div class="width_common">
                                                                                    <span class="box"><input id="goalteam1" name="goalteam1" type="text" data-rel="<?php echo $matchDetail['id']; ?>-team1"></span>
                                                                                    <span class="box no-border">-</span>
                                                                                    <span class="box"><input id="goalteam2" name="goalteam2" type="text" data-rel="<?php echo $matchDetail['id']; ?>-team2"></span>
                                                                                </div>
                                                                                <?php
                                                                            }
                                                                            ?>
                                                                        </div>
                                                                    </td>
                                                                    <td class="sub_team">
                                                                        <img width="40" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                                                        <p><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><?php echo $team2['name']; ?></a></p></td>
                                                                </tr>
                                                                <?php
                                                                if ($this->matchDetail['status'] == 1 || $this->flag_dd)
                                                                {
                                                                    ?>
                                                                    <tr class="submit">
                                                                        <td class="main_team"></td>
                                                                        <td class="score">
                                                                            <button style="cursor: pointer;" class="predict-match" data-rel="<?php echo $matchDetail['id']; ?>" data-predict-type="6" data-time="<?php echo $matchDetail['matchTime']; ?>" data-predict-text="<?php echo $team1['name']; ?> vs <?php echo $team2['name']; ?>">Gửi</button>
                                                                            <input id="matchid" name="matchid" type="hidden" value="<?php echo $matchDetail['id']; ?>" />
                                                                        </td>
                                                                        <td class="sub_team"></td>
                                                                    </tr>
                                                                    <?php
                                                                }
                                                                ?>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="width_common total_source_guess" style="display:none;">
                                                <div class="title text_center predict-statistic-total"></div>
                                                <table class="width_common predict-statistic" data-rel="<?php echo $this->matchDetail['id']; ?>" data-text="<?php echo $this->team1['name']; ?>">
                                                </table>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <!-- end page_trangdau -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="block_close_menu">&nbsp; </div>
        </div>
        <div id="slideshow_popup" style="background: #000000; display: none;"></div>
        <div class="clear"></div>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['js']; ?>/mwordcup.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/predict.js"></script>
        <div id="trackingLandingPage"></div>
        <script type="text/javascript">
            var timeTemp = '<?php echo time(); ?>';
            //document ready
            $(function() {
                //Show parser
                if (typeof (Parser) != "undefined") {
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
        </script>

    </body>
</html>