<?php
$matchDetail = $this->matchDetail;
$team1 = $this->team1;
$team2 = $this->team2;
$this->flag_dd = isset($this->matchDetail['matchTime']) && !empty($this->matchDetail['matchTime']) && $this->matchDetail['matchTime'] <= 80 ?1:0;
?>
<div class="line_gray line_page width_common" id="container_live">
    <div id="col_left">
        <?php
        if (DEVICE_ENV != 1)
        {
            ?>
            <div class="block_slder_top space_box" id="top_fixture_worldcup">
                <div style="text-align: center;"><p style="padding: 25px 0;">Đang tải dữ liệu...</p></div>
            </div>
            <?php
        }
        ?>
        <div class="page_trandau width_common">
            <div class="block_clear_men"><a target="_blank" onclick="thethao.trackingImpression()" href="http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=20&mc=click&pli=10045207&PluID=0&ord=<?php echo time();?>" title="Clear Men"><img src="<?php echo $this->configView['images']; ?>/graphics/img_clearmen.png" /></a></div>
            <?php
            if (DEVICE_ENV != 1)
            {
                echo $this->render('match/box/header.phtml');
            }
            else
            {
                echo $this->render('match/box/mheader.phtml');
            }
            ?>
            <div class="vongloai_vongbang tab_content">
                <ul class="tabs">
                    <li><a href="<?php echo $this->configView['url'] . "/thong-ke/{$this->seoTitle}-{$this->matchDetail['id']}" ?>" title="Thống kê trận đấu <?php echo $this->matchDetail['name_format']; ?>" class="tab">Thống kê</a></li>
                    <li><a href="<?php echo $this->configView['url'] . "/tuong-thuat/{$this->seoTitle}-{$this->matchDetail['id']}" ?>" title="Diễn biết trận đấu <?php echo $this->matchDetail['name_format']; ?>" class="tab">Diễn biến</a></li>
                    <li><a href="<?php echo $this->configView['url'] . "/report/{$this->seoTitle}-{$this->matchDetail['id']}" ?>" title="Tổng thuật trận đấu <?php echo $this->matchDetail['name_format']; ?>" class="tab active">Tổng thuật</a></li>
                </ul>
                <div id="tab_tuongthuat" class="content active">
                    <?php
                    if ($this->tuongThuat['relate_id'] > 0)
                    {
                        ?>
                        <div class="box_width_common" id="box_details_news" data-liveblog-active="<?php echo ((($this->tuongThuat['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                            <div class="main_content_detail width_common">
                                <div class="title_news">
                                    <h1><?php echo $this->tuongThuat['title_format']; ?></h1>
                                </div>
                                <div class="short_intro txt_666"><?php echo $this->tuongThuat['lead']; ?></div>
                                <div class="width_common fck_detail">
                                    <?php echo $this->matchDetail['dataReport'];?>
                                </div>
                                <div class="width_common">
									<div class="live_post_dienbien">
										<a href="<?php echo $this->strLinkTuongThuat; ?>" title="Diễn biến chính của trận đấu" class="short_live">Xem diễn biến chính của trận đấu</a>
									</div>
								</div>
                                <div class="space_box width_common">
                                    <?php echo $this->render('/common/box_share_bottom.phtml'); ?>
                                </div>
                                <?php
                                if (!empty($this->tuongThuat['list_tag'])) : ?>
                                    <div class="block_tag width_common space_bottom_20">
                                        <div class="txt_tag">Tags</div>
                                        <?php foreach ($this->tuongThuat['list_tag'] as $list_tag) : ?>
                                            <a href="<?php echo $this->configView['url_vne'].$list_tag['tag_url']; ?>" title="<?php echo $list_tag['tag_name_format']; ?>" class="tag_item"><?php echo $list_tag['tag_name']; ?></a>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <script type="text/javascript">
                            (function() {
                                var req = require.config({
                                    context: 'body-content',
                                    baseUrl: '<?php echo $this->configView['vnecdn']['js'], '/live'; ?>'
                                });
                                req(['livenews']);
                            })();
                            if (typeof (Parser) != "undefined") {
                                Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                                Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                                Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                                Parser.SITE_ID = <?php echo SITE_ID; ?>;
                                Parser.AUTO_PLAY = 1;
                                Parser.parseAll();
                            }
                            if (typeof(common.resizeImageDetail) != 'undefined') {
                                common.resizeImageDetail();
                                $(window).resize(function() {
                                    common.delayFireOnce(1000).done(function() {
                                        common.resizeImageDetail();
                                    });
                                });
                            }
                        </script>
                        <?php
                    }
                    ?>
                    <div class="box_category width_common space_box box_dudoan" style="border-bottom:none;">
                        <div class="title_box_detailpage width_common">
                          <div class="txt_main_category"><a>Dự đoán</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <div class="block_dudoan category_guess_score">
                                <table>
                                    <thead>
                                        <tr>
                                            <td class="minutes" colspan="3"></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="current">
                                            <td class="main_team">
                                                <img width="40" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                                <p><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><?php echo $team1['name']; ?></a></p>
                                            </td>
                                            <td class="score">
                                                <div class="width_common">
                                                    <?php
                                                    if($this->flag_dd || ($matchDetail['status'] == 2)) //thoi gian dang dien ra <80 or tran dau da ket thuc
                                                    {
                                                        ?>
                                                        <div class="width_common">
                                                            <span class="box no-border"><?php echo $this->matchDetail['goal1']; ?></span>
                                                            <span class="box no-border">-</span>
                                                            <span class="box no-border"><?php echo $this->matchDetail['goal2']; ?></span>
                                                        </div>
                                                        <?php
                                                    }
                                                    if($matchDetail['status'] ==1 || $this->flag_dd)
                                                    {
                                                    ?>
                                                        <div class="width_common">
                                                            <span class="box"><input id="goalteam1" name="goalteam1" type="text" data-rel="<?php echo $matchDetail['id']; ?>-team1"></span>
                                                            <span class="box no-border">-</span>
                                                            <span class="box"><input id="goalteam2" name="goalteam2" type="text" data-rel="<?php echo $matchDetail['id']; ?>-team2"></span>
                                                        </div>
                                                    <?php
                                                    }
                                                    ?>
                                                </div>
                                            </td>
                                            <td class="sub_team">
                                                <img width="40" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                                <p><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><?php echo $team2['name']; ?></a></p></td>
                                        </tr>
                                        <?php
                                        if ($this->matchDetail['status'] ==1 || $this->flag_dd)
                                        {
                                        ?>
                                        <tr class="submit">
                                            <td class="main_team"></td>
                                            <td class="score">
                                                <button style="cursor: pointer;" class="predict-match" data-rel="<?php echo $matchDetail['id']; ?>" data-predict-type="6" data-time="<?php echo $matchDetail['matchTime']; ?>" data-predict-text="<?php echo $team1['name']; ?> vs <?php echo $team2['name']; ?>">Gửi</button>
                                                <input id="matchid" name="matchid" type="hidden" value="<?php echo $matchDetail['id']; ?>" />
                                            </td>
                                            <td class="sub_team"></td>
                                        </tr>
                                        <?php
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="width_common total_source_guess" style="display:none;">
                        <div class="title text_center predict-statistic-total"></div>
                        <table class="width_common predict-statistic" data-rel="<?php echo $this->matchDetail['id']; ?>" data-text="<?php echo $this->team1['name']; ?>">
                        </table>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page_trangdau -->
    </div>
    <div id="col_right">
        <?php
        //Comment
        echo DEVICE_ENV != 4 ? $this->render('/block/comment_match.phtml') : $this->render('/block/comment_match_live.phtml');
        //block left
        echo $this->GetBlock('left');
        ?>
    </div>
</div>