<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        echo $this->headMeta();
        $tt_category_id = isset($this->intCategoryId) ? $this->intCategoryId : SITE_ID;
        $tt_article_id = isset($this->intArticleId) ? $this->intArticleId : $tt_category_id;
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <meta name="tt_site_id" content="<?php echo SITE_ID; ?>" />
        <link rel="alternate" href="<?php echo $this->configView['url']; ?>" hreflang="vi-vn" />
        <!--Title-->
        <?php echo $this->headTitle(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-18']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-249346-37']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();

            var site_id     = <?php echo SITE_ID; ?>,
                img_url   = '<?php echo $this->configView['images']; ?>',
                css_url     = '<?php echo $this->configView['css']; ?>',
                base_url    = '<?php echo $this->configView['url']; ?>',
                device_env  = <?php echo DEVICE_ENV; ?>,
                article_id  = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>,
                vne_url     = '<?php echo $this->configView['url_vne']; ?>',
                interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = 0;
            document.domain = '<?php echo DOMAIN_VNE ?>';
        </script>
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/mobile_common.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/detail_common.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/msport.css" media="all" />
        <?php echo $this->headLink(); ?>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
    </head>
    <body>
        <div id="page">
            <div id="wrapper_container">
                <div id="container">
                    <div class="width_common">
                        <?php
                        $arrData = $this->arrArticleDetail;
                        ?>
                        <div id="detail_page" class="width_common line_col">
                            <div id="col_660" class="left">
                                <div class="box_width_common" id="box_details_news" data-sort-newest="<?php echo (($arrData['privacy'] & 16384) ? 'true' : 'false'); ?>" data-matchsport="true" data-liveblog-active="<?php echo ((($arrData['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                                    <div class="w670 left">
                                        <div class="main_content_detail width_common">
                                            <?php
                                            if ($this->viewApp == 'app')
                                            {
                                                ?>
                                                <div class="div-fbook width_common title_div_fbook" id="timer_update">
                                                    <?php
                                                    echo $this->DateTimeFormat($arrData['publish_time'], 'long');
                                                    ?>
                                                </div>
                                                <div class="title_news">
                                                    <h1><?php echo $arrData['title_format']; ?></h1>
                                                </div>
                                                <div class="short_intro txt_666"><?php echo $arrData['lead']; ?></div>
                                                <?php
                                                if (!empty($arrData['reference_detail']))
                                                {
                                                    $arrRef = array();
                                                    foreach ($arrData['reference_detail'] as $index => $reference)
                                                    {
                                                        $index++;
                                                        $arrRef[] = '<li><a tabindex="'.$index.'" alt="' . $reference['title_format'] . '" title="' . $reference['title_format'] . '" href="' . $reference['share_url'] . '">' . $reference['title'] . '</a></li>';
                                                    }
                                                    ?>
                                                    <div class="relative_new">
                                                        <ul class="list_news_dot_3x3_300">
                                                            <?php
                                                            echo implode('', $arrRef);
                                                            ?>
                                                        </ul>
                                                    </div>
                                                    <?php
                                                }
                                            }
                                            if (isset($this->articleExtra['key_infor']) && !empty($this->articleExtra['key_infor']))
                                            {
                                                ?>
                                                <div class="fck_detail news_lead">
                                                    <?php echo $this->articleExtra['key_infor']; ?>
                                                </div>
                                                <?php
                                            }
                                            if ($this->isReview)
                                            {
                                                ?>
                                                <div class="vongloai_vongbang tab_content"<?php echo $this->viewApp == 'app_sport_live' ? ' style="margin-top: 10px;"' : ''; ?>>
                                                    <ul class="tabs">
                                                        <li><a class="tab active" title="Diễn biến">Diễn biến</a></li>
                                                        <li><a class="tab" title="Tổng thuật" href="<?php echo $this->strLinkTongThuat; ?>">Tổng thuật</a></li>
                                                    </ul>
                                                </div>
                                            <?php
                                            }
                                            ?>
                                            <div class="block_filter_live">
                                                <div class="filter_left">
                                                    <span class="active highlight_filter" style="display: none"><input type="checkbox" id="checkNew" class="checking_filter"> <label for="checkNew">Nổi bật</label></span>
                                                    <?php if (DEVICE_ENV != 1 && !empty($this->articleExtra['location_live'])) { ?>
                                                    <a><?php echo 'Giờ '. ($this->articleExtra['location_live']) . ' (GMT'. $this->articleExtra['timezone']. ')'; ?></a>
                                                    <?php } ?>
                                                </div>
                                                <div class="filter_right">
                                                    <a href="javascript:;" class="sort-live latest">Mới nhất</a>
                                                    <a href="javascript:;" class="sort-live oldest">Cũ nhất</a>
                                                </div>
                                            </div>
                                            <?php if (DEVICE_ENV == 1 && !empty($this->articleExtra['location_live'])) { ?>
                                            <div class="block_filter_live">
                                                <div class="filter_left">
                                                    <a><?php echo 'Giờ '. ($this->articleExtra['location_live']) . ' (GMT'. $this->articleExtra['timezone']. ')'; ?></a>
                                                </div>
                                            </div>
                                            <?php } ?>
                                            <div class="live_post_status" id="live_post_status" style="display: none">
                                                <a href="javascript:;" class="short_live">Có <span id="live-updates-counter"></span> tin mới được cập nhật</a>
                                            </div>
                                            <div id="container_tab_live" class="width_common" data-update-uri="<?php echo $this->configView['url_vne'] . '/detail/block?id=', $arrData['article_id']; ?>" data-article-id="<?php echo $arrData['article_id']; ?>">
                                                <ul id="list_live" <?php echo (($arrData['privacy'] & 16384) ? '' : 'class="reversed"'); ?>>
                                                    <?php
                                                    echo (($arrData['privacy'] & 16384) ? '<li id="live-updates-wrapper" class="no_space"></li>' : '');
                                                    if (!empty($this->arrBlockDataId))
                                                    {
                                                        foreach ($this->arrBlockDataId as $blockId)
                                                        {
                                                            $blockDetail = $this->objLive->getBlockDetail($blockId);

                                                            if (empty($blockDetail))
                                                            {
                                                                continue;
                                                            }
                                                            $count = count($blockDetail['article_reference_id']);
                                                            //class High light
                                                            $classHighLight = $blockDetail['highlight'] ? ' high-light' : '';
                                                            ?>
                                                            <li id="block-<?php echo $blockDetail['published_time']; ?>" data-datetime="<?php echo date('Y-m-d',$blockDetail['published_time']); ?>" data-block-id="<?php echo $blockId; ?>" class="block<?php echo $classHighLight; ?>">
                                                                <div class="minutes">
                                                                    <?php
                                                                    $time = trim($blockDetail['display_time']);
                                                                    if ((!empty($time)) && (strpos($time, '#') === false))
                                                                    {
                                                                        ?>
                                                                        <span class="text_minutes <?php echo ($blockDetail['highlight'] ? 'special_time' : ''); ?>" datetime="<?php echo $blockDetail['published_time']; ?>">
                                                                            <strong><?php echo $time; ?></strong>
                                                                        </span>
                                                                    <?php } ?>
                                                                    <img src="<?php echo $this->configView['images'], '/graphics/img_blank.gif'; ?>" alt="icon" class="icon_live <?php echo empty($blockDetail['icon']) ? 'icon_dot_live' : $blockDetail['icon']; ?>">
                                                                </div>
                                                                <div class="text_live">
                                                                    <?php
                                                                    echo $blockDetail['block_content'];
                                                                    if (!empty($blockDetail['article_reference_id']))
                                                                    {
                                                                        $this->objArticle->setIdBasic($blockDetail['article_reference_id']);

                                                                        if ($count == 1)
                                                                        {
                                                                            $article = $this->objArticle->getArticleBasic($blockDetail['article_reference_id'][0]);
                                                                            ?>
                                                                            <div class="block_image_news width_common">
                                                                                <?php
                                                                                if (!empty($article['thumbnail_url']))
                                                                                {
                                                                                    ?>
                                                                                    <div class="thumb">
                                                                                        <a href="<?php echo $article['share_url']; ?>">
                                                                                            <img src="<?php echo $this->ImageurlArticle($article, 'size6'); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                                                        </a>
                                                                                        <?php echo $this->ArticleTypeIcon($article); ?>
                                                                                    </div>
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                                <h2 class="title_news">
                                                                                    <a href="<?php echo $article['share_url']; ?>" class="txt_link">
                                                                                        <?php echo $article['title'] ?>
                                                                                        <span class="no_wrap">
                                                                                            <?php echo $this->ArticleViewIcon($article); ?>
                                                                                        </span>
                                                                                    </a>

                                                                                </h2>
                                                                                <div class="news_lead" data-mobile-href="<?php echo $article['share_url']; ?>">
                                                                                    <?php echo $article['lead']; ?>
                                                                                </div>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                        else
                                                                        {
                                                                            ?>
                                                                            <div class="list_dot_3x3">
                                                                                <?php
                                                                                foreach ($blockDetail['article_reference_id'] as $id)
                                                                                {
                                                                                    $article = $this->objArticle->getArticleBasic($id);
                                                                                    if (empty($article))
                                                                                    {
                                                                                        continue;
                                                                                    }
                                                                                    ?>
                                                                                    <div class="dot_item">
                                                                                        <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>">
                                                                                            <?php echo $article['title']; ?>
                                                                                        </a>
                                                                                    </div>
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                    }
                                                                    ?>
                                                                </div>
                                                                <div class="clear"></div>
                                                            </li>
                                                            <?php
                                                        }
                                                    }
                                                    echo (($arrData['privacy'] & 16384) ? '' : '<li id="live-updates-wrapper" class="no_space"></li>');
                                                    ?>
                                                </ul>
                                                <div class="width_common fck_detail">
                                                    <?php
                                                    echo $arrData['content'];
                                                    ?>
                                                </div>
                                            </div>
                                            <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/require.min.js"></script>
                                            <script type="text/javascript">
                                                (function() {
                                                    var req = require.config({
                                                        context: 'main_content_detail',
                                                        baseUrl: '<?php echo $this->configView['vnecdn']['js'], '/live'; ?>'

                                                    });
                                                    req(['livenews']);
                                                })();
                                            </script>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="block_close_menu">&nbsp;</div>
        </div>
        <div class="clear"></div>
        <script src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutilsdetail.js"></script>
        <script type="text/javascript">
            $(function(){
                if(typeof(Parser) != "undefined"){
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
                if (typeof(common.resizeImageDetail) != 'undefined') {
                    common.resizeImageDetail();
                    $(window).resize(function() {
                        common.delayFireOnce(1000).done(function() {
                            common.resizeImageDetail();
                        });
                    });
                }
                if(typeof(common) != "undefined"){
                    common.initCommon();
                }
            });
        </script>
    </body>
</html>