<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        echo $this->headMeta();
        $tt_category_id = isset($this->intCategoryId) ? $this->intCategoryId : SITE_ID;
        $tt_article_id = isset($this->intArticleId) ? $this->intArticleId : $tt_category_id;
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <meta name="tt_site_id" content="<?php echo SITE_ID; ?>" />
        <link rel="alternate" href="<?php echo $this->configView['url']; ?>" hreflang="vi-vn" />
        <!--Title-->
        <?php echo $this->headTitle(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-18']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-249346-37']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();

            var site_id     = <?php echo SITE_ID; ?>,
                img_url   = '<?php echo $this->configView['images']; ?>',
                css_url     = '<?php echo $this->configView['css']; ?>',
                base_url    = '<?php echo $this->configView['url']; ?>',
                device_env  = <?php echo DEVICE_ENV; ?>,
                article_id  = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>,
                vne_url     = '<?php echo $this->configView['url_vne']; ?>',
                interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = 0;
            document.domain = '<?php echo DOMAIN_VNE ?>';
        </script>
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/mobile_common.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/detail_common.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/msport.css" media="all" />
        <?php echo $this->headLink(); ?>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
    </head>
    <body>
        <div id="page">
            <div id="wrapper_container">
                <div id="container">
                    <div class="width_common">
                        <div id="detail_page" class="width_common line_col">
                            <div id="col_660" class="left">
                                <div class="box_width_common" id="box_details_news">
                                    <div class="w670 left">
                                        <div class="main_content_detail width_common">
                                            <div class="width_common line_col_480 space_bottom_20">
                                                <div class="block_col_480">
                                                    <div id="left_calculator">
                                                        <div class="div-fbook width_common title_div_fbook">
                                                            <div class="block_timer left txt_666"><?php echo $this->DateTimeFormat($this->arrArticleDetail['publish_time'], 'long'); ?></div>
                                                        </div>
                                                        <div class="title_news">
                                                            <h1><?php echo $this->arrArticleDetail['title']; ?></h1>
                                                        </div>
                                                        <div class="short_intro txt_666">
                                                            <?php echo $this->arrArticleDetail['lead']; ?>
                                                        </div>
                                                        <?php
                                                        if (!empty($this->arrArticleDetail['reference_detail']))
                                                        {
                                                            $arrRef = array();
                                                            foreach ($this->arrArticleDetail['reference_detail'] as $index => $reference)
                                                            {
                                                                $index++;
                                                                $arrRef[] = '<li><a tabindex="'.$index.'" alt="' . $reference['title_format'] . '" title="' . $reference['title_format'] . '" href="' . $reference['share_url'] . '">' . $reference['title'] . '</a></li>';
                                                            }
                                                            ?>
                                                            <div class="relative_new">
                                                                <ul class="list_news_dot_3x3_300">
                                                                        <?php
                                                                        echo implode('', $arrRef);
                                                                        ?>
                                                                </ul>
                                                            </div>
                                                            <?php
                                                        }
                                                        ?>
                                                        <div class="fck_detail width_common">
                                                            <?php echo $this->arrArticleDetail['content']; ?>
                                                        </div>
                                                        <script type="text/javascript">
                                                            if(typeof(Parser) != "undefined"){
                                                                Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                                                                Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                                                                Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                                                                Parser.SITE_ID = <?php echo SITE_ID; ?>;
                                                                Parser.AUTO_PLAY = 1;
                                                                Parser.parseAll();
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                                <div class="clear">&nbsp;</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="block_close_menu">&nbsp;</div>
        </div>
        <div class="clear"></div>
        <script src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutilsdetail.js"></script>
        <script type="text/javascript">
            $(function(){
                if(typeof(Parser) != "undefined"){
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
                if (typeof(common.resizeImageDetail) != 'undefined') {
                    common.resizeImageDetail();
                    $(window).resize(function() {
                        common.delayFireOnce(1000).done(function() {
                            common.resizeImageDetail();
                        });
                    });
                }
                if(typeof(common) != "undefined"){
                    common.initCommon();
                }
            });
        </script>
    </body>
</html>