<?php
$arrData = $this->arrArticleDetail;
$timeUpdate = (isset($this->timeUpdate) && !empty($this->timeUpdate)) ? $this->timeUpdate : time();
$liveBlog = ((($arrData['privacy'] & 8) == 8) ? 'true' : 'false');
?>
<div id="detail_page_live" class="width_common line_col">
    <div id="col_660" class="left">
        <div class="box_width_common" id="box_details_news" data-liveblog-active="<?php echo $liveBlog; ?>">
            <div class="w670 left">
                <div class="main_content_detail width_common">
                    <?php
                    if (DEVICE_ENV != 1)
                    {
                    ?>
                    <div class="block_timer_share">
                        <div class="block_timer left txt_666" id="timer_update">
                            <?php
                            echo '<b>Cập nhật:</b> ', $this->DateTimeFormat($timeUpdate, 'long');
                            ?>
                        </div>
                        <div class="block_share right">
                            <?php echo $this->render('detail/box/box_share_photo.phtml'); ?>
                        </div>
                    </div>
                    <?php
                    }
                    else {
                    ?>
                    <div class="div-fbook width_common title_div_fbook">
                        <div class="block_timer left txt_666" id="timer_update">
                            <?php
                            echo '<b>Cập nhật:</b> ', $this->DateTimeFormat($timeUpdate, 'long');
                            ?>
                        </div>
                    </div>
                    <?php
                    }
                    ?>
                    <div class="title_news">
                        <h1><?php echo $arrData['title_format']; ?></h1>
                    </div>
                    <div class="short_intro txt_666"><?php echo $arrData['lead']; ?></div>
                    <?php
                    if (!empty($arrData['reference_detail']))
                    {
                        $arrRef = array();
                        foreach ($arrData['reference_detail'] as $reference)
                        {
                            $arrRef[] = '<a alt="' . $reference['title_format'] . '" title="' . $reference['title_format'] . '" href="' . $reference['share_url'] . '">' . $reference['title'] . '</a>';
                        }
                        ?>
                        <div class="relative_new">
                            <ul class="list_news_dot_3x3_300">
                                <li>
                                    <?php
                                    echo DEVICE_ENV==1?implode('&nbsp;&nbsp;/&nbsp;&nbsp;', $arrRef):implode('&nbsp;/&nbsp;', $arrRef);
                                    ?>
                                </li>
                            </ul>
                        </div>
                        <?php
                    }
                    ?>
                    <div class="vongloai_vongbang tab_content">
                        <ul class="tabs">
                            <li><a class="tab" title="Diễn biến" href="<?php echo $this->strLinkTuongThuat; ?>">Diễn biến</a></li>
                            <li><a class="tab active" title="Tổng thuật">Tổng thuật</a></li>
                        </ul>
                    </div>
                    <div class="fck_detail width_common">
                        <?php echo $arrData['content_review'];?>
                    </div>
                    <div id="container_tab_live" class="width_common">
                        <div class="live_post_dienbien">
                            <a class="short_live" href="<?php echo $this->strLinkTuongThuat; ?>" title="Xem diễn biến chính của trận đấu">Xem diễn biến chính của trận đấu</a>
                        </div>
                    </div>
                    <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/require.min.js"></script>
                    <script type="text/javascript">
                        if (device_env != 1 && typeof(common.resizeImageDetail) != 'undefined') {
                            common.resizeImageDetail();
                            $(window).resize(function() {
                                common.delayFireOnce(1000).done(function() {
                                    common.resizeImageDetail();
                                });
                            });
                        }
                        (function() {
                            var req = require.config({
                                context: 'main_content_detail',
                                baseUrl: '<?php echo $this->configView['vnecdn']['js'],'/live'; ?>'
                            });
                            req(['livenews']);
                        })();
                    </script>
                    <?php
                    echo $this->render('/common/box_share_bottom.phtml');
                    //********************* Process Tin liên quan: Topic + Link chéo *************************//
                    //Check empty
                    $notEmptyTopic         = !empty($this->arrArticleDetail['list_topic_id']) && is_array($this->arrArticleDetail['list_topic_id']);
                    $notEmptyReferenceSite = !empty($this->arrArticleDetail['list_reference_sites_id']) && is_array($this->arrArticleDetail['list_reference_sites_id']);
                    //Check
                    if ( $notEmptyTopic || $notEmptyReferenceSite )
                    {
                        //set id
                        $id_box_tinlienquan = 'box_tinlienquan';

                        //set class
                        $class_mg_bottom_20	= "mg_bottom_20";

                        //check show style topic = 2
                        if ($notEmptyTopic && $this->topic_show_style==2 )
                        {
                            ?>
                            <div id="<?php echo $id_box_tinlienquan; ?>" class="block_maybay width_common <?php echo $class_mg_bottom_20;?>">
                                <div class="title_maybay width_common">
                                    <a class="left txt_vne" href="<?php echo $this->arrTopicDetail['share_url']; ?>" title="<?php echo $this->arrTopicDetail['title_format']; ?>"><?php echo $this->arrTopicDetail['title']; ?></a>
                                </div>
                                <div class="content_maybay width_common">
                                    <div class="list_3image_inrow">
                                        <ul class="list_news_image">
                                            <?php
                                            foreach ( $this->arrTopic as $id )
                                            {
                                                $articleDetail = $this->objArticle->getArticleBasic($id);
                                                if ( empty($articleDetail) ) continue;
                                                ?>
                                                <li>
                                                    <?php
                                                    if ( !empty($articleDetail['thumbnail_url']) )
                                                    {
                                                        ?>
                                                        <div class="thumb">
                                                            <a href="<?php echo $articleDetail['share_url']; ?>" title="<?php echo $articleDetail['title_format']; ?>">
                                                                <img alt="<?php echo $articleDetail['title_format']; ?>" src="<?php echo $this->ImageurlArticle($articleDetail, 'size1'); ?>" />
                                                            </a>
                                                        </div>
                                                    <?php
                                                    }//end if
                                                    ?>
                                                    <h2 class="title_news">
                                                        <a href="<?php echo $articleDetail['share_url']; ?>" class="txt_link" title="<?php echo $articleDetail['title_format']; ?>"><?php echo $articleDetail['title_format']; ?></a>
                                                    </h2>
                                                </li>
                                            <?php
                                            }//end foreach
                                            ?>
                                        </ul>
                                        <div class="block_view_more">
                                            <a class="txt_view_more" href="<?php echo $this->arrTopicDetail['share_url']; ?>" title="Xem thêm">Xem thêm</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php
                            $class_mg_bottom_20 = '';
                        }//end if
                        //check list refrence or show style topic = 1
                        if ( $notEmptyReferenceSite || ($notEmptyTopic && $this->topic_show_style==1) )
                        {
                            ?>
                            <div id="<?php echo $id_box_tinlienquan; ?>" class="width_common <?php echo $class_mg_bottom_20;?>">
                                <?php
                                if ( $notEmptyTopic && $this->topic_show_style==1 )
                                {
                                    ?>
                                    <div class="title_box_category style_02">
                                        <h2 class="txt_main_category">
                                            <a href="<?php echo $this->arrTopicDetail['share_url']; ?>"><?php echo $this->arrTopicDetail['title_format'];?></a>
                                        </h2>
                                    </div>
                                <?php
                                }//end if
                                ?>
                                <div class="content_box_category width_common">
                                    <?php
                                    //********************* Process Topic *************************//
                                    if ( $notEmptyTopic && $this->topic_show_style==1 )
                                    {
                                        ?>
                                        <ul class="list_news_dot_3x3">
                                            <?php
                                            foreach ( $this->arrTopic as $id )
                                            {
                                                $articleDetail = $this->objArticle->getArticleBasic($id);
                                                if ( empty($articleDetail) ) continue;
                                                ?>
                                                <li>
                                                    <a href="<?php echo $articleDetail['share_url']; ?>" title="<?php echo $articleDetail['title_format']; ?>"><?php echo $articleDetail['title_format']; ?></a> <span class="txt_666">(<?php echo $this->DateTimeFormat($articleDetail['publish_time'], 'short'); ?>)</span>
														<span class="no_wrap">
															<img class="icon_content icon_title_<?php echo intval($articleDetail['article_icon']); ?>" alt="" src="<?php echo $this->configView['images'];?>/graphics/img_blank.gif">
                                                            <?php echo $this->ArticleComment($articleDetail); ?>
														</span>
                                                </li>
                                            <?php
                                            }//end foreach
                                            ?>
                                        </ul>
                                        <div class="block_view_more">
                                            <a class="txt_view_more" href="<?php echo $this->arrTopicDetail['share_url']; ?>" title="Xem thêm">Xem thêm</a>
                                        </div>
                                    <?php
                                    }//end if

                                    //********************* Process Link chéo *************************//
                                    //==== Khi đọc các tin thuộc VNEx hoặc các Vertical ====//
                                    //Click link của VNEx hoặc Vertical sẽ đi chính trang
                                    //Click link khác của NgôiSao hoặc iOne sẽ mở Tab mới
                                    if ($notEmptyReferenceSite)
                                    {
                                        //Set flags to know which situation
                                        $flag_vne       = false;
                                        $flag_ione      = false;
                                        $flag_ngoisao   = false;
                                        foreach ( $this->arrArticleDetail['list_reference_sites_id'] as $reference )
                                        {
                                            if (empty($reference)) continue;
                                            switch ( $reference['site_id'] )
                                            {
                                                case $this->configView['othersite']['ione']:
                                                    $flag_ione = true;
                                                    break;
                                                case $this->configView['othersite']['ngoisao']:
                                                    $flag_ngoisao = true;
                                                    break;
                                                default:
                                                    $flag_vne = true;
                                                    break;
                                            }//end switch
                                        }//end foreach
                                        //echo 1;die;
                                        echo $this->partial('detail/box/box_includelink.phtml', array(
                                            'list_reference'    => $this->arrArticleDetail['list_reference_sites_id'],
                                            'flag_vne'          => $flag_vne,
                                            'flag_ione'         => $flag_ione,
                                            'flag_ngoisao'      => $flag_ngoisao,
                                            'has_topic'         => $notEmptyTopic,
                                            'config'            => $this->configView));
                                    }//end if
                                    ?>
                                </div>
                            </div>
                        <?php
                        }//end if
                    }//end if
                    if (!empty($arrData['list_tag'])) : ?>
                        <div class="block_tag width_common space_bottom_20">
                            <div class="txt_tag">Tags</div>
                            <?php foreach ($arrData['list_tag'] as $list_tag) : ?>
                                <a href="<?php echo $list_tag['tag_url']; ?>" title="<?php echo $list_tag['tag_name_format']; ?>" class="tag_item"><?php echo $list_tag['tag_name']; ?></a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <input type="hidden" name="article_id" id="article_id" value="<?php echo $arrData['article_id']; ?>"/>
                </div>
            </div>
        </div>
    </div>
    <div id="col_300" class="right">
        <div class="box_category width_common">
            <div class="banner_300x250">
                <script type="text/javascript">try {Poly_Large(1);}catch(ex){};	</script>
            </div>
        </div>
        <?php
        //Check permission comment
        if ($arrData['iscomment'])
        {
            echo DEVICE_ENV != 4 ? $this->render('/block/comment.phtml') : $this->render('/block/comment_live.phtml');
        }//end if
        ?>
    </div>
</div>

<div class="banner_980x60">
    <?php //echo $this->GetBlock('footer'); ?>
</div>
<div class="clear"></div>
<script type="text/javascript">
    //init send mail
    var article_title = "<?php echo addslashes($arrData['title_format']); ?>",
        article_description = "<?php echo urlencode($arrData['lead']); ?>",
        article_url = "<?php echo $arrData['share_url']; ?>"
        article_image = "<?php echo!empty($arrData['thumbnail_url']) ? $this->ImageurlArticle($arrData, 'size1', -1) : ''; ?>";
    $(function(){
        if (device_env != 1) {
            sendmail.init({
                article_link: '<?php echo $arrData['share_url']; ?>',
                article_title: article_title,
                url_post: '<?php echo $this->configView['url']; ?>/detail/ajaxsendmail'
            });
        } else {
            if (typeof(common.resizeImageDetail) != 'undefined') {
                common.resizeImageDetail();
                $(window).resize(function() {
                    common.delayFireOnce(1000).done(function() {
                        common.resizeImageDetail();
                    });
                });
            }
        }
    });
</script>