<?php
if (!empty ($this->data['data']))
{
    $name = empty($this->layout['title']) ? $this->data['info']['name'] : $this->layout['title'];
?>
<div id="toyota" class="box_category width_common">
    <div class="title_box_category width_common">
        <h2 class="txt_main_category">
            <a href="<?php echo $this->data['info']['share_url']; ?>" title="<?php echo $name; ?>">
                <?php echo $name; ?>
            </a>
        </h2>
    </div>
    <div class="content_box_category width_common">
        <?php
        $idFirstNews    = array_shift($this->data['data']);
        $firstNews      = $this->objArticle->getArticleBasic($idFirstNews);
        ?>
        <h2 class="title_news">
            <a href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>" class="txt_link">
                <?php
                echo $firstNews['title'];
                ?>
            </a>
            <span class="no_wrap">
                <?php echo $this->ArticleViewIcon($firstNews); ?>
                <?php echo $this->ArticleComment($firstNews); ?>
            </span>
        </h2>
        <div class="block_image_news width_common">
            <?php if (DEVICE_ENV != 1){ ?>
                <div class="thumb">
                    <a href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">
                        <img src="<?php echo $this->ImageurlArticle($firstNews, 'size1'); ?>" alt="<?php echo $firstNews['title_format']; ?>" title="<?php echo $firstNews['title_format']; ?>"/>
                    </a>
                    <?php echo $this->ArticleTypeIcon($firstNews); ?>
                </div>
            <?php } else { ?>
                <div class="thumb" data-scale="5/3">
                    <a href="<?php echo $firstNews['share_url']; ?>" class="cover_image image_92" style="background-image: url('<?php echo $this->ImageurlArticle($firstNews, 'size1'); ?>')" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">&nbsp;</a>
                    <?php echo $this->ArticleTypeIcon($firstNews); ?>
                </div>
            <?php } ?>
            <div class="news_lead" data-mobile-href="<?php echo $firstNews['share_url']; ?>">
                <?php
                echo $firstNews['lead'];
                ?>
            </div>
            <?php
            if (!empty($this->data['data']))
            {
            ?>
            <ul class="list_news_dot_3x3_300">
                <?php
                foreach ($this->data['data'] as $id)
                {
                    $article = $this->objArticle->getArticleBasic($id);
                    if (empty($article))
                    {
                        continue;
                    }
                    ?>
                    <li>
                        <h2>
                            <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                <?php echo $article['title']; ?>
                            </a>
                            <span class="no_wrap">
                                <?php echo $this->ArticleViewIcon($article); ?>
                                <?php echo $this->ArticleComment($article); ?>
                            </span>
                        </h2>
                    </li>
                    <?php
                }
                ?>
            </ul>
            <?php
            }
            ?>
        </div>
        <div class="bottom_hop_tac">
            <div class="txt_hoptac">Được hợp tác bởi:</div>
            <div class="nhataitro">
                <a href="http://vnexpress.net/" title="VnExpress" class="vne"><img class="left hoptac" alt="vnexpress logo" title="VnExpress" src="<?php echo $this->configView['images'] ?>/graphics/logo_hoptac_vne.gif"></a>
                <a href="http://toyotamekongfootball.com/" title="Toyota" class="wp"><img alt="Toyota" title="Toyota" src="<?php echo $this->configView['images'] ?>/graphics/logo-toyota.png"></a>
            </div>
		</div>
    </div>
</div>
<?php
}
?>