<?php
if (!empty($this->data['data']))
{
?>
<div class="box_category width_common" id="video">
    <div class="title_box_category width_common">
        <h2 class="txt_main_category">
            <a href="<?php echo $this->configView['url'],$this->data['info']['share_url']; ?>" title="<?php echo $this->data['info']['name']; ?>"><?php echo $this->data['info']['name']; ?></a>
        </h2>
        <a class="block_arrow_title" href="<?php echo $this->configView['url'],$this->data['info']['share_url']; ?>" title="<?php echo $this->data['info']['name']; ?>">&nbsp;</a>
    </div>
    <div class="content_box_category width_common">
        <?php
        $firstNews      = $this->objArticle->getArticleBasic($this->data['data'][0]);
        ?>
        <div class="width_common box_num02">
            <?php if(DEVICE_ENV != 1){ ?>
                <div class="thumb_relative">
                    <a href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">
                        <img src="<?php echo $this->ImageurlArticle($firstNews, 'size6'); ?>" alt="<?php echo $firstNews['title_format']; ?>" title="<?php echo $firstNews['title_format']; ?>"/>
                    </a>
                    <?php echo $this->ArticleTypeIcon($firstNews); ?>
                </div>
            <?php }else {?>
                <div class="thumb_relative" data-scale="5/3">
                    <a class="cover_image image_180" style="background-image: url('<?php echo $this->ImageurlArticle($firstNews, 'size6'); ?>')" href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">&nbsp;</a>
                    <?php echo $this->ArticleTypeIcon($firstNews); ?>
                </div>
            <?php } ?>
            <h2 class="title_news">
                <a class="txt_link" href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">
                    <?php echo $firstNews['title']; ?>
                </a>
                <span class="no_wrap">
                    <?php echo $this->ArticleViewIcon($firstNews); ?>
                    <?php echo $this->ArticleComment($firstNews); ?>
                </span>
            </h2>
            <div class="news_lead" data-mobile-href="<?php echo $firstNews['share_url']; ?>">
                <?php echo $firstNews['lead']; ?>
            </div>
        </div>
        <?php
        unset($this->data['data'][0]);
        if (!empty ($this->data['data']))
        {
        ?>
        <ul class="list_new_140 list_col">
            <?php
            $i=1;
            foreach ($this->data['data'] as $id)
            {
                $article = $this->objArticle->getArticleBasic($id);
                if (empty($article))
                    continue;
            ?>
            <li <?php echo 2==$i?'class="end"':''; ?>>
                <?php if(DEVICE_ENV != 1) { ?>
                    <div class="thumb_140 width_common">
                        <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                            <img src="<?php echo $this->ImageurlArticle($article, 'size1'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>"/>
                        </a>
                        <?php echo $this->ArticleTypeIcon($article); ?>
                    </div>
                <?php }else { ?>
                    <div class="thumb_140 width_common" data-scale="5/3">
                        <a href="<?php echo $article['share_url']; ?>" class="cover_image image_108" style="background-image: url('<?php echo $this->ImageurlArticle($article, 'size1'); ?>')" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">&nbsp;</a>
                        <?php echo $this->ArticleTypeIcon($article); ?>
                    </div>
                <?php } ?>
                <h2>
                    <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                        <?php echo $article['title']; ?>
                    </a>
                    <span class="no_wrap">
                        <?php echo $this->ArticleViewIcon($article); ?>
                        <?php echo $this->ArticleComment($article); ?>
                    </span>
                </h2>
            </li>
            <?php
                $i++;
            }
            ?>
        </ul>
        <?php
        }
        ?>
    </div>
</div>
<?php
}
?>