<div class="line_gray line_page width_common">
    <div id="col_left">
        <?php
        if(DEVICE_ENV != 1)
        {
        ?>
        <div class="block_slder_top space_box" id="top_fixture_worldcup">
            <div style="text-align: center;"><p style="padding: 25px 0;">Đang tải dữ liệu...</p></div>
        </div>
        <?php
        }
        ?>
        <div class="page_detail_player page_trandau">
            <?php
            if (!empty ($this->arrPlayer))
            {
            ?>
            <div class="box width_common space_box detail_player">
                <div class="title">Thông tin cầu thủ</div>
                <div class="block_clear_men"><a target="_blank" onclick="thethao.trackingImpression()" href="http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=20&mc=click&pli=10045207&PluID=0&ord=<?php echo time();?>" title="Clear Men"><img src="<?php echo $this->configView['images']; ?>/graphics/img_clearmen.png" /></a></div>
                <div class="body">
                    <div class="wrap_player">
                        <img src="<?php echo $this->Imageurl($this->arrPlayer['thumbnail'], 'size8');?>" title="<?php echo $this->arrPlayer['name_format']; ?>" alt="<?php echo $this->arrPlayer['name_format']; ?>" />
                        <div class="info_player">
                            <div class="name"><?php echo $this->arrPlayer['name'];?></div>
                            <table>
                                <tbody>
                                    <?php
                                    $birth = explode('-', $this->arrPlayer['birthday']);
                                    if(isset($birth[0]))
                                    {
                                        $age = intval(date('Y')-$birth[0]).' tuổi';
                                    }else{
                                        $age = 1000;
                                    }
                                    if($age >10 && $age <60 )
                                    {
                                        $dateSt = date('d/m/Y',strtotime($this->arrPlayer['birthday'])).' ('.$age.')';
                                    }
                                    if(!empty($dateSt)){
                                    ?>
                                    <tr>
                                        <td class="label">Ngày sinh</td>
                                        <td class="value"><?php echo $dateSt; ?></td>
                                    </tr>
                                    <?php
                                    }
                                    if(!empty($this->arrPlayer['place_birth']))
                                    {
                                    ?>
                                    <tr>
                                        <td class="label">Nơi sinh</td>
                                        <td class="value"><?php echo $this->arrPlayer['place_birth']; ?></td>
                                    </tr>
                                    <?php
                                     }
                                     if(!empty($this->arrPlayer['nationality_name']))
                                     {
                                     ?>
                                    <tr>
                                        <td class="label">Quốc tịch</td>
                                        <td class="value"><?php echo $this->arrPlayer['nationality_name']; ?></td>
                                    </tr>
                                    <?php
                                     }
                                     if($this->arrPlayer['height']!=0)
                                     {
                                     ?>
                                    <tr>
                                        <td class="label">Chiều cao</td>
                                        <td class="value"><?php echo $this->arrPlayer['height'].'&nbsp;Cm'; ?></td>
                                    </tr>
                                    <?php
                                     }
                                     if($this->arrPlayer['weight'] !=0)
                                     {
                                     ?>
                                    <tr>
                                        <td class="label">Cân nặng</td>
                                        <td class="value"><?php echo $this->arrPlayer['weight'].'&nbsp;Kg'; ?></td>
                                    </tr>
                                    <?php
                                     }
                                     if($this->arrPlayer['position'] !=NULL)
                                     { ?>
                                    <tr>
                                        <td class="label">Vị trí</td>
                                        <td class="value">
                                            <?php
                                            switch ($this->arrPlayer['position'])
                                            {
                                                case 'D':
                                                    $position = 'Hậu vệ';
                                                    break;
                                                case 'F':
                                                    $position = 'Tiền đạo';
                                                    break;
                                                case 'M':
                                                    $position = 'Tiền vệ';
                                                    break;
                                                case 'G':
                                                    $position = 'Thủ môn';
                                                    break;
                                                case 'C':
                                                    $position = 'Huấn luyện viên';
                                                    break;
                                                case 'SUB':
                                                    $position = 'Dự bị';
                                                    break;
                                                default :
                                                    $position = 'Vị trí khác';
                                                    break;
                                            }
                                            echo $position;
                                            ?>
                                        </td>
                                    </tr>
                                    <?php
                                    }
                                    if($this->arrPlayer['num_coat']!=0)
                                    {
                                    ?>
                                    <tr>
                                        <td class="label">Số áo</td>
                                        <td class="value"><?php  echo $this->arrPlayer['num_coat'];?></td>
                                    </tr>
                                    <?php
                                    }
                                    $id = $this->arrPlayer['nationality'];
                                    if(isset($this->arrLocation[$id])){

                                        echo '<tr><td class="label">Đội bóng quốc gia</td><td class="value">'.$this->arrLocation[$id]['name'].'</td></tr>';
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <?php
            }
            if (!empty($this->assessment['data']))
            {
            ?>
            <div class="box width_common assessment_player">
                <div class="title">Đánh giá cầu thủ</div>
                <div class="body">
                    <ul>
                        <?php
                        foreach ($this->assessment['data'] as $data)
                        {
                            $percent = $data['rating_point'] * 10;

                            switch ($data['rating_point'])
                            {
                                case $data['rating_point'] <= 5:
                                    $color = 'color2';
                                    break;
                                case $data['rating_point']<=7:
                                    $color = 'color3';
                                    break;
                                case $data['rating_point'] < 8:
                                    $color = 'color5';
                                    break;
                                case $data['rating_point'] < 9:
                                    $color = 'color1';
                                    break;
                                default :
                                    $color = 'color4';
                                    break;
                            }
                        ?>
                        <li>
                            <div class="label"><?php echo $data['rating_name']; ?></div>
                            <div class="progress_bar_style_2">
                                <span style="width:<?php echo $percent, '%'; ?>;"></span>
                            </div>
                            <?php echo $data['rating_point']; ?>
                        </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </div>
            <?php
            }
            if(!empty($this->newsPlayer))
            {
            ?>
            <div class="box width_common related_news_t">
                <div class="title">Tin liên quan</div>
                <div class="body">
                    <div class="wrap">
                        <?php
                        $idFirst = array_shift($this->newsPlayer);
                        $data = $this->objArticle->getArticleBasic($idFirst);
                        ?>
                        <div class="thumb">
                            <?php
							if(!empty($data['thumbnail_url']))
							{
							?>
                            <a href="<?php echo $this->ShareurlWorldcup($data['share_url']);?>" title="<?php echo $data['title_format'];?>">
                                <img class="big_thumb" src="<?php echo $this->Imageurl($data['thumbnail_url'], 'size6');?>" alt="<?php echo $data['title_format'];?>">
                            </a>
							<?php
							}
							?>
                            <div class="title_thumb">
                                <a href="<?php echo $this->ShareurlWorldcup($data['share_url']);?>" title="<?php echo $data['title_format'];?>">
                                    <?php echo $data['title'];?>
                                </a>
                            </div>
                        </div>
                        <?php
                        if(!empty ($this->newsPlayer))
                        {
                            $this->newsPlayer = array_slice($this->newsPlayer,0,LIMIT_RELATED_PLAYER);
                        ?>
                        <ul class="related">
                            <?php
                            $i = 0;
                            foreach ($this->newsPlayer as $id)
                            {
                                $data = $this->objArticle->getArticleBasic($id);
                                if(empty($data))
                                {
                                    continue;
                                }
                                $i++;
                            ?>
                            <li class="<?php echo $i==1?'first':''; ?>">
                                <div class="title_sub">
                                    <a href="<?php echo $this->ShareurlWorldcup($data['share_url']);?>" title="<?php echo $data['title_format'];?>"><?php echo $data['title'];?></a>
                                </div>
                                <p><?php echo $data['lead'];?></p>
                            </li>
                            <?php
                            }

                            ?>
                        </ul>
                        <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
            <?php
            }
            ?>
        </div>
    </div>
    <div id="col_right">
        <?php echo $this->GetBlock('left'); ?>
    </div>
</div>
<script language="javascript" type="text/javascript">
    /*Script thay đổi màu thanh Progress_bar_style_2*/
    var changeColorProgressBar = (function(){
      var ProgressBar = $('.progress_bar_style_2');
      $.each(ProgressBar, function() {
       var widthProgressBar = $(this).width();
       var progress = $(this).find('span');
       var widthProgress = progress.width();
       var result = widthProgress/widthProgressBar;
       if( result < 0.5 ){
          progress.css('background','#dedede');
        }else if( result > 0.8)
        {
          progress.css('background','#328005');
        }
      });
    })();
</script>