<?php
if (!empty($this->arrData))
{
?>
    <div class="block_mid_col_left">
        <ul class="list_news">
            <?php
            $arrDataAbove = array_slice($this->arrData, 0,5);
            $this->arrData = array_diff($this->arrData, $arrDataAbove);
            foreach($arrDataAbove as $id)
            {
                $article = $this->objArticle->getArticleBasic($id);
            ?>
                <li>
                    <div class="block_image_news width_common">
                        <?php
                        if (!empty($article['thumbnail_url']))
                        {
                            ?>
                        <div class="thumb">
                            <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                <img src="<?php echo $this->ImageurlArticle($article, 'size1'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                            </a>
                            <?php echo $this->ArticleTypeIcon($article); ?>
                        </div>
                        <?php
                        }
                        ?>
                        <div class="title_news">
                            <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>" class="txt_link">
                                <?php echo $article['title']; ?>
                            </a>
                            <span class="no_wrap">
                                <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                <?php echo $this->ArticleComment($article); ?>
                            </span>
                        </div>
                        <div class="news_lead"><?php echo $article['lead'];?></div>
                         <?php
                        if (sizeof($article['reference_detail']) > 0) {
                            $i = 1;
                            $arrRef = array();
                            foreach($article['reference_detail'] as $reference)
                            {
                                if($i > 2) {
                                    break;
                                }
                                $arrRef[] = '<a href="' . $this->ShareurlWorldcup($reference['share_url']) . '" title="' . $reference['title_format'] . '" alt="' . $reference['title_format'] . '">' . $reference['title'] . '</a>';
                                $i++;
                            }
                            ?>
                            <div class="list_dot">
                                <?php echo implode(' / ', $arrRef); ?>
                            </div>
                            <?php
                            unset($arrRef);
                        }
                        ?>
                    </div>
                </li>
            <?php
            }
            ?>
        </ul>
        <div class="block_banner_mid_2col width_common space_box">
            <?php
            if (DEVICE_ENV != 1)
            {
            ?>
            <div class="banner_468 banner_common">
                <div class="banner_468x90">
                    <script type="text/javascript">try{Poly_Article();}catch(e){}</script>
                </div>
            </div>
            <?php
            }
            ?>
        </div>
        <?php
        if(!empty($this->arrData))
        {
        ?>
        <ul class="list_news">
            <?php
            foreach($this->arrData as $id)
            {
                $article = $this->objArticle->getArticleBasic($id);
            ?>
                <li>
                    <div class="block_image_news width_common">
                        <?php
                        if (!empty($article['thumbnail_url']))
                        {
                            ?>
                        <div class="thumb">
                            <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                <img src="<?php echo $this->ImageurlArticle($article, 'size1'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                            </a>
                            <?php echo $this->ArticleTypeIcon($article); ?>
                        </div>
                        <?php
                        }
                        ?>
                        <div class="title_news">
                            <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>" class="txt_link">
                                <?php echo $article['title']; ?>
                            </a>
                            <span class="no_wrap">
                                <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                <?php echo $this->ArticleComment($article); ?>
                            </span>
                        </div>
                        <div class="news_lead"><?php echo $article['lead'];?></div>
                         <?php
                        if (sizeof($article['reference_detail']) > 0) {
                            $i = 1;
                            $arrRef = array();
                            foreach($article['reference_detail'] as $reference)
                            {
                                if($i > 2) {
                                    break;
                                }
                                $arrRef[] = '<a href="' . $this->ShareurlWorldcup($reference['share_url']) . '" title="' . $reference['title_format'] . '" alt="' . $reference['title_format'] . '">' . $reference['title'] . '</a>';
                                $i++;
                            }
                            ?>
                            <div class="list_dot">
                                <?php echo implode(' / ', $arrRef); ?>
                            </div>
                            <?php
                            unset($arrRef);
                        }
                        ?>
                    </div>
                </li>
            <?php
            }
            ?>
        </ul>
        <?php
        }
        ?>
        <?php
        echo $this->PaginationWorldcup($this->arrParamPaging);
        ?>
    </div>
<?php
}
?>