<div class="line_gray line_page width_common">
    <div id="col_left">
        <?php echo $this->render('block/top_lichthidau.phtml'); ?>
        <div class="page_guess width_common">
            <div class="title">Cách thức tham gia:</div>
            <p class="br">Đây là bước đầu tiên bạn cần thực hiện để được tham gia Chương trình Dự đoán trúng thưởng hằng ngày và toàn giải. Bạn khai báo thông tin ngắn gọn tại trang web http://thantai.vnexpress.net, ở mục Đăng ký. Mỗi thành viên CHỈ được sở hữu DUY NHẤT một tài khoản &amp; thông tin khai báo phải chính xác. Ban Tổ Chức không chịu trách nhiệm với những thông tin sai và chỉ trao giải cho những thành viên đã đăng ký đúng với chương trình.</p>
            <p>Cú pháp dự đoán qua SMS :</p>
            <p>Khi dự đoán đội bóng đó chiến thắng.</p>
            <p class="green br">VNE &lt;Mã trận&gt; &lt;Mã đội&gt; THANG &lt;Điểm dự đoán&gt;</p>
            <p>Khi dự đoán đội bóng đó hòa.</p>
            <p class="green br">VNE &lt;Mã trận&gt; &lt;Mã đội&gt; HOA &lt;Điểm dự đoán&gt;</p>
            <p>Dự đoán đội vô địch:</p>
            <p class="green br">VNE VD &lt;Mã đội bóng&gt; &lt;Điểm dự đoán&gt;</p>
            <div class="box_guess math width_common">
                <div class="title_box">Trận đấu</div>
                <div class="content width_common">
                    <div class="caption">LUẬT CHƠI DỰ ĐOÁN WORLD CUP 2014</div>
                    <p>Đăng ký thành viên. Đây là bước đầu tiên bạn cần thực hiện để được tham gia Chương trình Dự đoán trúng thưởng hằng ngày và toàn giải. Bạn khai báo thông tin ngắn gọn tại trang web http://thantai.vnexpress.net, ở mục Đăng ký. Mỗi thành viên CHỈ được sở hữu DUY NHẤT một tài khoản &amp; thông tin khai báo phải chính xác. Ban Tổ Chức không chịu trách nhiệm với những thông tin sai và chỉ trao giải cho những thành viên đã đăng ký đúng với chương trình.</p>
                </div>
                <div class="action width_common">
                    <a href="#" class="btn">Dự đóan</a>
                </div>
            </div>
            <div class="box_guess team width_common">
                <div class="title_box">Đội vô địch</div>
                <div class="content width_common">
                    <div class="caption">LUẬT CHƠI DỰ ĐOÁN WORLD CUP 2014</div>
                    <p>Đăng ký thành viên. Đây là bước đầu tiên bạn cần thực hiện để được tham gia Chương trình Dự đoán trúng thưởng hằng ngày và toàn giải. Bạn khai báo thông tin ngắn gọn tại trang web http://thantai.vnexpress.net, ở mục Đăng ký. Mỗi thành viên CHỈ được sở hữu DUY NHẤT một tài khoản &amp; thông tin khai báo phải chính xác. Ban Tổ Chức không chịu trách nhiệm với những thông tin sai và chỉ trao giải cho những thành viên đã đăng ký đúng với chương trình.</p>
                </div>
                <div class="action width_common">
                    <select>
                        <option value="">Chọn đội</option>
                    </select>
                    <a href="#" class="btn">Gửi</a>
                </div>
            </div>
            <div class="box_guess player width_common">
                <div class="title_box">Vua phá lưới</div>
                <div class="content width_common">
                    <div class="caption">LUẬT CHƠI DỰ ĐOÁN WORLD CUP 2014</div>
                    <p>Đăng ký thành viên. Đây là bước đầu tiên bạn cần thực hiện để được tham gia Chương trình Dự đoán trúng thưởng hằng ngày và toàn giải. Bạn khai báo thông tin ngắn gọn tại trang web http://thantai.vnexpress.net, ở mục Đăng ký. Mỗi thành viên CHỈ được sở hữu DUY NHẤT một tài khoản &amp; thông tin khai báo phải chính xác. Ban Tổ Chức không chịu trách nhiệm với những thông tin sai và chỉ trao giải cho những thành viên đã đăng ký đúng với chương trình.</p>
                </div>
                <div class="action width_common">
                    <select>
                        <option value="">Chọn đội</option>
                    </select>
                    <select>
                        <option value="">Chọn đội</option>
                    </select>
                    <a href="#" class="btn">Gửi</a>
                </div>
            </div>
        </div>
    </div>
    <div id="col_right">
        <?php echo $this->GetBlock('left'); ?>
    </div>
</div>