<div class="block_slder_top space_box">
    <a href="javascript:;" class="btn_control_tv_slider next_slider">&nbsp;</a>
    <a href="javascript:;" class="btn_control_tv_slider prev_slider">&nbsp;</a>
    <div class="content_slider">
        <div class="main_slider">
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
            <div class="item_slider">
                <div class="top_time">
                    <span class="left">20/10</span>
                    <span class="right">Bảng A</span>
                </div>
                <div class="doidau">
                    <p>
                        <span class="left">Brazil</span>
                        <span class="right">4</span>
                    </p>
                    <p>
                        <span class="left">Ecuado</span>
                        <span class="right">4</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>