<div class="image_club">
    <img alt="logo" src="<?php echo $this->Imageurl($this->teamDetail['thumbnail'], 'size10'); ?>">
</div>
<div class="block_right_title_club">
    <div class="block_title_page_club">
        <div class="left w680">
            <h1>
                <?php
                echo $this->teamDetail['name'];
                ?>
            </h1>
        </div>
        <div class="social_share left">
            <div class="item_social" data-component="true" data-component-type="like" data-component-objectid="<?php echo $this->teamDetail['id']; ?>" data-component-siteid="<?php echo SITE_ID; ?>" data-objecttype="12"></div>
            <div class="item_social hidden_320"><iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->teamDetail['share_url']; ?>&amp;send=false&amp;layout=button_count&amp;width=60&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;" allowTransparency="true"></iframe></div>
        </div>

    </div>
    <div class="title_tab">
        <ul>
            <li rel="info" class="start active"><a href="javascript:;" onclick="Team.changeTabContent(this);">Thông tin tổng hợp</a></li>
            <li rel="fixture"><a href="javascript:;" data-url="<?php echo $this->configView['url'] . '/load-list-fixture/doi-bong-' . $this->teamDetail['id'] . '.html'; ?>" onclick="Team.changeTabContent(this);"> Kết quả &amp; lịch thi đấu</a></li>
            <li rel="history" id="his"><a href="javascript:;" onclick="Team.changeTabContent(this);">Lịch sử câu lạc bộ</a></li>
        </ul>
    </div>
</div>
<div class="tab_mobile">
    <a href="javascript:;" class="tab_main_mobile">Thông tin tổng hơp</a>
    <div class="list_tab_mobile">
        <ul>
            <li rel="info" class="start active"><a href="javascript:;" data-title="Thông tin tổng hợp" onclick="Team.changeTabContent(this);">Thông tin tổng hợp</a></li>
            <li rel="fixture"><a href="javascript:;" data-title="Kết quả &amp; lịch thi đấu" data-url="<?php echo $this->configView['url'] . '/load-list-fixture/doi-bong-' . $this->teamDetail['id'] . '.html'; ?>" onclick="Team.changeTabContent(this);"> Kết quả &amp; lịch thi đấu</a></li>
            <li rel="history" id="his"><a href="javascript:;" data-title="Lịch sử câu lạc bộ" onclick="Team.changeTabContent(this);">Lịch sử câu lạc bộ</a></li>
        </ul>
    </div>
</div>