<div class="line_gray line_page width_common">
    <div id="col_left">
        <?php
        if (!empty($this->arrHotNews))
        {
            ?>
            <div class="block_hot_top width_common">
                <div class="width_common space_box" id="spotlight">
                    <?php
                    $idFirstNews = array_shift($this->arrHotNews);
                    $firstNews = $this->objArticle->getArticleBasic($idFirstNews);
                    if (!empty($firstNews))
                    {
                        $firstNews['share_url'] = $this->ShareurlSeagame($firstNews['share_url']);
                        ?>
                        <div class="block_image">
                            <a href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>" class="txt_link">
                                <img src="<?php echo $this->ImageurlArticle($firstNews, 'size2', -1); ?>" alt="<?php echo $firstNews['title_format']; ?>" title="<?php echo $firstNews['title_format']; ?>" class="width_image_common" />
                            </a>
                            <?php echo $this->ArticleTypeIcon($firstNews); ?>
                        </div>
                        <div class="block_title">
                            <div class="txt_title">
                                <a href="<?php echo $firstNews['share_url']; ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>" class="txt_link">
                                    <?php echo $firstNews['title']; ?>
                                    <span class="no_wrap">
                                        <?php echo $this->ArticleViewIcon($firstNews); ?>
                                        <?php echo $this->ArticleComment($firstNews); ?>
                                    </span>
                                </a>
                            </div>
                            <div class="block_lead">
                                <?php echo $this->CropWord($firstNews['lead'], 33, $this->ShareurlSeagame($firstNews['share_url'])); ?>
                            </div>
                            <?php
                            if (sizeof($firstNews['reference_detail']) > 0)
                            {
                                $i = 1;
                                $arrRef = '';
                                foreach ($firstNews['reference_detail'] as $reference)
                                {
                                    if ($i > 1)
                                    {
                                        break;
                                    }
                                    $arrRef = '<a href="' . $this->ShareurlSeagame($reference['share_url']) . '" title="' . $reference['title_format'] . '" alt="' . $reference['title_format'] . '">' . $reference['title'] . '</a>';
                                    $i++;
                                }
                                ?>
                                <ul class="list_news_dot_3x3_300">
                                    <li>
                                        <p>
                                            <?php echo $arrRef; ?>
                                        </p>
                                    </li>
                                </ul>
                                <?php
                                unset($arrRef);
                            }
                            ?>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <?php
                if (!empty($this->arrHotNews))
                {
                    ?>
                    <div class="list_hot_top">
                        <div class="scroll-pane">
                            <div class="content_scoller width_common">
                                <ul class="list_news">
                                    <?php
                                    foreach ($this->arrHotNews as $key => $id)
                                    {
                                        $article = $this->objArticle->getArticleBasic($id);
                                        if (empty($article))
                                        {
                                            continue;
                                        }
                                        $article['share_url'] = $this->ShareurlSeagame($article['share_url']);
                                        ?>
                                        <li <?php echo 4 == $key ? 'class="last_item"' : ''; ?>>
                                            <div class="block_image_news width_common">
                                                <?php
                                                if (!empty ($article['thumbnail_url'])) {
                                                    ?>
                                                    <div class="thumb">
                                                        <a href="<?php echo $article['share_url']; ?>" class="txt_link" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                            <img src="<?php echo $this->ImageurlArticle($article, 'size11', -1); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                                        </a>
                                                    </div>
                                                    <?php
                                                }
                                                ?>
                                                <div class="title_news">
                                                    <a href="<?php echo $article['share_url']; ?>" class="txt_link" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                        <?php echo $article['title']; ?>
                                                        <span class="no_wrap">
                                                            <?php echo $this->ArticleViewIcon($article); ?>
                                                            <?php echo $this->ArticleComment($article); ?>
                                                        </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <?php
        }
        ?>
        <div class="block_2mid_col line_mid_col width_common">
            <div id="block_folder" class="block_two_col_mid width_common block_two_col_folder">
                <?php
                $mobile = DEVICE_ENV == 1 ? '_mobile':'';
                echo $this->render('category/list_paging_category'.$mobile.'.phtml');
                ?>
                <div class="block_col_folder_right">
                    <?php
                    if (!empty($this->arrListVideo))
                    {
                        ?>
                        <div class="common_right_folder">
                            <div class="title_box_category width_common">
                                <div class="txt_main_category"><a href="<?php echo $this->configView['url'] . '/video'; ?>" title="Video">Video</a></div>
                            </div>
                            <div class="list_video_folder width_common">
                                <?php
                                foreach ($this->arrListVideo as $id)
                                {
                                    $video = $this->objArticle->getArticleBasic($id);
                                    if (empty($video)) {
                                        continue;
                                    }
                                    $video['share_url'] = $this->ShareurlSeagame($video['share_url']);
                                    ?>
                                    <div class="item_video_folder width_common">
                                        <?php
                                        if (!empty($video['thumbnail_url']))
                                        {
                                            ?>
                                            <div class="thumb_image">
                                                <a href="<?php echo $video['share_url']; ?>" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                                    <img src="<?php echo $this->ImageurlArticle($video, 'size6', -1); ?>" alt="<?php echo $video['title_format']; ?>" title="<?php echo $video['title_format']; ?>" />
                                                    <span class="play_icon"></span>
                                                </a>
                                                <?php echo $this->ArticleTypeIcon($video); ?>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                        <div class="title_video">
                                            <a href="<?php echo $video['share_url']; ?>" class="txt_link txt_14" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                                <?php echo $video['title']; ?>
                                            </a>
                                        </div>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                    <div class="common_right_folder banner_225">
                        <div class="banner_225">
                            <script language="javascript">
                                <?php if($this->isArticleHotVnE) { ?>
                                try{Poly_Sky()();}catch(e){}
                                <?php } else { ?>
                                try{Poly_SpecialRight();}catch(e){}
                                <?php } ?>
                            </script>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div id="col_right">
        <?php echo $this->GetBlockOther('left'); ?>
    </div>
</div>