<div class="line_gray line_page width_common" id="page_lichthidau">
    <div id="col_left" class="col_sche">
        <div class="block_col_sche">
        <table cellspacing="0" cellpadding="0" style="width: 100%;" class="table_sche">
        <tbody><tr>
            <td rowspan="2" class="s0 bor_top"></td>
            <td class="s1 bor_top">29</td>
            <td class="s1 bor_top">30</td>
            <td class="s1 bor_top">31</td>
            <td class="s1 bor_top">1</td>
            <td class="s1 bor_top">2</td>
            <td class="s1 bor_top">3</td>
            <td class="s1 bor_top">4</td>
            <td class="s1 bor_top">5</td>
            <td class="s1 bor_top">6</td>
            <td class="s1 bor_top">7</td>
            <td class="s1 bor_top">8</td>
            <td class="s1 bor_top">9</td>
            <td class="s1 bor_top">10</td>
            <td class="s1 bor_top">11</td>
            <td class="s1 bor_top">12</td>
            <td class="s1 bor_top">13</td>
            <td class="s1 bor_top">14</td>
            <td class="s1 bor_top">15</td>
            <td class="s1 bor_top">16</td>
        </tr>
        <tr>

            <td class="s1">T6</td>
            <td class="s1">T7</td>
            <td class="s1">CN</td>
            <td class="s1">T2</td>
            <td class="s1">T3</td>
            <td class="s1">T4</td>
            <td class="s1">T5</td>
            <td class="s1">T6</td>
            <td class="s1">T7</td>
            <td class="s1">CN</td>
            <td class="s1">T2</td>
            <td class="s1">T3</td>
            <td class="s1">T4</td>
            <td class="s1">T5</td>
            <td class="s1">T6</td>
            <td class="s1">T7</td>
            <td class="s1">CN</td>
            <td class="s1">T2</td>
            <td class="s1">T3</td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/CEREM.png">Khai mạc &amp; Bế mạc</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket">KM</td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket">BM</td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/AT.png">Điền kinh</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>

        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/FB.png">Bóng đá nam</td>


            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/RB.png">Bóng bầu dục 7 người</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/DV.png">Lặn</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SW.png">Bơi lội</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SS.png">Bơi nghệ thuật</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/WP.png">Bóng nước</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/NB.png">Bóng rổ 7 người</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/BK.png">Bóng rổ</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/FE.png">Đấu kiếm</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/VO.png">Bóng chuyền</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/BS.png">Billiards &amp; Snooker</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/TT.png">Bóng bàn</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/BD.png">Cầu lông</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/GA.png">Thể dục dụng cụ</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/CY.png">Đua xe đạp</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/TR.png">Ba môn phối hợp</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/BX.png">Quyền anh</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/ST.png">Cầu mây</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/JU.png">Judo</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/TK.png">Taekwondo</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/WU.png">Wushu</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/PS.png">Pencak Silat</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/FL.png">Floorball</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/AR.png">Bắn cung</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SB.png">Softball</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SQ.png">Bóng quần (Đơn &amp; đồng đội)</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SQ.png">Bóng quần (đôi Jumbo)</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/TE.png">Quần vợt</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/WS.png">Lướt ván nước</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/CA.png">Canoeing</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/RO.png">Đua thuyền</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/TB.png">Đua thuyền truyền thống**</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SA.png">Đua thuyền buồm</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SH.png">Bắn súng (trong nhà)</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/SH.png">Bắn súng (ngoài trời)</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/PT.png">Bi sắt</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/BW.png">Bowling</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/GO.png">Golf</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/HO.png">Khúc côn cầu</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket"></td>
            <td class="s1"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        <tr>
            <td class="s0_3 s0_f no_bold"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/icon_sg/EQ.png">Đua ngựa</td>


            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>

            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1 ticket dot"><img alt="" src="<?php echo $this->configView['images']; ?>/graphics/hc_icon.png"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
            <td class="s1"></td>
        </tr>
        </tbody></table>
        <div class="note_sche width_common">
            <p><span class="ticket">KM</span>Khai mạc<span class="ticket">BM</span>Bế mạc<span class="ticket date_td"></span>Ngày thi đấu <span class="ticket date_hc"></span>Ngày thi đấu, trao huy chương</p>
        </div>
        </div>
    </div>
    <div id="col_right">
        <?php echo $this->GetBlockOther('left'); ?>
    </div>
</div>