<?php
if (!empty($this->arrData))
{
?>
<div class="block_col_mid_common block_col_mid_folder">
    <div class="list_hot_top">
        <ul class="list_news" id="list_news">
            <?php
            $count = count($this->arrData);
            $i = 0;
            foreach($this->arrData as $id)
            {
                $article = $this->objArticle->getArticleBasic($id);

                $i++;
                if (empty($article))
                {
                    continue;
                }
                $article['share_url'] = $this->ShareurlSeagame($article['share_url']);
                ?>
                <li <?php echo $i == $count ? 'class="last_item"':''; ?>>
                    <div class="block_image_news width_common">
                        <?php
                        if (!empty($article['thumbnail_url']))
                        {
                            ?>
                            <div class="thumb">
                                <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                    <img src="<?php echo $this->ImageurlArticle($article, 'size11', -1); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                </a>
                                <?php echo $this->ArticleTypeIcon($article); ?>
                            </div>
                        <?php
                        }
                        ?>
                        <div class="title_news">
                            <a class="txt_link" href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                <?php echo $article['title']; ?>
                                <span class="no_wrap">
                                    <?php echo $this->ArticleViewIcon($article); ?>
                                    <?php echo $this->ArticleComment($article); ?>
                                </span>
                            </a>
                        </div>
                    </div>
                </li>
            <?php
            }
            ?>
        </ul>
        <div class="more_btn">
            <a href="<?php echo $this->configView['url'] . '/mobile/listcategory/category_id/' . $this->intCategoryId; ?>" data-container="#list_news" data-params="<?php echo $this->escape(Zend_Json::encode(array('limit' => LIMIT_LIST_MORE, 'offset' => LIMIT_LIST_CATE, 'total' => $this->arrParamPaging['total'], 'exclude' => implode(',', array_slice($this->arrData, -5, 5))))); ?>">Xem tiếp</a>
        </div>
    </div>
</div>
<?php
}
?>