<!DOCTYPE html>
<html>
    <head>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="VnExpress.net" />
        <!-- iPad icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/72x72.png" sizes="72x72">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="144x144">
        <!-- iPhone and iPod touch icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" sizes="57x57">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="114x114">
        <!-- Nokia Symbian -->
        <link rel="nokia-touch-icon" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png">
        <!-- Android icon precomposed so it takes precedence -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="1x1">

        <meta content="VnExpress" property="og:site_name" />
        <meta content="<?php echo $this->escape($this->ogType); ?>" property="og:type" />
        <meta content="<?php echo $this->escape($this->ogTitle); ?>" itemprop="headline" property="og:title" />
        <meta content="<?php echo $this->ogUrl; ?>" itemprop="url" property="og:url" />
        <meta content="<?php echo $this->ogImage; ?>" itemprop="thumbnailUrl" property="og:image" />
        <meta content="<?php echo $this->escape($this->ogDescription); ?>" itemprop="description" property="og:description" />
        <!--Meta Tag-->
        <?php
        echo $this->headMeta();
        $tt_category_id = isset($this->intCategoryId) ? $this->intCategoryId : SITE_ID;
        $tt_article_id = isset($this->intArticleId) ? $this->intArticleId : $tt_category_id;
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <!--Title-->
        <?php echo $this->headTitle(); ?>
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/mgeneral.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/mthethao.css" media="all" />
        <?php echo $this->headLink(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var site_id     = <?php echo SITE_ID; ?>,
            img_url   = '<?php echo $this->configView['images']; ?>',
            css_url     = '<?php echo $this->configView['css']; ?>',
            base_url    = '<?php echo $this->configView['url']; ?>',
            device_env  = <?php echo DEVICE_ENV; ?>,
            article_id  = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>,
            vne_url     = '<?php echo $this->configView['url_vne']; ?>',
            interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = 0;
            document.domain = '<?php echo DOMAIN_VNE ?>';
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-18']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-249346-37']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();
        </script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutils.js"></script>
    </head>
    <body>
        <div id="page">
            <div id="wrapper_container">
                <div id="container">
                    <div class="width_common">
                        <div class="width_common" id="warpper_trandau">
                            <?php
                            echo $this->render('/object/common/header_trandau.phtml');
                            ?>
                            <div class="width_common line_mid_980_300">
                                <div id="col_660" class="left">
                                    <div class="content_tab_trandau width_common">
                                        <?php
                                        if ($this->tuongThuat['relate_id'] > 0)
                                        {
                                            ?>
                                            <div id="box_details_news" class="width_common" data-liveblog-active="<?php echo ((($this->tuongThuat['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                                                <div class="w670 left">
                                                    <div class="main_content_detail width_common">
                                                        <div class="title_news">
                                                            <h1><?php echo $this->tuongThuat['title']; ?></h1>
                                                        </div>
                                                        <div class="short_intro txt_666"><?php echo $this->tuongThuat['lead']; ?></div>
                                                        <?php
                                                        if ($this->tuongThuat['article_type'] == 5)
                                                        {
                                                            ?>
                                                            <div class="block_filter_live">
                                                                <div class="filter_left">
                                                                    <div class="block_check_noibat"><input type="checkbox" id="checkNew"><label for="checkNew">Nổi bật</label></div>
                                                                </div>
                                                                <div class="filter_right">
                                                                    <a href="javascript:;" class="sort-live latest">Mới nhất</a>
                                                                    <a href="javascript:;" class="sort-live oldest">Cũ nhất</a>
                                                                </div>
                                                            </div>
                                                            <div class="live_post_status" id="live_post_status" style="display: none">
                                                                <a href="javascript:;" class="short_live">Có <span id="live-updates-counter"></span> tin mới được cập nhật</a>
                                                            </div>
                                                            <div id="container_tab_live" class="width_common" data-update-uri="<?php echo $this->configView['url_vne'] . '/detail/block?id=', $this->tuongThuat['article_id']; ?>" data-article-id="<?php echo $this->tuongThuat['article_id']; ?>">
                                                                <ul id="list_live">
                                                                    <li id="live-updates-wrapper" class="no_space"></li>
                                                                    <?php
                                                                    if (!empty($this->arrBlockDataId))
                                                                    {
                                                                        foreach ($this->arrBlockDataId as $blockId)
                                                                        {
                                                                            $blockDetail = $this->objLive->getBlockDetail($blockId);

                                                                            if (empty($blockDetail))
                                                                            {
                                                                                continue;
                                                                            }
                                                                            $share_url = $this->configView['url_vne'] . '/detail/share-block?id=' . $this->tuongThuat['article_id'] . '&blockid=' . $blockId;

                                                                            $count = count($blockDetail['article_reference_id']);

                                                                            //class High light
                                                                            $classHighLight = $blockDetail['highlight'] ? ' high-light' : '';
                                                                            ?>
                                                                            <li id="block-<?php echo $blockDetail['published_time']; ?>" data-block-id="<?php echo $blockId; ?>" class="block<?php echo $classHighLight; ?>">
                                                                                <div class="minutes">
                                                                                    <?php
                                                                                    $time = trim($blockDetail['display_time']);
                                                                                    if ((!empty($time)) && (strpos($time, '#') === false))
                                                                                    {
                                                                                        ?>
                                                                                        <span class="text_minutes <?php echo ($blockDetail['highlight'] ? 'special_time' : ''); ?>" datetime="<?php echo $blockDetail['published_time']; ?>">
                                                                                            <?php echo $time; ?>
                                                                                        </span>
                                                                                        <?php
                                                                                    }
                                                                                    ?>
                                                                                    <img src="<?php echo $this->configView['images'], '/graphics/img_blank.gif'; ?>" alt="icon" class="icon_live <?php echo empty($blockDetail['icon']) ? 'icon_dot_live' : $blockDetail['icon']; ?>">
                                                                                </div>
                                                                                <div class="text_live">
                                                                                    <?php
                                                                                    echo $blockDetail['block_content'];
                                                                                    if (!empty($blockDetail['article_reference_id']))
                                                                                    {
                                                                                        $this->objArticle->setIdBasic($blockDetail['article_reference_id']);

                                                                                        if ($count == 1)
                                                                                        {
                                                                                            $article = $this->objArticle->getArticleBasic($blockDetail['article_reference_id'][0]);
                                                                                            ?>
                                                                                            <div class="block_image_news width_common">
                                                                                                <?php
                                                                                                if (!empty($article['thumbnail_url']))
                                                                                                {
                                                                                                    ?>
                                                                                                    <div class="thumb">
                                                                                                        <a href="<?php echo $article['share_url']; ?>">
                                                                                                            <img src="<?php echo $this->ImageurlArticle($article, 'size6'); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                                                                        </a>
                                                                                                        <?php echo $this->ArticleTypeIcon($article); ?>
                                                                                                    </div>
                                                                                                    <?php
                                                                                                }
                                                                                                ?>
                                                                                                <h2 class="title_news">
                                                                                                    <a href="<?php echo $article['share_url']; ?>" class="txt_link">
                                                                                                        <?php echo $article['title'] ?>
                                                                                                        <span class="no_wrap">
                                                                                                            <?php echo $this->ArticleViewIcon($article); ?>
                                                                                                        </span>
                                                                                                    </a>

                                                                                                </h2>
                                                                                                <div class="news_lead" data-mobile-href="<?php echo $article['share_url']; ?>">
                                                                                                    <?php echo $article['lead']; ?>
                                                                                                </div>
                                                                                            </div>
                                                                                            <?php
                                                                                        }
                                                                                        else
                                                                                        {
                                                                                            ?>
                                                                                            <div class="list_dot_3x3">
                                                                                                <?php
                                                                                                foreach ($blockDetail['article_reference_id'] as $id)
                                                                                                {
                                                                                                    $article = $this->objArticle->getArticleBasic($id);
                                                                                                    if (empty($article))
                                                                                                    {
                                                                                                        continue;
                                                                                                    }
                                                                                                    ?>
                                                                                                    <div class="dot_item">
                                                                                                        <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>">
                                                                                                            <?php echo $article['title']; ?>
                                                                                                        </a>
                                                                                                    </div>
                                                                                                    <?php
                                                                                                }
                                                                                                ?>
                                                                                            </div>
                                                                                            <?php
                                                                                        }
                                                                                    }
                                                                                    if (DEVICE_ENV == 4)
                                                                                    {
                                                                                        ?>
                                                                                        <div class="social_share right">
                                                                                            <div class="content_inner">
                                                                                                <div class="item_social hidden_320">
                                                                                                    <a title="Chia sẻ bài viết lên facebook" class="left" target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo urlencode($share_url); ?>">
                                                                                                        <img alt="Chia sẻ bài viết lên facebook" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_fb.gif">
                                                                                                    </a>
                                                                                                </div>
                                                                                                <div class="item_social hidden_320">
                                                                                                    <a title="Chia sẻ bài viết lên twitter" class="left" target="_blank" href="http://twitter.com/share?url=<?php echo urlencode($share_url); ?>&text=<?php echo $this->tuongThuat['title']; ?>">
                                                                                                        <img alt="Chia sẻ bài viết lên twitter" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_tw.gif">
                                                                                                    </a>
                                                                                                </div>
                                                                                                <div class="item_social hidden_320">
                                                                                                    <a title="Chia sẻ bài viết lên google+" class="left" target="_blank" href="https://plus.google.com/share?url=<?php echo urlencode($share_url); ?>">
                                                                                                        <img alt="Chia sẻ bài viết lên google+" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_google.gif">
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                        <?php
                                                                                    }
                                                                                    ?>
                                                                                </div>
                                                                                <div class="clear"></div>
                                                                            </li>
                                                                            <?php
                                                                        }
                                                                    }
                                                                    ?>
                                                                </ul>
                                                                <?php
                                                                if (!empty($this->tuongThuat['content']))
                                                                {
                                                                    ?>
                                                                    <div class="width_common info_befo">
                                                                        <div class="minutes"><img src="<?php echo $this->configView['images']; ?>/icons/before_match.png" alt="Thông tin trước trận" title="Thông tin trước trận"/></div>
                                                                        <div class="text_live">
                                                                            <div class="width_common fck_detail">
                                                                                <?php echo $this->tuongThuat['content']; ?>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <script type="text/javascript">
                                                                        if (typeof(common.resizeImageDetail) != 'undefined') {
                                                                            common.resizeImageDetail();
                                                                            $(window).resize(function() {
                                                                                common.delayFireOnce(1000).done(function() {
                                                                                    common.resizeImageDetail();
                                                                                });
                                                                            });
                                                                        }
                                                                    </script>
                                                                    <?php
                                                                }
                                                                ?>
                                                            </div>
                                                            <?php
                                                        }
                                                        else
                                                        {
                                                            ?>
                                                            <div class="width_common fck_detail">
                                                                <?php
                                                                echo $this->tuongThuat['content'];
                                                                ?>
                                                            </div>
                                                            <?php
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/require.min.js"></script>
                                            <script type="text/javascript">
                                                (function() {
                                                    var req = require.config({
                                                        context: 'body-content',
                                                        baseUrl: '<?php echo $this->configView['vnecdn']['js'], '/live'; ?>'
                                                    });
                                                    req(['livenews']);
                                                })();
                                                if(typeof(Parser) != "undefined"){
                                                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                                                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                                                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                                                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                                                    Parser.AUTO_PLAY = 1;
                                                    Parser.parseAll();
                                                }
                                            </script>
                                            <?php
                                        }
                                        else
                                        {
                                            ?>
                                            <div class="txt_666" style="padding-bottom: 10px;">Không có thông tin tường thuật trận đấu.<br/></div>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="block_close_menu">&nbsp;</div>
        </div>
        <div class="clear"></div>
        <script type="text/javascript">
            $(function(){
                if(typeof(Parser) != "undefined"){
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
        </script>
    </body>
</html>