<?php $shareTitle =  strip_tags($this->headTitle());?>
<div class="list_share_icon right">
    <ul class="left">
        <li class="face_green">
            <div class="fb-like" data-href="<?php echo $this->shareUrl; ?>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>
        </li>
        <!--<li>
            <iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/tweet_button.html?url=<?php echo $this->shareUrl;;?>&via=<?php echo $shareTitle; ?>&text=<?php echo $shareTitle; ?>" style="width:80px; height:21px;"></iframe>
        </li>
        <li class="icon_goo"><g:plusone size="medium" annonation="none"></g:plusone></li>-->
    </ul>
    <div class="clear">&nbsp;</div>
</div>