<div class="width_common" id="warpper_trandau">
    <?php
    echo $this->render('/object/common/header_trandau.phtml');
    ?>
    <div class="width_common line_mid_980_300">
        <div id="col_660" class="left">
            <div class="tab_trandau width_common">
                <?php
                if (DEVICE_ENV == 1)
                {
                    ?>
                    <div class="tab_mobile">
                        <a href="javascript:;" title="Tường thuật" class="tab_main_mobile">Tường thuật</a>
                        <div class="list_tab_mobile">
                            <ul>
                                <li>
                                    <a title="Ảnh - Video" href="<?php echo "/anh-video/{$this->seoTitle}-{$this->matchDetail['id']}" ?>">Ảnh - Video</a>
                                </li>
                                <li>
                                    <a title="Điểm tin" href="<?php echo "/diem-tin/{$this->seoTitle}-{$this->matchDetail['id']}" ?>">Điểm tin</a>
                                </li>
                                <li>
                                    <a title="Thống kê" href="<?php echo "/thong-ke/{$this->seoTitle}-{$this->matchDetail['id']}" ?>"> Thống kê</a>
                                </li>
                                <li>
                                    <a href="javascript:;" title="Tường thuật">Tường thuật</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <?php
                }
                else
                {
                    ?>
                    <div class="title_tab width_common">
                        <ul>
                            <li class="start">
                                <a title="Ảnh - Video" href="<?php echo "/anh-video/{$this->seoTitle}-{$this->matchDetail['id']}" ?>">Ảnh - Video</a>
                            </li>
                            <li>
                                <a title="Điểm tin" href="<?php echo "/diem-tin/{$this->seoTitle}-{$this->matchDetail['id']}" ?>">Điểm tin</a>
                            </li>
                            <li>
                                <a title="Thống kê" href="<?php echo "/thong-ke/{$this->seoTitle}-{$this->matchDetail['id']}" ?>">Thống kê</a>
                            </li>
                            <li class="active">
                                <a href="javascript:;" title="Tường thuật">Tường thuật</a>
                            </li>
                        </ul>
                    </div>
                    <?php
                }
                ?>
           	</div>
            <div class="content_tab_trandau width_common">
                <?php
                if ($this->tuongThuat['relate_id'] > 0)
                {
                    ?>
                    <div id="box_details_news" class="width_common" data-liveblog-active="<?php echo ((($this->tuongThuat['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                        <div class="w670 left">
                            <div class="main_content_detail width_common">
                                <div class="title_news">
                                    <h1><?php echo $this->tuongThuat['title']; ?></h1>
                                </div>
                                <div class="short_intro txt_666"><?php echo $this->tuongThuat['lead']; ?></div>
                                <?php
                                if ($this->tuongThuat['article_type'] == 5)
                                {
                                ?>
                                    <div class="block_filter_live">
                                        <div class="filter_left">
                                            <div class="block_check_noibat"><input type="checkbox" id="checkNew"><label for="checkNew">Nổi bật</label></div>
                                        </div>
                                        <div class="filter_right">
                                            <a href="javascript:;" class="sort-live latest">Mới nhất</a>
                                            <a href="javascript:;" class="sort-live oldest">Cũ nhất</a>
                                        </div>
                                    </div>
                                    <div class="live_post_status" id="live_post_status" style="display: none">
                                        <a href="javascript:;" class="short_live">Có <span id="live-updates-counter"></span> tin mới được cập nhật</a>
                                    </div>
                                    <div id="container_tab_live" class="width_common" data-update-uri="<?php echo $this->configView['url_vne'] . '/detail/block?id=', $this->tuongThuat['article_id']; ?>" data-article-id="<?php echo $this->tuongThuat['article_id']; ?>">
                                        <ul id="list_live">
                                            <li id="live-updates-wrapper" class="no_space"></li>
                                            <?php
                                            if (!empty($this->arrBlockDataId))
                                            {
                                                foreach ($this->arrBlockDataId as $blockId)
                                                {
                                                    $blockDetail = $this->objLive->getBlockDetail($blockId);

                                                    if(empty($blockDetail))
                                                    {
                                                        continue;
                                                    }
                                                    $share_url = $this->configView['url_vne'] . '/detail/share-block?id='.$this->tuongThuat['article_id'].'&blockid='.$blockId;

                                                    $count = count($blockDetail['article_reference_id']);

                                                    //class High light
                                                    $classHighLight = $blockDetail['highlight'] ? ' high-light' : '';
                                                    ?>
                                                    <li id="block-<?php echo $blockDetail['published_time']; ?>" data-block-id="<?php echo $blockId; ?>" class="block<?php echo $classHighLight; ?>">
                                                        <div class="minutes">
                                                            <?php
                                                            $time = trim($blockDetail['display_time']);
                                                            if ((!empty($time)) && (strpos($time, '#') === false))
                                                            {
                                                            ?>
                                                            <span class="text_minutes <?php echo ($blockDetail['highlight'] ? 'special_time' : ''); ?>" datetime="<?php echo $blockDetail['published_time']; ?>">
                                                                <?php echo $time; ?>
                                                            </span>
                                                            <?php
                                                            }
                                                            ?>
                                                            <img src="<?php echo $this->configView['images'],'/graphics/img_blank.gif'; ?>" alt="icon" class="icon_live <?php echo empty($blockDetail['icon']) ? 'icon_dot_live' : $blockDetail['icon']; ?>">
                                                        </div>
                                                        <div class="text_live">
                                                            <?php
                                                            echo $blockDetail['block_content'];
                                                            if (!empty($blockDetail['article_reference_id']))
                                                            {
                                                                $this->objArticle->setIdBasic($blockDetail['article_reference_id']);

                                                                if ($count == 1)
                                                                {
                                                                    $article = $this->objArticle->getArticleBasic($blockDetail['article_reference_id'][0]);
                                                                    ?>
                                                                    <div class="block_image_news width_common">
                                                                        <?php
                                                                        if(!empty($article['thumbnail_url'])) {
                                                                            ?>
                                                                            <div class="thumb">
                                                                                <a href="<?php echo $article['share_url']; ?>">
                                                                                    <img src="<?php echo $this->ImageurlArticle($article, 'size6'); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                                                </a>
                                                                                <?php echo $this->ArticleTypeIcon($article); ?>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                        ?>
                                                                        <h2 class="title_news">
                                                                            <a href="<?php echo $article['share_url']; ?>" class="txt_link">
                                                                                <?php echo $article['title'] ?>
                                                                                <span class="no_wrap">
                                                                                    <?php echo $this->ArticleViewIcon($article); ?>
                                                                                </span>
                                                                            </a>

                                                                        </h2>
                                                                        <div class="news_lead" data-mobile-href="<?php echo $article['share_url']; ?>">
                                                                            <?php echo $article['lead']; ?>
                                                                        </div>
                                                                    </div>
                                                                    <?php
                                                                }
                                                                else {
                                                                    ?>
                                                                    <div class="list_dot_3x3">
                                                                        <?php
                                                                        foreach($blockDetail['article_reference_id'] as $id)
                                                                        {
                                                                            $article = $this->objArticle->getArticleBasic($id);
                                                                            if(empty($article))
                                                                            {
                                                                                continue;
                                                                            }
                                                                            ?>
                                                                            <div class="dot_item">
                                                                                <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>">
                                                                                    <?php echo $article['title']; ?>
                                                                                </a>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                        ?>
                                                                    </div>
                                                                    <?php
                                                                }
                                                            }
                                                            if (DEVICE_ENV == 4)
                                                            {
                                                                ?>
                                                                <div class="social_share right">
                                                                    <div class="content_inner">
                                                                        <div class="item_social hidden_320">
                                                                            <a title="Chia sẻ bài viết lên facebook" class="left" target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo urlencode($share_url); ?>">
                                                                                <img alt="Chia sẻ bài viết lên facebook" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_fb.gif">
                                                                            </a>
                                                                        </div>
                                                                        <div class="item_social hidden_320">
                                                                            <a title="Chia sẻ bài viết lên twitter" class="left" target="_blank" href="http://twitter.com/share?url=<?php echo urlencode($share_url); ?>&text=<?php echo $this->tuongThuat['title']; ?>">
                                                                                <img alt="Chia sẻ bài viết lên twitter" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_tw.gif">
                                                                            </a>
                                                                        </div>
                                                                        <div class="item_social hidden_320">
                                                                            <a title="Chia sẻ bài viết lên google+" class="left" target="_blank" href="https://plus.google.com/share?url=<?php echo urlencode($share_url); ?>">
                                                                                <img alt="Chia sẻ bài viết lên google+" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/icon_google.gif">
                                                                            </a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <?php
                                                            }
                                                            ?>
                                                        </div>
                                                        <div class="clear"></div>
                                                    </li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        <?php
                                        if (!empty ($this->tuongThuat['content']))
                                        {
                                        ?>
                                        <div class="width_common info_befo">
                                            <div class="minutes"><img src="<?php echo $this->configView['images']; ?>/icons/before_match.png" alt="Thông tin trước trận" title="Thông tin trước trận"/></div>
                                            <div class="text_live">
                                                <div class="width_common fck_detail">
                                                    <?php echo $this->tuongThuat['content'];?>
                                                </div>
                                            </div>
                                        </div>
                                        <script type="text/javascript">
                                            if (typeof(common.resizeImageDetail) != 'undefined') {
                                                common.resizeImageDetail();
                                                $(window).resize(function() {
                                                    common.delayFireOnce(1000).done(function() {
                                                        common.resizeImageDetail();
                                                    });
                                                });
                                            }
                                        </script>
                                        <?php
                                        }
                                        ?>
                                    </div>
                                <?php
                                }
                                else {
                                    ?>
                                <div class="width_common fck_detail">
                                    <?php
                                    echo $this->tuongThuat['content'];
                                    ?>
                                </div>
                                <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/require.min.js"></script>
                    <script type="text/javascript">
                        (function() {
                            var req = require.config({
                                context: 'body-content',
                                baseUrl: '<?php echo $this->configView['vnecdn']['js'],'/live'; ?>'
                            });
                            req(['livenews']);
                        })();
                        if(typeof(Parser) != "undefined"){
                            Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                            Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                            Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                            Parser.SITE_ID = <?php echo SITE_ID; ?>;
                            Parser.AUTO_PLAY = 1;
                            Parser.parseAll();
                        }
                    </script>
                    <?php
                }
                else
                {
                    ?>
                    <div class="txt_666" style="padding-bottom: 10px;">Không có thông tin tường thuật trận đấu.<br/></div>
                    <?php
                }
                ?>
            </div>
        </div>
        <div id="col_300" class="right">
            <?php
            //Comment
            echo  DEVICE_ENV != 4 ? $this->render('/block/comment_match.phtml') : $this->render('/block/comment_match_live.phtml');
            //block left
            echo $this->GetBlock('left');
            ?>

        </div>
    </div>
</div>
<!--<div class="banner_980x60"><?php echo $this->GetBlock('footer'); ?></div>-->