<!DOCTYPE html>
<html>
    <head>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="Vnexpress.net" />

        <!-- iPad icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/72x72.png" sizes="72x72" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="144x144" />
        <!-- iPhone and iPod touch icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" sizes="57x57" />
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="114x114" />
        <!-- Nokia Symbian -->
        <link rel="nokia-touch-icon" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" />
        <!-- Android icon precomposed so it takes precedence -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="1x1" />
        <!-- InstanceBeginEditable name="doctitle" -->
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta content="VnExpress" property="og:site_name" />
        <meta content="<?php echo $this->escape($this->ogType); ?>" property="og:type" />
        <meta content="<?php echo $this->escape($this->ogTitle); ?>" itemprop="headline" property="og:title" />
        <meta content="<?php echo $this->ogUrl; ?>" itemprop="url" property="og:url" />
        <meta content="<?php echo $this->ogImage; ?>" itemprop="thumbnailUrl" property="og:image" />
        <meta content="<?php echo $this->escape($this->ogDescription); ?>" itemprop="description" property="og:description" />
        <?php
        $isDetailArticle = isset($this->articleTrackingId) && is_numeric($this->articleTrackingId) && $this->articleTrackingId > 0;
        $isCategoryPolyAds = isset($this->intCateIdPolyAds) && is_numeric($this->intCateIdPolyAds) && $this->intCateIdPolyAds > 0;
        //Proccess category id
        $tt_category_id = $isCategoryPolyAds ? $this->intCateIdPolyAds : WORLD_CUP;
        $tt_article_id = $isDetailArticle ? $this->articleTrackingId : $tt_category_id;
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <meta name="tt_site_id" content="<?php echo SITE_ID; ?>" />
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/general.css" media="all" />
        <?php echo $this->headLink(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var site_id = <?php echo SITE_ID; ?>;
            var img_url = '<?php echo $this->configView['images']; ?>';
            var css_url = '<?php echo $this->configView['css']; ?>';
            var base_url = '<?php echo $this->configView['url']; ?>';
            var device_env = <?php echo DEVICE_ENV; ?>;
            var article_id = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>;
            var vne_url = '<?php echo $this->configView['url_vne']; ?>';
            var interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = <?php echo ACTIVE_CAPCHA; ?>;
            document.domain = '<?php echo DOMAIN_VNE ?>';
            var application_env = '<?php echo APPLICATION_ENV; ?>';
        </script>
        <!-- JS -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/libs/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutils.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/require.min.js"></script>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
            /*GA - Tracking pageview*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_setDomainName', 'vnexpress.net']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['a._setAccount', 'UA-249346-22']);
            _gaq.push(['a._trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-37']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-29374284-26']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();
        </script>
    </head>
    <body>
        <div>
            <div id="wrapper_page">
                <div id="wrapper_container">
                    <div id="container">
                        <?php
                        $arrData = $this->arrArticleDetail;
                        $timeUpdate = (isset($this->timeUpdate) && !empty($this->timeUpdate)) ? $this->timeUpdate : time();
                        $liveBlog = ((($arrData['privacy'] & 8) == 8) ? 'true' : 'false');
                        $timeServer = time();
                        ?>
                        <div class="line_gray line_page width_common">
                            <div id="col_left">
                                <div class="box_width_common" id="box_details_news" data-liveblog-active="<?php echo ((($arrData['privacy'] & 8) == 8) ? 'true' : 'false'); ?>">
                                    <div class="w670 left">
                                        <div class="main_content_detail width_common">
                                            <div class="block_timer_share">
                                                <div class="block_timer left txt_666" id="timer_update">
                                                    <?php
                                                    echo '<b>Cập nhật:</b> ', $this->DateTimeFormat($timeUpdate, 'long');
                                                    ?>
                                                </div>
                                            </div>
                                            <div class="div-fbook width_common title_div_fbook">
                                                <div class="block_timer left txt_666"><?php echo $this->DateTimeFormat($arrData['publish_time'], 'long'); ?></div>
                                            </div>
                                            <div class="title_news">
                                                <h1><?php echo $arrData['title_format']; ?></h1>
                                            </div>
                                            <div class="short_intro txt_666"><?php echo $arrData['lead']; ?></div>
                                            <div class="block_filter_live">
                                                <div class="filter_left">
                                                    <div class="block_check_noibat"><input type="checkbox" id="checkNew"><label for="checkNew">Nổi bật</label></div>
                                                </div>
                                                <div class="filter_right">
                                                    <a href="javascript:;" class="sort-live latest">Mới nhất</a>
                                                    <a href="javascript:;" class="sort-live oldest">Cũ nhất</a>
                                                </div>
                                            </div>
                                            <div class="live_post_status" id="live_post_status" style="display: none">
                                                <a href="javascript:;" class="short_live">Có <span id="live-updates-counter"></span> tin mới được cập nhật</a>
                                            </div>
                                            <div id="container_tab_live" class="width_common" data-update-uri="<?php echo $this->configView['url_vne'] . '/detail/block?id=', $arrData['article_id']; ?>" data-article-id="<?php echo $arrData['article_id']; ?>">
                                                <ul id="list_live" data-relative-time="<?php echo date('c', $arrData['publish_time']); ?>" data-server-time="<?php echo date('c', $timeServer); ?>">
                                                    <li id="live-updates-wrapper" class="no_space"></li>
                                                    <?php
                                                    if (!empty($this->arrBlockDataId))
                                                    {
                                                        $relativeTime = $arrData['publish_time'];
                                                        $intDay = -1;
                                                        foreach ($this->arrBlockDataId as $blockId)
                                                        {
                                                            $blockDetail = $this->objLive->getBlockDetail($blockId);

                                                            if (empty($blockDetail))
                                                            {
                                                                continue;
                                                            }
                                                            $count = count($blockDetail['article_reference_id']);
                                                            $classHighLight = $blockDetail['highlight'] ? ' high-light' : '';
                                                            if ($liveBlog =='true')
                                                            {
                                                                $intDayBlock = (int)((abs(strtotime(date('d/m/Y',$blockDetail['published_time'])) - strtotime(date('d/m/Y',$relativeTime))))/(60*60*24));
                                                                $intDayCurrent = (int)((abs(strtotime(date('d/m/Y',$blockDetail['published_time'])) - strtotime(date('d/m/Y', $timeServer)))) / (60*60*24));
                                                                if ($intDay != $intDayBlock && $intDayCurrent)
                                                                {
                                                                    $strDate = date('j/n', $blockDetail['published_time']);

                                                                    if (date('Y', $timeServer) != date('Y', $blockDetail['published_time']))
                                                                    {
                                                                        $strDate = $strDate . "/" . date('Y', $blockDetail['published_time']);
                                                                    }
                                                                    echo '<li id="block-',$blockDetail['published_time'],'" class="block day"><div class="day_time">Ngày ', $strDate,'</div></li>';
                                                                    $intDay = $intDayBlock;
                                                                }
                                                            }
                                                            ?>
                                                            <li id="block-<?php echo $blockDetail['published_time']; ?>" data-datetime="<?php echo date('c',$blockDetail['published_time']); ?>" data-block-id="<?php echo $blockId; ?>" class="block<?php echo $classHighLight; ?>">
                                                                <div class="minutes">
                                                                    <?php
                                                                    $time = trim($blockDetail['display_time']);
                                                                    if ((!empty($time)) && (strpos($time, '#') === false))
                                                                    {
                                                                        ?>
                                                                        <span class="text_minutes <?php echo ($blockDetail['highlight'] ? 'special_time' : ''); ?>" datetime="<?php echo $blockDetail['published_time']; ?>">
                                                                            <?php echo $time; ?>
                                                                        </span>
                                                                    <?php } ?>
                                                                    <img src="<?php echo $this->configView['images'], '/graphics/img_blank.gif'; ?>" alt="icon" class="icon_live <?php echo empty($blockDetail['icon']) ? 'icon_dot_live' : $blockDetail['icon']; ?>">
                                                                </div>
                                                                <div class="text_live">
                                                                    <?php
                                                                    echo $blockDetail['block_content'];
                                                                    if (!empty($blockDetail['article_reference_id']))
                                                                    {
                                                                        $this->objArticle->setIdBasic($blockDetail['article_reference_id']);

                                                                        if ($count == 1)
                                                                        {
                                                                            $article = $this->objArticle->getArticleBasic($blockDetail['article_reference_id'][0]);
                                                                            ?>
                                                                            <div class="block_image_news width_common">
                                                                                <?php
                                                                                if (!empty($article['thumbnail_url']))
                                                                                {
                                                                                    ?>
                                                                                    <div class="thumb">
                                                                                        <a href="<?php echo $article['share_url']; ?>">
                                                                                            <img src="<?php echo $this->ImageurlArticle($article, 'size6'); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                                                        </a>
                                                                                        <?php echo $this->ArticleTypeIcon($article); ?>
                                                                                    </div>
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                                <div class="title_news">
                                                                                    <a href="<?php echo $article['share_url']; ?>" class="txt_link">
                                                                                        <?php echo $article['title'] ?>
                                                                                        <span class="no_wrap">
                                                                                            <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                                                                        </span>
                                                                                    </a>

                                                                                </div>
                                                                                <div class="news_lead" data-mobile-href="<?php echo $article['share_url']; ?>">
                                                                                    <?php echo $article['lead']; ?>
                                                                                </div>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                        else
                                                                        {
                                                                            ?>
                                                                            <div class="list_dot_3x3">
                                                                                <?php
                                                                                foreach ($blockDetail['article_reference_id'] as $id)
                                                                                {
                                                                                    $article = $this->objArticle->getArticleBasic($id);
                                                                                    if (empty($article))
                                                                                    {
                                                                                        continue;
                                                                                    }
                                                                                    ?>
                                                                                    <div class="dot_item">
                                                                                        <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>">
                                                                                            <?php echo $article['title']; ?>
                                                                                        </a>
                                                                                    </div>
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                            </div>
                                                                            <?php
                                                                        }
                                                                    }
                                                                    ?>
                                                                </div>
                                                                <div class="clear"></div>
                                                            </li>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </ul>
                                                <?php
                                                if (!empty($this->tuongThuat['content']))
                                                {
                                                    ?>
                                                    <div class="width_common info_befo">
                                                        <div class="minutes"><img src="<?php echo $this->configView['images']; ?>/icons/before_match.png" alt="Thông tin trước trận" title="Thông tin trước trận"/></div>
                                                        <div class="text_live">
                                                            <div class="width_common fck_detail">
                                                                <?php echo $arrData['content']; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <script type="text/javascript">
                                                        if (typeof(common.resizeImageDetail) != 'undefined') {
                                                            common.resizeImageDetail();
                                                            $(window).resize(function() {
                                                                common.delayFireOnce(1000).done(function() {
                                                                    common.resizeImageDetail();
                                                                });
                                                            });
                                                        }
                                                    </script>
                                                    <?php
                                                }
                                                ?>
                                            </div>
                                            <script type="text/javascript">
                                                (function() {
                                                    var req = require.config({
                                                        context: 'main_content_detail',
                                                        baseUrl: '<?php echo $this->configView['vnecdn']['js'], '/live'; ?>'
                                                    });
                                                    req(['livenews']);
                                                })();
                                            </script>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="block_close_menu">&nbsp; </div>
        </div>

        <div id="slideshow_popup" style="background: #000000; display: none;"></div>
        <div class="clear"></div>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['js']; ?>/mwordcup.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/predict.js"></script>
        <div id="trackingLandingPage"></div>
        <script type="text/javascript">
            var timeTemp = '<?php echo time(); ?>';
            //document ready
            $(function() {
                //Show parser
                if (typeof (Parser) != "undefined") {
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
        </script>

    </body>
</html>