<?php
//1 - mobile , 0 - web, tablet
$device = DEVICE_ENV & 1;
$objMatch   = $this->objObject->getMatch();
$objTeam    = $this->objObject->getTeam();
$team1 = $team2 = array();
$arrTeam = array();
if(!empty($this->arrAllMatch))
{
    foreach ($this->arrAllMatch as $key => $team)
    {
        //get detail player
        $teamDetail = $objTeam->getDetailObjectBasic($team['TeamID']);
        $arrTeam[$teamDetail['id']] =  $teamDetail['name'];
    }
    //sort alpha
    asort($arrTeam);
}
?>
<div class="line_gray line_page width_common">
    <div id="col_left">
        <?php
        if(DEVICE_ENV != 1)
        {
        ?>
        <div class="block_slder_top space_box" id="top_fixture_worldcup">
            <div style="text-align: center;"><p style="padding: 25px 0;">Đang tải dữ liệu...</p></div>
        </div>
        <?php
        }
        ?>
        <div id="box_details_news" class="box_width_common">
            <div class="block_col_480">
                <div class="block_timer_share">
                    <div class="block_timer left txt_666"><?php echo $this->DateTimeFormat($this->arrArticleDetail['publish_time'], 'long'); ?></div>
                    <?php
                    if (DEVICE_ENV == 4) {
                    ?>
                    <div class="block_clear_men"><a target="_blank" onclick="thethao.trackingImpression()" href="http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=20&mc=click&pli=10045207&PluID=0&ord=<?php echo time();?>" title="Clear Men"><img src="<?php echo $this->configView['images']; ?>/graphics/img_clearmen.png" /></a></div>
                    <?php
                    }
                    if (DEVICE_ENV != 1)
                    {
                    ?>
                    <div class="block_share right">
                        <?php echo $this->render('detail/box/box_share_photo.phtml'); ?>
                    </div>
                    <?php
                    }
                    ?>
                </div>

                <div class="title_news">
                    <h1><?php echo $this->arrArticleDetail['title']; ?></h1>
                </div>
                <div class="short_intro txt_666"><?php echo $this->arrArticleDetail['lead']; ?></div>
                <?php
                if (!empty($this->arrArticleDetail['reference_detail']))
                {
                    $arrRef = array();
                    foreach ($this->arrArticleDetail['reference_detail'] as $reference)
                    {
                        $arrRef[] = '<a alt="' . $reference['title_format'] . '" title="' . $reference['title_format'] . '" href="' . $this->ShareurlWorldcup($reference['share_url']) . '">' . $reference['title'] . '</a>';
                    }
                    ?>
                    <div class="relative_new">
                        <ul class="list_news_dot_3x3_300">
                            <li>
                                <?php
                                echo implode(' / ', $arrRef);
                                ?>
                            </li>
                        </ul>
                    </div>
                    <?php
                }
                ?>
                <div class="fck_detail width_common"><?php echo $this->arrArticleDetail['content']; ?></div>
                <?php
                if(isset($this->arrArticleDetail['list_object_type'][OBJECT_TYPE_MATCH_ARTICLE]) && !empty($this->arrArticleDetail['list_object_type'][OBJECT_TYPE_MATCH_ARTICLE]))
                {
                    $arrMatchArticle = $this->arrArticleDetail['list_object_type'][OBJECT_TYPE_MATCH_ARTICLE];
                    //set id
                    $objMatch->setId($arrMatchArticle);
                    foreach($arrMatchArticle as $matchId)
                    {
                        //get detail match
                        $matchDetail = $objMatch->getDetailObjectBasic($matchId);
                        if (empty($matchDetail) || $matchDetail['status'] == 2)
                        {
                            continue;
                        }
                        $objTeam->setId(array($matchDetail['team1'],$matchDetail['team2']));
                        $team1 = $objTeam->getDetailObjectBasic($matchDetail['team1']);
                        $team2 = $objTeam->getDetailObjectBasic($matchDetail['team2']);
                    ?>
                    <div class="box_category width_common space_box box_dudoan">
                        <div class="title_box_detailpage width_common">
                            <div class="txt_main_category"><a>Dự đoán của bạn</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <div class="block_dudoan category_guess_score">
                                <table class="">
                                    <thead>
                                        <tr>
                                            <td colspan="3" class="minutes <?php echo ($matchDetail['status'] == 1 || $matchDetail['status'] == 2)?'chuadau':'';?>">
                                                <?php if($matchDetail['status'] == 1 || $matchDetail['status'] == 2) //chua dien ra or da ket thuc
                                                {
                                                    echo $matchDetail['datetime_happen_format'];
                                                }
                                                else
                                                {
                                                    $text = '';
                                                    switch ((int)$matchDetail['status'])
                                                    {
                                                        case 4:
                                                            $text = 'Hết hiệp 1';
                                                            break;
                                                        case 6:
                                                            $text = 'Hết hiệp 2';
                                                            break;
                                                        case 8:
                                                            $text = 'Hết hiệp phụ thứ nhất';
                                                            break;
                                                        case 10:
                                                            $text = 'Hết hiệp phụ thứ hai';
                                                            break;
                                                        case 11:
                                                            $text = 'Penalty';
                                                            break;
                                                        default:
                                                            $text = $data['matchTime'] . "'";
                                                            break;
                                                    }
                                                    echo $text;
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <div class="daiphatsong" data-schedule-match="<?php echo $matchDetail['id']; ?>"></div>
                                            </td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="current">
                                            <td class="main_team">
                                                <img width="40" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                                <p><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>" alt="<?php echo $team1['name_format']; ?>">
                                                <?php echo $team1['name']; ?>
                                                </a></p>

                                            </td>
                                            <td class="score">
                                                <?php
												if($matchDetail['status'] != 1)//dang dien ra hoạc da ket thuc
												{
												?>
                                                <div class="width_common">
                                                    <span class="box no-border"><?php echo $matchDetail['goal1']; ?></span>
                                                    <span class="box no-border">-</span>
                                                    <span class="box no-border"><?php echo $matchDetail['goal2']; ?></span>
                                                    <?php
                                                    if($matchDetail['penalty1'] > 0 || $matchDetail['penalty2'] > 0)
                                                    {
                                                    ?>
                                                    <p class="txt_11" style="font-weight:normal">penalty</p>
                                                    <p class="txt_11" style="color:red">(<?php echo $matchDetail['penalty1'],' - ', $matchDetail['penalty2'] ;?>)</p>
                                                    <?php
                                                    }
                                                    ?>
                                                </div>
												<?php
												}
                                                if($matchDetail['status'] != 2) //chua dien ra hoac dang dien ra
												{
												?>
                                                <div class="width_common">
                                                    <span class="box"><input type="text" value="" data-rel="<?php echo $matchDetail['id'];?>-team1"></span>
                                                    <span class="box no-border">-</span>
                                                    <span class="box"><input type="text" value="" data-rel="<?php echo $matchDetail['id'];?>-team2"></span>
                                                </div>
												<?php
												}
												?>
                                            </td>
                                            <td class="sub_team">
                                                <img width="40" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                                <p><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>" alt="<?php echo $team2['name_format']; ?>">
                                                    <?php echo $team2['name']; ?>
                                                    </a></p>
                                            </td>
                                        </tr>
                                        <tr class="submit">
                                            <td class="main_team"></td>
                                            <td class="score"><button type="submit" class="predict-match" data-rel="<?php echo $matchDetail['id'];?>" data-predict-type="6" data-time="<?php echo $matchDetail['matchTime'];?>" data-predict-text="<?php echo $team1['name'];?> vs <?php echo $team2['name'];?>" onclick="_gaq.push(['_trackEvent', 'Trang bài viết World Cup', 'Click button Gửi trong box', 'Box Dự đoán']);">Gửi</button>
                                                <a href="<?php echo $this->configView['url']. '/thong-ke/tran-', Fpt_Filter::setSeoLink($team1['name'] . ' vs ' . $team2['name'] . ' ' . $matchDetail['id'])  ?>" alt="<?php echo $matchDetail['name_format']; ?>" title="<?php echo $matchDetail['name_format']; ?>"><button class="btn_goiy" type="submit2">Gợi ý</button></a>
                                            </td>
                                            <td class="sub_team">&nbsp;</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <?php
                    }
                }
                ?>
                <?php
                if(!empty($this->arrTeamData))
                {
                    $countTeam = count($this->arrTeamData);
                ?>
                <div class="box_category width_common space_box box_ttdoibong">
                    <div class="title_box_detailpage width_common">
                        <div class="txt_main_category"><a>Thông tin đội bóng</a></div>
                    </div>
                    <div class="content_box_category width_common">
                        <?php
                        if($countTeam == 1)
                        {
                            foreach($this->arrTeamData as $team)
                            {
                            ?>
                            <div class="box_tt_1doi">
                                <div class="block_image_quocgia">
                                    <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                        <img alt="<?php echo $team['name_format']; ?>" src="<?php echo $this->Imageurl($team['thumbnail'], 'size1'); ?>" />
                                    </a>
                                </div>
                                <div class="info_quocgia">
                                    <div class="info_1">
                                        <p class="txt_tenquocgia">
                                            <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                                <?php echo $team['name']; ?>
                                            </a>
                                        </p>
                                        <?php
                                        if(isset($team['extend'][$team['id']]) && !empty($team['extend'][$team['id']]['Lead']))
                                        {
                                            echo $team['extend'][$team['id']]['Lead'];
                                        }
                                        ?>
                                    </div>
                                    <?php
                                    if(!empty($this->arrMatchId))
                                    {
                                    ?>
                                    <div class="info_2">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td class="txt_defaul"> <div class="txt_trandau">Trận đấu:</div></td>
                                                    <td class="txt_info_quocgia">&nbsp;</td>
                                                </tr>
                                                <?php
                                                if (isset($team['match_detail']) && !empty($team['match_detail']))
                                                {
                                                    foreach ($team['match_detail'] as $matchCommingSoon)
                                                    {
                                                        if(empty($matchCommingSoon))
                                                        {
                                                            continue;
                                                        }
                                                        $objTeam->setId(array($matchDetail['team1'],$matchDetail['team2']));
                                                        $team1 = $objTeam->getDetailObjectBasic($matchCommingSoon['team1']);
                                                        $team2 = $objTeam->getDetailObjectBasic($matchCommingSoon['team2']);
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">
                                                                <a href="<?php echo $this->configView['url']. '/thong-ke/tran-', Fpt_Filter::setSeoLink($team1['name'] . ' vs ' . $team2['name'] . ' ' . $matchCommingSoon['id'])  ?>" alt="<?php echo $matchCommingSoon['name_format']; ?>" title="<?php echo $matchCommingSoon['name_format']; ?>">
                                                                <?php
                                                                if ($matchCommingSoon['status'] == '1')
                                                                {
                                                                    echo $team1['abbreviation'] . ' - ' . $team2['abbreviation'];
                                                                }
                                                                else {
                                                                    echo $team1['abbreviation'] . '&nbsp;'.$matchCommingSoon['goal1']. ' - '. $matchCommingSoon['goal2']. '&nbsp;' . $team2['abbreviation'];
                                                                }
                                                                ?>
                                                                </a>
                                                            </td>
                                                            <td class="txt_info_quocgia">(<?php echo $matchCommingSoon['datetime_happen_format']; ?>)</td>
                                                        </tr>
                                                        <?php
                                                        unset($name);
                                                    }
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <?php
                                    }
                                    ?>
                                </div>
                            </div>
                            <?php
                            }
                        }
                        ?>
                        <?php
                        if($countTeam == 2)
                        {
                            ?>
                            <div class="box_tt_2doi">
                                <?php
                                $i = 0;
                                foreach($this->arrTeamData as $team)
                                {
                                    $i++;
                                    ?>
                                    <div class="doiitem<?php echo $i==2?'_2':''; ?>">
                                        <div class="block_image_quocgia">
                                            <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                                <img alt="<?php echo $team['name_format']; ?>" src="<?php echo $this->Imageurl($team['thumbnail'], 'size1'); ?>" />
                                            </a>
                                        </div>
                                        <div class="info_quocgia">
                                            <div class="info_1">
                                                <p class="txt_tenquocgia">
                                                    <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                                        <?php echo $team['name']; ?>
                                                    </a>
                                                </p>
                                                <?php
                                                if(!empty($this->arrMatchId))
                                                {
                                                ?>
                                                <table border="0" cellspacing="0" cellpadding="0">
                                                    <tbody>
														<?php
														if (isset($team['match_detail']) && !empty($team['match_detail']))
														{
															foreach ($team['match_detail'] as $matchCommingSoon)
															{
																if(empty($matchCommingSoon))
																{
																	continue;
																}
																//$name = explode('-', $matchCommingSoon['name']);
																$objTeam->setId(array($matchDetail['team1'],$matchDetail['team2']));
																$team1 = $objTeam->getDetailObjectBasic($matchCommingSoon['team1']);
																$team2 = $objTeam->getDetailObjectBasic($matchCommingSoon['team2']);
																?>
																<tr>
																	<td class="txt_defaul">
																		<a href="<?php echo $this->configView['url']. '/thong-ke/tran-', Fpt_Filter::setSeoLink($team1['name'] . ' vs ' . $team2['name'] . ' ' . $matchCommingSoon['id'])  ?>" alt="<?php echo $matchCommingSoon['name_format']; ?>" title="<?php echo $matchCommingSoon['name_format']; ?>">
                                                                            <?php
                                                                            if($matchCommingSoon['status'] == '1') {
                                                                                echo $team1['abbreviation'] . ' - ' . $team2['abbreviation'];
                                                                            }
                                                                            else {
                                                                                echo $team1['abbreviation'] . '&nbsp;'. $matchCommingSoon['goal1']. ' - '. $matchCommingSoon['goal2']. '&nbsp;' . $team2['abbreviation'];
                                                                            }
                                                                        ?>
																		</a>
																	</td>
																</tr>
                                                                <tr>
                                                                    <td class="txt_info_quocgia">(<?php echo $matchCommingSoon['datetime_happen_format']; ?>)</td>
                                                                </tr>
																<?php
																//unset($name);
															}
														}
														?>
													</tbody>
                                                </table>
                                                <?php
                                                }
                                                ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                            <?php
                        }
                        ?>
                        <?php
                        if($countTeam == 3 || $countTeam == 4)
                        {
                            ?>
                            <div class="<?php echo $countTeam==3?'box_tt_3doi':'box_tt_4doi';?>">
                                <?php
                                foreach($this->arrTeamData as $team)
                                {
                                    ?>
                                    <div class="doiitem">
                                        <div class="block_image_quocgia">
                                            <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                                <img alt="<?php echo $team['name_format']; ?>" src="<?php echo $this->Imageurl($team['thumbnail'], 'size1'); ?>" />
                                            </a>
                                        </div>
                                        <div class="info_quocgia">
                                            <div class="info_1">
                                                <p class="txt_tenquocgia">
                                                    <a href="<?php echo $this->ShareurlWorldcup($team['share_url']); ?>" alt="<?php echo $team['name_format']; ?>" title="<?php echo $team['name_format']; ?>" >
                                                        <?php echo $team['name']; ?>
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                        <?php
                                        if(!empty($this->arrMatchId))
                                        {
                                        ?>
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <?php
                                                if (isset($team['match_detail']) && !empty($team['match_detail']))
                                                {
                                                    foreach ($team['match_detail'] as $matchCommingSoon)
                                                    {
                                                        if(empty($matchCommingSoon))
                                                        {
                                                            continue;
                                                        }
                                                        //$name = explode('-', $matchCommingSoon['name']);
                                                        $objTeam->setId(array($matchDetail['team1'],$matchDetail['team2']));
                                                        $team1 = $objTeam->getDetailObjectBasic($matchCommingSoon['team1']);
                                                        $team2 = $objTeam->getDetailObjectBasic($matchCommingSoon['team2']);
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">
                                                                <a href="<?php echo $this->configView['url']. '/thong-ke/tran-', Fpt_Filter::setSeoLink($team1['name'] . ' vs ' . $team2['name'] . ' ' . $matchCommingSoon['id'])  ?>" alt="<?php echo $matchCommingSoon['name_format']; ?>" title="<?php echo $matchCommingSoon['name_format']; ?>">
                                                                <?php
                                                                    if($matchCommingSoon['status'] == '1') {
                                                                        echo $team1['abbreviation'] . ' - ' . $team2['abbreviation'];
                                                                    }
                                                                    else {
                                                                        echo $team1['abbreviation'] . '&nbsp;'.  $matchCommingSoon['goal1']. ' - '. $matchCommingSoon['goal2']. '&nbsp;' . $team2['abbreviation'];
                                                                    }
                                                                ?>
                                                                </a>
                                                            </td>
                                                            <?php
															if($countTeam == 3)
															{
															?>
															<td class="txt_info_quocgia">(<?php echo $matchCommingSoon['datetime_happen_format']; ?>)</td>
															<?php
															}
															?>
                                                        </tr>
                                                        <?php
                                                        //unset($name);
                                                    }
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                        <?php
                                        }
                                        ?>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <?php
                }
                ?>
                <?php
                if(!empty($this->arrPlayerData))
                {
                    $countPlayer = count($this->arrPlayerData);
                    ?>
                    <div class="box_category width_common space_box box_ttcauthu">
                        <div class="title_box_detailpage width_common">
                            <div class="txt_main_category"><a>Thông tin cầu thủ</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <?php
                            if($countPlayer == 1)
                            {
                            ?>
                            <div class="box_tt_1cauthu">
                                <?php
                                foreach($this->arrPlayerData as $playerDetail)
                                {
                                ?>
                                <div class="block_image_cauthu">
                                    <a href="<?php echo $this->ShareurlWorldcup($playerDetail['share_url']); ?>" title="<?php echo $playerDetail['name_format']; ?>" alt="<?php echo $playerDetail['name_format']; ?>">
                                        <img alt="<?php echo ($playerDetail['name_format']); ?>" src="<?php echo $this->Imageurl($playerDetail['thumbnail'], 'size8'); ?>" />
                                    </a>
                                    <p class="txt_cauthuname">
                                        <a href="<?php echo $this->ShareurlWorldcup($playerDetail['share_url']); ?>" title="<?php echo $playerDetail['name_format']; ?>" alt="<?php echo $playerDetail['name_format']; ?>">
                                            <?php echo $playerDetail['name']; ?>
                                        </a>
                                    </p>
                                </div>
                                <div class="info_cauthu">
                                    <div class="info_1">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <?php
                                                if (!empty($playerDetail['nationality_name']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Quốc tịch:</td>
                                                    <td class="txt_info_quocgia"><?php echo $playerDetail['nationality_name']; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['birthday']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Ngày sinh:</td>
                                                    <td class="txt_info_quocgia">&nbsp;<?php echo date('j/n/Y', strtotime($playerDetail['birthday'])); ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['place_birth']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Nơi sinh:</td>
                                                    <td class="txt_info_quocgia"><?php echo $playerDetail['place_birth']; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (isset($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name']) && !empty($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">CLB:</td>
                                                    <td class="txt_info_quocgia"><?php echo (isset($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name'])) ? $playerDetail['team_detail'][$playerDetail['team_id'][0]]['name'] : ""; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['height']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Chiều cao:</td>
                                                    <td class="txt_info_quocgia"><?php echo $playerDetail['height']; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['weight']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Cân nặng:</td>
                                                    <td class="txt_info_quocgia"><?php echo $playerDetail['weight'].' kg'; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['position']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Vị trí:</td>
                                                    <td class="txt_info_quocgia">
                                                        <?php
                                                        switch ($playerDetail['position'])
                                                        {
                                                            case 'D':
                                                                $position = 'Hậu vệ';
                                                                break;
                                                            case 'F':
                                                                $position = 'Tiền đạo';
                                                                break;
                                                            case 'M':
                                                                $position = 'Tiền vệ';
                                                                break;
                                                            case 'G':
                                                                $position = 'Thủ môn';
                                                                break;
                                                            case 'C':
                                                                $position = 'Huấn luyện viên';
                                                                break;
                                                            case 'SUB':
                                                                $position = 'Dự bị';
                                                                break;
                                                            default :
                                                                $position = $playerDetail['position'];
                                                                break;
                                                        }
                                                        echo $position;
                                                        ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                                <?php
                                                if (!empty($playerDetail['num_coat']))
                                                {
                                                ?>
                                                <tr>
                                                    <td class="txt_defaul">Áo số:</td>
                                                    <td class="txt_info_quocgia"><?php echo $playerDetail['num_coat']; ?></td>
                                                </tr>
                                                <?php
                                                }
                                                ?>
                                            </tbody></table>
                                    </div>
                                    <?php
                                    if(isset($playerDetail['object_news']) && !empty($playerDetail['object_news']))
                                    {
                                    ?>
                                    <div class="info_2">
                                        <ul class="list_tin_300">
                                            <?php
                                            foreach($playerDetail['object_news'] as $id)
                                            {
                                                $article = $this->objArticle->getArticleBasic($id);
                                            ?>
                                                <li>
                                                    <div class="block_image_news width_common">
                                                        <div class="title_news">
                                                            <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>" class="txt_link"><?php echo $article['title']; ?></a>
                                                        </div>
                                                        <div class="block_thumb_lead">
                                                            <?php
                                                            if(!empty($article['thumbnail_url']))
                                                            {
                                                            ?>
                                                            <div class="thumb">
                                                                <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                                    <img src="<?php echo $this->ImageurlArticle($article, 'size1'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                                                </a>
                                                                <?php echo $this->ArticleTypeIcon($article); ?>
                                                            </div>
                                                            <?php
                                                            }
                                                            ?>
                                                            <div class="news_lead"><?php echo $article['lead']; ?></div>
                                                        </div>
                                                    </div>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                    <?php
                                    }
                                    ?>
                                </div>
                                <?php
                                }
                                ?>
                            </div>
                            <?php
                            }
                            ?>
                            <?php
                            if($countPlayer == 2 || $countPlayer == 3 || $countPlayer == 4)
                            {
                            ?>
                            <div class="<?php echo 'box_tt_'.$countPlayer.'cauthu';?>">
                                <?php
                                foreach($this->arrPlayerData as $playerDetail)
                                {
                                    ?>
                                    <div class="cauthu_item">
                                        <div class="block_image_cauthu">
                                            <a href="<?php echo $this->ShareurlWorldcup($playerDetail['share_url']); ?>" title="<?php echo $playerDetail['name_format']; ?>" alt="<?php echo $playerDetail['name_format']; ?>">
                                                <img alt="<?php echo ($playerDetail['name_format']); ?>" src="<?php echo $this->Imageurl($playerDetail['thumbnail'], 'size8'); ?>" />
                                            </a>
                                            <p class="txt_cauthuname">
                                                <a href="<?php echo $this->ShareurlWorldcup($playerDetail['share_url']); ?>" title="<?php echo $playerDetail['name_format']; ?>" alt="<?php echo $playerDetail['name_format']; ?>">
                                                    <?php echo $playerDetail['name']; ?>
                                                </a>
                                            </p>
                                        </div>
                                        <?php
                                        if($countPlayer == 2)
                                        {
                                        ?>
                                        <div class="info_cauthu">
                                            <div class="info_2">
                                                <table border="0" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <?php
                                                        if (!empty($playerDetail['nationality_name']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Quốc tịch:</td>
                                                            <td class="txt_info_quocgia"><?php echo $playerDetail['nationality_name']; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['birthday']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Ngày sinh: </td>
                                                            <td class="txt_info_quocgia">&nbsp;<?php echo date('j/n/Y', strtotime($playerDetail['birthday'])); ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['place_birth']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Nơi sinh:</td>
                                                            <td class="txt_info_quocgia"><?php echo $playerDetail['place_birth']; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (isset($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name']) && !empty($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">CLB:</td>
                                                            <td class="txt_info_quocgia"><?php echo (isset($playerDetail['team_detail'][$playerDetail['team_id'][0]]['name'])) ? $playerDetail['team_detail'][$playerDetail['team_id'][0]]['name'] : ""; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['height']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Chiều cao:</td>
                                                            <td class="txt_info_quocgia"><?php echo $playerDetail['height']; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['weight']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Cân nặng:</td>
                                                            <td class="txt_info_quocgia"><?php echo $playerDetail['weight'].' kg'; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['position']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Vị trí:</td>
                                                            <td class="txt_info_quocgia">
                                                                <?php
                                                                switch ($playerDetail['position'])
                                                                {
                                                                    case 'D':
                                                                        $position = 'Hậu vệ';
                                                                        break;
                                                                    case 'F':
                                                                        $position = 'Tiền đạo';
                                                                        break;
                                                                    case 'M':
                                                                        $position = 'Tiền vệ';
                                                                        break;
                                                                    case 'G':
                                                                        $position = 'Thủ môn';
                                                                        break;
                                                                    case 'C':
                                                                        $position = 'Huấn luyện viên';
                                                                        break;
                                                                    case 'SUB':
                                                                        $position = 'Dự bị';
                                                                        break;
                                                                    default :
                                                                        $position = $playerDetail['position'];
                                                                        break;
                                                                }
                                                                echo $position;
                                                                ?>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                        <?php
                                                        if (!empty($playerDetail['num_coat']))
                                                        {
                                                        ?>
                                                        <tr>
                                                            <td class="txt_defaul">Áo số:</td>
                                                            <td class="txt_info_quocgia"><?php echo $playerDetail['num_coat']; ?></td>
                                                        </tr>
                                                        <?php
                                                        }
                                                        ?>
                                                    </tbody></table>
                                            </div>
                                        </div>
                                        <?php
                                        }
                                        ?>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                            <?php
                            }
                            ?>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <script type="text/javascript">
                    if(typeof(Parser) != "undefined"){
                        Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                        Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                        Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                        Parser.SITE_ID = <?php echo SITE_ID; ?>;
                        Parser.AUTO_PLAY = 1;
                        Parser.parseAll();
                    }
                    if (typeof(common.resizeImageDetail) != 'undefined') {
                        common.resizeImageDetail();
                        $(window).resize(function() {
                            common.delayFireOnce(1000).done(function() {
                                common.resizeImageDetail();
                            });
                        });
                    }
                </script>
                <div class="space_box width_common">
                    <?php
                    echo $this->render('/common/box_share_bottom.phtml');
                    ?>
                </div>
                <?php
                if (!empty($this->arrTopic) || !empty($this->arrArticleDetail['list_reference_sites_id']) && is_array($this->arrArticleDetail['list_reference_sites_id']))
                {
                    $has_topic = !empty($this->arrTopic);
                    ?>
                    <div id="box_tinlienquan" class="width_common mg_bottom_20">
                        <div class="title_box_category style_02">
                            <div class="txt_main_category"><a href="javascript:;" title="Tin liên quan">Tin liên quan</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <?php
                            $class_no_space = 'no_space';
                            if (!empty($this->arrTopic))
                            {
                                $class_no_space = '';
                                ?>
                                <ul class="list_news_dot_3x3">
                                    <?php
                                    foreach ($this->arrTopic as $id)
                                    {
                                        $article = $this->objArticle->getArticleBasic($id);
                                        if (empty($article))
                                        {
                                            continue;
                                        }
                                        ?>
                                        <li>
                                            <a href="<?php echo $article['share_url']; ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                <?php
                                                echo $article['title'];
                                                ?>
                                            </a>
                                            <span class="txt_666">(<?php echo $this->DateTimeFormat($article['publish_time'], 'short'); ?>)</span>
                                            <span class="no_wrap">
                                                <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                                <?php echo $this->ArticleComment($article); ?>
                                            </span>
                                        </li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                                <div class="block_view_more">
                                    <a href="<?php echo $this->arrTopicDetail['share_url']; ?>" title="<?php echo $this->arrTopicDetail['title']; ?>" class="txt_view_more">Xem thêm</a>
                                </div>
                                <?php
                            }
                            //update chức năng link chéo dưới chân bài giữa các trang--
                            //Click link của VNEx hoặc Vertical sẽ đi chính trang
                            //Click link khác của Ngôi Sao hoặc iOne sẽ mở Tab mới

                            if (!empty($this->arrArticleDetail['list_reference_sites_id']))
                            {
                                $arrListReferenceSiteId = $this->arrArticleDetail['list_reference_sites_id'];
                                $arrVNE = array(SITE_ID, SITE_DULICH, SITE_DOISONG, SITE_GIAITRI, SITE_SOHOA, SITE_KINHDOANH, SITE_VNE);
                                //  Set flags to know which situation
                                $flag_vne = false;
                                $flag_ione = false;
                                $flag_ngoisao = false;
                                foreach ($arrListReferenceSiteId as $reference)
                                {
                                    if (empty($reference))
                                        continue;
                                    if (in_array($reference['site_id'], $arrVNE))
                                    {
                                        $flag_vne = true;
                                    }
                                    if ($reference['site_id'] == SITE_IONE)
                                    {
                                        $flag_ione = true;
                                    }
                                    if ($reference['site_id'] == SITE_NGOISAO)
                                    {
                                        $flag_ngoisao = true;
                                    }
                                }
                                echo $this->partial('detail/box/box_includelink.phtml', array('list_reference' => $arrListReferenceSiteId, 'flag_vne' => $flag_vne, 'flag_ione' => $flag_ione, 'flag_ngoisao' => $flag_ngoisao, 'has_topic' => $has_topic, 'arrVNE' => $arrVNE,  'config' => $this->configView));
                            }
                            ?>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <?php
                if (DEVICE_ENV != 1)
                {
                    ?>
                    <!-- Article_BANNER 468x90-->
                    <div class="banner_468 banner_common">
                        <div class="banner_468x90">
                            <script type="text/javascript">
                                try{Poly_Article();}catch(e){}
                            </script>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <?php
            //Check permission comment
            if ($this->arrArticleDetail['iscomment'])
            {
                echo $this->render('/block/comment.phtml');
            }//end if
            ?>
            <?php
            if (!empty($this->arrArticleDetail['list_tag']))
            {
                ?>
                <div class="block_tag width_common space_bottom_20">
                    <div class="txt_tag">Tags</div>
                    <?php
                    foreach ($this->arrArticleDetail['list_tag'] as $list_tag)
                    {
                        echo '<a href="', $this->configView['url_vne'], $list_tag['tag_url'], '" title="', $list_tag['tag_name_format'], '" class="tag_item">', $list_tag['tag_name'], '</a>';
                    }
                    ?>
                </div>
                <?php
            }
            ?>
            <?php
            if (!empty($this->arrOrtherArticle))
            {
                ?>
                <div id="box_tinkhac_detail" class="box_category width_common style_03">
                    <?php
                    echo $this->render('detail/box/othernews_' . $device . '.phtml');
                    ?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <?php
    if(DEVICE_ENV != 1)
    {
    ?>
    <div id="col_right">
       <?php echo $this->GetBlock('left'); ?>
    </div>
    <?php
    }
    ?>
</div>
<script type="text/javascript">
    //init send mail
    var article_title = "<?php echo addslashes($this->arrArticleDetail['title_format']) , ' - VnExpress Thể Thao'; ?>",
    article_description = "<?php echo urlencode($this->arrArticleDetail['lead']); ?>",
    article_image = "<?php echo!empty($this->arrArticleDetail['thumbnail_url']) ? $this->ImageurlArticle($this->arrArticleDetail, 'size1') : ''; ?>";
    $(function(){
        if (device_env != 1) {
            sendmail.init({
                article_link: '<?php echo $this->arrArticleDetail['share_url']; ?>',
                article_title: article_title,
                url_post: '<?php echo $this->configView['url']; ?>/detail/ajaxsendmail'
            });
        }
    });
</script>