<!DOCTYPE html>
<html>
    <head>
        <?php
        //Get cookie: switch_to_desktop to set suffix
        $isSwitch   = SWITCH_DESKTOP;
        $cssSuffix  = $isSwitch?'_only':'';
        ?>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        if (!$isSwitch )
        {
            ?>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
            <?php
        }//end if
        ?>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="VnExpress.net" />
        <meta name="dc.description" content="Tin nhanh video clip hình ảnh các môn thể thao: bóng đá quyền anh đua xe bóng chuyền cầu lông… đang diễn ra ở VN & thế giới.." />
        <meta name="dc.subject" content="Thể Thao - Vnexpress" />
        <meta name="dc.created" content="2001-02-26" />
        <meta name="dc.publisher" content="VnExpress" />
        <meta name="dc.rights.copyright" content="VnExpress" />
        <meta name="dc.creator.name" content="VnExpress" />
        <meta name="dc.creator.email" content="webmaster@vnexpress.net" />
        <meta name="dc.identifier" content="http://vnexpress.net" />
        <meta name="copyright" content="VnExpress" />
        <meta name="author" content="VnExpress" />
        <meta name="dc.language" content="vi-VN" />
        <meta name="robots" content="index,follow" />
        <meta http-equiv="content-language" content="vi"/>
        <meta name="geo.placename" content="Ha Noi, Viet Nam" />
        <meta name="geo.region" content="VN-HN" />
        <meta name="geo.position" content="21.030624;105.782431" />
        <meta name="ICBM" content="21.030624, 105.782431" />
        <meta name="revisit-after" content="days">
        <!-- iPad icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/72x72.png" sizes="72x72">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="144x144">
        <!-- iPhone and iPod touch icons -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png" sizes="57x57">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="114x114">
        <!-- Nokia Symbian -->
        <link rel="nokia-touch-icon" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/57x57.png">
        <!-- Android icon precomposed so it takes precedence -->
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->configView['vnecdn']['images']; ?>/logos/114x114.png" sizes="1x1">
        <?php
        if (!$this->notRefreshPage)
        {
            ?>
            <meta http-equiv="REFRESH" content="1800" />
            <?php
        }
        ?>
        <meta content="VnExpress" property="og:site_name" />
        <meta content="<?php echo $this->escape($this->ogType); ?>" property="og:type" />
        <meta content="<?php echo $this->escape($this->ogTitle); ?>" itemprop="headline" property="og:title" />
        <meta content="<?php echo $this->ogUrl; ?>" itemprop="url" property="og:url" />
        <meta content="<?php echo $this->ogImage; ?>" itemprop="thumbnailUrl" property="og:image" />
        <meta content="<?php echo $this->escape($this->ogDescription); ?>" itemprop="description" property="og:description" />
        <link rel="alternate" href="<?php echo $this->configView['url']; ?>" hreflang="vi-vn" />
        <!--Meta Tag-->
        <?php
        echo $this->headMeta();
        $tt_category_id = isset($this->intCategoryId) ? $this->intCategoryId : SITE_ID;
        $tt_article_id  = isset($this->intArticleId) ? $this->intArticleId : $tt_category_id;
        if ($tt_category_id == 1003240) {
            echo '<meta name="robots" content="noindex">';
        }
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <meta name="tt_site_id" content="<?php echo SITE_ID; ?>" />
        <!--Title-->
        <?php echo $this->headTitle(); ?>
        <!-- JS -->
        <script type="text/javascript">
            //GA
            var _gaq = _gaq || [];
            _gaq.push(["_setAccount", "UA-249346-5"]);
            _gaq.push(["_trackPageview"]);
            _gaq.push(["c._setAccount", "UA-249346-37"]);
            _gaq.push(["c._trackPageview"]);
            _gaq.push(["d._setAccount", "UA-249346-18"]);
            _gaq.push(["d._trackPageview"]);
            _gaq.push(["e._setAccount", "UA-50285069-12"]);
            _gaq.push(["e._trackPageview"]);
            (function() {
                var a = document.createElement("script");
                a.type = "text/javascript";
                a.async = !0;
                a.src = ("https:" == document.location.protocol ? "https://" : "http://") + "stats.g.doubleclick.net/dc.js";
                var b = document.getElementsByTagName("script")[0];
                b.parentNode.insertBefore(a, b)
            })();
            //E-click
            var _siteId = "11";
            (function() {
                var a = document.createElement("script");
                a.type = "text/javascript";
                a.async = !0;
                a.src = "http://st.l.a.eclick.vn/ea.js";
                var b = document.getElementsByTagName("script")[0];
                b.parentNode.insertBefore(a, b)
            })();
            //Begin comScore Tag
            var _comscore = _comscore || [];
            _comscore.push({ c1: "2", c2: "19747654" });
            (function() {
                var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
                s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
                el.parentNode.insertBefore(s, el);
            })();
            (function() {
                var csid = "F09828";
                var bpid = "fpt_vn";
                var e = document.createElement("script");
                var s = document.getElementsByTagName("script")[0];
                e.src = "//js.revsci.net/gateway/gw.js?auto=t&csid=" + csid + "&bpid=" + bpid;
                e.async = true;
                s.parentNode.insertBefore(e, s);
            })();

            var SITE_ID     = <?php echo SITE_ID; ?>,
                img_url     = '<?php echo $this->configView['images']; ?>',
                css_url     = '<?php echo $this->configView['css']; ?>',
                base_url    = '<?php echo $this->configView['url']; ?>',
                device_env  = <?php echo DEVICE_ENV; ?>,
                article_id  = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>,
                vne_url     = '<?php echo $this->configView['url_vne']; ?>',
                application_env = '<?php echo APPLICATION_ENV; ?>',
                interactions_url = '<?php echo $this->configView['comment']; ?>',
                predict_with_captcha = 0;
            document.domain = '<?php echo DOMAIN_VNE ?>';
        </script>
        <noscript>
            <img src="http://b.scorecardresearch.com/p?c1=2&c2=19747654&cv=2.0&cj=1" />
        </noscript>
        <!-- End comScore Tag -->
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/general<?php echo $cssSuffix;?>.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/thethao<?php echo $cssSuffix;?>.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['myvne']['css']; ?>/my_index.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['myvne']['css']; ?>/lib/jquery.fancybox.css"  media="all"/>
        <?php echo $this->headLink(); ?>
        <script src="<?php echo $this->configView['vnecdn']['libs']; ?>/jquery-1.7.1.min.js"></script>
        <script src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <script src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/utils.js"></script>
        <script src="<?php echo $this->configView['polyads']['core']; ?>/TheThaoShowAds.js"></script>
    </head>
    <body>
        <div id="myvne_taskbar"></div>
        <!--Check is switch-->
        <?php
        if ( $isSwitch )
        {
        ?>
        <div id="bar_swich_page">
            <div class="swich_page">
                <div class="goback_oldversion"> <a id="del-switch-to" href="javascript:;"> Quay lại phiên bản mặc định </a> </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <?php
        }//end if
        ?>
        <div class="block_more_info" id="box_col_left">
            <div class="box_width_common">
                <div class="btn_control_col_left"><img class="icon_total_vne icon_hambermenu" src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/img_blank.gif" alt="" /></div>
                <div class="block_scoll_menu">
                    <div class="block_search">
                        <form action="http://timkiem.vnexpress.net/thethao" method="get" target="_blank" id="search">
                            <input type="text" name="q" value="Tìm kiếm" maxlength="80" class="input_search" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''"/>
                            <input type="submit" value="" class="icon_menu_phone btn_search" />
                        </form>
                        <div class="clear">&nbsp;</div>
                    </div>
                    <ul class="list_item_panel">
                        <li><a href="<?php echo $this->configView['url_vne']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Trang chủ']);" title="Trang chủ" class="bg_666"><span class="icon_menu_phone ico_menu_01">&nbsp;</span>Trang chủ</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/thoi-su" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thời sự']);" title="Thời sự"><span class="icon_menu_phone ico_menu_02">&nbsp;</span>Thời sự</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/goc-nhin" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Góc nhìn']);"><span class="icon_menu_phone ico_menu_03">&nbsp;</span>Góc nhìn</a></
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thế giới']);" title="Thế giới"><span class="icon_menu_phone ico_menu_05">&nbsp;</span>Thế giới</a></li>
                        <li><a href="<?php echo $this->configView['url_kdo']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Kinh doanh']);" title="Kinh doanh"><span class="icon_menu_phone ico_menu_06">&nbsp;</span>Kinh doanh</a></li>
                        <li><a href="<?php echo $this->configView['url_gti']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Giải trí']);" title="Giải trí"><span class="icon_menu_phone ico_menu_07">&nbsp;</span>Giải trí</a></li>
                        <li class="active"><a href="/" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thể thao']);" title="Thể thao"><span class="icon_menu_phone ico_menu_08">&nbsp;</span>Thể thao</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Pháp luật']);" title="Pháp luật"><span class="icon_menu_phone ico_menu_09">&nbsp;</span>Pháp luật</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/giao-duc" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Giáo dục']);" title="Giáo dục"><span class="icon_menu_phone ico_menu_25">&nbsp;</span>Giáo dục</a></li>
                        <li><a href="<?php echo $this->configView['url_skh']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Sức khỏe']);" title="Sức khỏe"><span class="icon_menu_phone ico_menu_27">&nbsp;</span>Sức khỏe</a></li>
                        <li><a href="<?php echo $this->configView['url_dso']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Đời sống']);" title="Gia đình"><span class="icon_menu_phone ico_menu_10">&nbsp;</span>Gia đình</a></li>
                        <li><a href="<?php echo $this->configView['url_dli']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Du lịch']);" title="Du lịch"><span class="icon_menu_phone ico_menu_23">&nbsp;</span>Du lịch</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Khoa học']);" title="Khoa học"><span class="icon_menu_phone ico_menu_11">&nbsp;</span>Khoa học</a></li>
                        <li><a href="<?php echo $this->configView['url_sho']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Số hóa']);" title="Số hóa"><span class="icon_menu_phone ico_menu_12">&nbsp;</span>Số hóa</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Xe']);" title="Xe"><span class="icon_menu_phone ico_menu_13">&nbsp;</span>Xe</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cong-dong" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Cộng đồng']);" title="Cộng đồng"><span class="icon_menu_phone ico_menu_04">&nbsp;</span>Cộng đồng</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/tam-su" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Tâm sự']);" title="Tâm sự"><span class="icon_menu_phone ico_menu_15">&nbsp;</span>Tâm sự</a></li>
                        <li><a href="http://video.vnexpress.net" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Video']);" title="Video"><span class="icon_menu_phone ico_menu_17">&nbsp;</span>Video</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cuoi" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Cười']);" title="Cười"><span class="icon_menu_phone ico_menu_19">&nbsp;</span>Cười</a></li>
                        <li><a href="http://raovat.vnexpress.net" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Rao vặt']);" title="Rao vặt"><span class="icon_menu_phone ico_menu_16">&nbsp;</span>Rao vặt</a></li>
                        <li><a class="bg_666" href="<?php echo $this->configView['url_vne']; ?>/24h-qua" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', '24h qua']);" title="24h qua"><span class="icon_menu_phone ico_menu_24">&nbsp;</span>24h qua</a></li>
                        <?php
                        //check tablet
                        if ( DEVICE_ENV == 2 )
                        {
                            ?>
                            <li><a class="bg_666" href="javascript:;" id="switch-to-desktop"><span class="icon_menu_phone ico_menu_20">&nbsp;</span>Phiên bản Desktop</a></li>
                            <?php
                        }//end if
                        ?>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/lien-he-toa-soan/?p=thethao" class="bg_666"><span class="icon_menu_phone ico_menu_21">&nbsp;</span>Liên hệ Toà soạn</a></li>
                        <li class="end"><a href="<?php echo $this->configView['url_vne']; ?>/contact.htm" class="bg_666"><span class="icon_menu_phone ico_menu_22">&nbsp;</span>Thông tin Toà soạn</a></li>
                    </ul>
                    <div class="coppy_right_left width_common">
                        <div class="txt_coppy_right">
                            <p>&copy; Copyright 1997 - VnExpress.net, All rights reserved.</p>
                            <p>&reg; VnExpress giữ bản quyền nội dung trên website này.</p>
                        </div>
                        <div class="txt_lienhe"> Hotline:<br>
                            <a href="tel:012388801238">0123.888.0123 (Hà Nội)</a><br />
                            <a href="tel:01292333555">0129.233.3555 (TP HCM) </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
        <div id="page">
            <div id="header_web" class="width_common">
                <div id="header_main">
                    <div class="header_logo width_common">
                        <a href="<?php echo $this->configView['url_vne']; ?>"><img src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/img_logo_vne_web.gif" alt="vnexpress logo"  class="left logo_web"/></a>
                        <div class="banner_728x90 right">
                            <script type="text/javascript">try{Poly_Top();}catch(e){}</script>
                        </div>
                    </div>
                    <ul id="menu_web" class="width_common">
                        <li><a href="<?php echo $this->configView['url_vne']; ?>" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Trang chủ']);" title="Trang chủ"><img src="<?php echo $this->configView['images']; ?>/graphics/img_blank.gif" alt="Home" class="logo_icon_home"/></a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/thoi-su" class="mnu_thoisu" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thời sự']);" title="Thời sự">Thời sự</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi" class="mnu_thegioi" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thế giới']);" title="Thế giới">Thế giới</a></li>
                        <li><a href="<?php echo $this->configView['url_kdo']; ?>" class="mnu_kinhdoanh" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Kinh doanh']);" title="Kinh doanh">Kinh doanh</a></li>
                        <li><a href="<?php echo $this->configView['url_gti']; ?>" class="mnu_giaitri" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Giải trí']);" title="Giải trí">Giải trí</a></li>
                        <li class="active"><a href="/" class="mnu_thethao" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Thể thao']);" title="Thể thao">Thể thao</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat" class="mnu_phapluat" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Pháp luật']);" title="Pháp luật">Pháp luật</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/giao-duc" class="mnu_giaoduc" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Giáo dục']);" title="Giáo dục">Giáo dục</a></li>
                        <li><a href="<?php echo $this->configView['url_skh']; ?>" class="mnu_suckhoe" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Sức khỏe']);" title="Sức khỏe">Sức khỏe</a></li>
                        <li><a href="<?php echo $this->configView['url_dso']; ?>" class="mnu_doisong" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Đời sống']);">Gia đình</a></li>
                        <li><a href="<?php echo $this->configView['url_dli']; ?>" class="mnu_dulich" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Du lịch']);" title="Du lịch">Du lịch</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc" class="mnu_khoahoc" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Khoa học']);" title="Khoa học">Khoa học</a></li>
                        <li><a href="<?php echo $this->configView['url_sho']; ?>" class="mnu_sohoa" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Số hóa']);" title="Số hóa">Số hóa</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may" class="mnu_xe" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Xe']);" title="Xe">Xe</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cong-dong" class="mnu_bandoc" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Cộng đồng']);" title="Cộng đồng">Cộng đồng</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/tam-su" class="mnu_tamsu" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Tâm sự']);" title="Tâm sự">Tâm sự</a></li>
                        <li><a href="http://video.vnexpress.net" class="mnu_video" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Video']);" title="Video">Video</a></li>
						<li class="end"><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cuoi" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Cười']);" title="Cười">Cười</a></li>
                        <li class="item_have_more_menu">
                            <a href="javascript:;" class="end">
                                <img src="<?php echo $this->configView['images']; ?>/graphics/img_blank.gif" class="arrow_lastest_menu">
                            </a>
                            <div class="sub_main_menu_item" style="display: none;">
                                <a href="http://raovat.vnexpress.net" onclick="_gaq.push(['c._trackEvent', 'Menu', 'Click', 'Rao vặt']);" title="Rao vặt">Rao vặt</a>
                            </div>
                        </li>
                    </ul>
                    <div class="mid_header width_common">
                        <ul id="breakumb_web">                            
                            <?php
                            $count = count($this->arrActiveMenu);
                            $i = 0;

                            foreach ($this->arrMenu as $parent)
                            {
                                $class = '';
                                if ($parent['show_folder'] == 0
                                        || $parent['catecode'] == 'lich-thi-dau')
                                {
                                    continue;
                                }
                                if (in_array($parent['category_id'], $this->arrActiveMenu))
                                {
                                    $class = 'class="active" data-url="'.$parent['link'].'" data-name="'.$parent['catename'].'"';
                                }
                                if ($parent['category_id'] == CATE_ID_VIDEO)
                                {
                                    $parent['link'] = 'http://video.vnexpress.net/the-thao';
                                }
                                ?>
                                <li <?php echo $class; ?>>
                                    <h3>
                                        <a href="<?php echo $parent['link']; ?>" class="parent_menu">
                                            <?php echo $parent['catename']; ?>
                                        </a>
                                    </h3>
                                </li>
                                <?php
                                $i++;
                                $class = '';
                            }
                            ?>
                        </ul>
                        <div class="right">
                            <?php
                            if ($this->intCategoryId == CATE_ID_TAITRO)
                            {
                                ?>
                                <a class="txt_thongtinnhataitro">Thông tin nhà tài trợ</a>
                                <?php
                            }
                            else if (empty($this->breakCumb) || empty($this->arrActiveMenu))
                            {
                                ?>
                                <div class="txt_timer" id="clockPC"></div>
                                <?php
                            }
                            if (DEVICE_ENV == 4)
                            {
                                if ($this->intCategoryId != CATE_ID_TAITRO)
                                {
                                    ?>
                                    <a href="<?php echo $this->configView['url_vne'], '/24h-qua/' ?>" class="txt_24h">24h qua</a>
                                    <?php
                                }
                                ?>
                                <a href="<?php echo $this->configView['url_vne'], '/rss/' ?>" class="img_rss left">
                                    <img src="<?php echo $this->configView['css']; ?>/images/graphics/img_rss_2.gif" alt="rss" />
                                </a>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                        if (!empty($this->arrActiveMenu) && !empty($this->breakCumb))
                        {
                            ?>
                            <div class="block_breakumb_left" style="width: 670px;">
                                <ul class="list_arrow_breakumb">
                                    <li class="start have_cap2"><h4><a href="/">Thể thao</a><span class="arrow_breakumb">&nbsp;</span></h4></li>
                                    <?php
                                    $count = count($this->breakCumb) + 1;
                                    $i = 2;
                                    foreach ($this->breakCumb as $breakCumb)
                                    {
                                        $class = ($i < $count) ? 'have_cap' . ($i + 1) . ' ' : '';
                                        $link = $breakCumb['link'] . '/';
                                        echo '<li class="', $class, 'cap', $i, '"><h4><a href="', $link, '">', $breakCumb['catename'], '</a><span class="arrow_breakumb">&nbsp;</span></h4></li>';
                                        $i++;
                                    }
                                    ?>
                                </ul>
                                <?php
                                if (!empty($this->breakCumbSub) && !isset($this->breakCumbOther))
                                {
                                    ?>
                                    <ul class="sub_breakumn">
                                        <?php
                                        $count = count($this->breakCumbSub);
                                        $i = 1;
                                        foreach ($this->breakCumbSub as $category)
                                        {
                                            if (0 == $category['show_folder'] && $count > 1)
                                            {
                                                $count--;
                                                continue;
                                            }
                                            $classHr = '';
                                            if ($i > 6)
                                            {
                                                break;
                                            }
                                            if ($i == $count || 6 == $i)
                                            {
                                                $classLi = 'end ';
                                            }
                                            if (in_array($category['category_id'], $this->arrActiveMenu))
                                            {
                                                $classHr = 'active';
                                            }
                                            echo '<li class="', $classLi, $classHr, '"><h4><a title="', $category['catename'], '" href="', $category['link'], '">', $category['catename'], '</a></h4></li>';

                                            $i++;
                                        }
                                        ?>
                                    </ul>
                                    <?php
                                }
                                ?>
                                <?php
                                if (isset($this->breakCumbOther))
                                {
                                    ?>
                                    <ul class="sub_breakumn">
                                        <li class="start end active"><h4><a href="<?php echo $this->breakCumbOther['link']; ?>"><?php echo $this->breakCumbOther['name']; ?></a><span class="arrow_breakumb">&nbsp;</span></h4></li>
                                    </ul>
                                    <?php
                                }
                                ?>
                            </div>
                            <?php
                        }
                        else
                        {
                            ?>
                            <div class="block_breakumb_left">
                                <ul class="list_arrow_breakumb">
                                    <li class="start"><h4><a href="/">Thể thao</a><span class="arrow_breakumb">&nbsp;</span></h4></li>
                                </ul>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div id="wrapper_header">
                <div id="header">
                    <div class="width_common">
                        <div class="logovne">
                            <a href="<?php echo $this->configView['url_vne']; ?>"><img src="<?php echo $this->configView['vnecdn']['images']; ?>/graphics/logo.png" alt="vnexpress logo" class="img_logo" /></a>
                            <div class="right ipad_header">
                                <div class="block_icon_menu_header right">
                                    <div class="left block_location_tt" data-component-type="weather" data-component-click=""></div>
                                    <a href="http://video.vnexpress.net"><img src="<?php echo $this->configView['images']; ?>/icons/icon_videomenu.gif" alt="" /></a>
                                </div>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                    <div class="clear">&nbsp;</div>
                </div>
            </div>
            <div id="wrapper_container" class="container_common">
                <div id="container">
                    <div class="width_common">
                        <div class="breakumb_timer width_common">
                            <div class="timer_header">
                                <ul>
                                    <?php
                                    if (!empty($this->arrActiveMenu) && $this->arrActiveMenu[0] == SITE_ID)
                                    {
                                        unset($this->arrActiveMenu);
                                    }
                                    ?>
                                    <li class="start<?php echo !empty($this->arrActiveMenu) ? ' have_cap2' : ''; ?>"><a href="/">Thể thao</a><span class="arrow_breakumb">&nbsp;</span></li>
                                    <?php
                                    if (!empty($this->menuDetail) && $this->menuDetail['category_id'] != SITE_ID)
                                    {
                                        ?>
                                        <li class="cap2"><a href="<?php echo $this->menuDetail['link']; ?>"><?php echo $this->menuDetail['catename']; ?></a><span class="arrow_breakumb">&nbsp;</span></li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                            <div class="rss right">
                                <?php
                                if ($this->intCategoryId == CATE_ID_TAITRO)
                                {
                                ?>
                                <a href="#" class="txt_thongtinnhataitro">Thông tin nhà tài trợ</a>
                                <?php
                                }
                                else {
                                ?>
                                <div class="block_timer left txt_666" id="clockMobile"></div>
                                <?php
                                }
                                ?>
                                <a href="#" class="img_arrow_timer">&nbsp;</a>
                            </div>
                            <div class="block_show_breakumb" style="display: none;">
                                <ul>                                    
                                    <?php
                                    foreach ($this->arrMenu as $menu)
                                    {
                                        if ($menu['cate_type'] != 1 || !$menu['show_folder']
                                                || $menu['catecode'] == 'lich-thi-dau')
                                        {
                                            continue;
                                        }
                                        if ($menu['category_id'] == CATE_ID_VIDEO)
                                        {
                                            $menu['link'] = 'http://video.vnexpress.net/the-thao';
                                        }
                                        ?>
                                        <li><a href="<?php echo $menu['link']; ?>"><?php echo $menu['catename']; ?></a></li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                        <?php echo $this->layout()->content;?>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div id="wrapper_footer">
                <div class="go_head">
                    <div class="right">
                        <a href="javascript:;" id="aSetHomePage" class="sethomepage" style="display: none;"><span class="icon_responsive ico_respone_01">&nbsp;</span>Đặt VnExpress làm trang chủ</a>
                        <a href="javascript:;" id="aSetHomePageIE" onclick="thethao.setHomepage();"><span class="icon_responsive ico_respone_01">&nbsp;</span>Đặt VnExpress làm trang chủ</a>
                        <a onclick="return common.scrollToTop();" href="#"><span class="icon_responsive ico_respone_02">&nbsp;</span>Về đầu trang</a>
                    </div>
                    <div class="clear">&nbsp;</div>
                </div>
                <div id="footer">
                    <div class="footerMenu">
                        <div class="lineFmenu">
                            <ul class="ulBlockMenu ulMainMenu">
                                <li class="liFirst"><h2><a class="mnu_thoisu" href="<?php echo $this->configView['url_vne']; ?>">Trang chủ</a></h2></li>
                                <li class="liFirst"><h2><a class="mnu_thoisu" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/thoi-su">Thời sự</a></h2></li>
                                <li class="liFirst"><h2><a class="mnu_gocnhin" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/goc-nhin">Góc nhìn</a></h2></li>
                                <li class="liFirst"><h2><a class="mnu_video" href="http://video.vnexpress.net">Video</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst"><h2><a class="mnu_giaoduc" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/giao-duc">Giáo dục</a></h2></li>
                                <li class="liFirst"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi" class="mnu_thegioi">Thế giới</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi/tu-lieu">Tư liệu</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi/phan-tich">Phân tích</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi/nguoi-viet-5-chau">Người Việt 5 châu</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst business"><h2><a class="mnu_kinhdoanh" href="<?php echo $this->configView['url_kdo']; ?>">Kinh doanh</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_kdo']; ?>/tin-tuc/hang-hoa">Hàng hóa</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_kdo']; ?>/tin-tuc/doanh-nghiep">Doanh nghiệp</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_kdo']; ?>/tin-tuc/ebank">Ebank</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst entertainment"><h2><a class="mnu_giaitri" href="<?php echo $this->configView['url_gti']; ?>">Giải trí</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_gti']; ?>/tin-tuc/gioi-sao">Giới sao</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_gti']; ?>/tin-tuc/thoi-trang">Thời trang</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_gti']; ?>/tin-tuc/phim">Phim</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst sporting"><h2><a class="mnu_thethao" href="/">Thể thao</a></h2></li>
                                <li class="liFollow"><h2><a href="/tin-tuc/bong-da">Bóng đá</a></h2></li>
                                <li class="liFollow"><h2><a href="/tin-tuc/tennis">Tennis</a></h2></li>
                                <li class="liFollow"><h2><a href="/tin-tuc/cac-mon-khac">Các môn khác</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst"><h2><a class="mnu_doisong" href="<?php echo $this->configView['url_dso']; ?>">Gia đình</a></h2></li>
                                <li class="liFirst"><h2><a class="mnu_phapluat" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat">Pháp luật</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat/ho-so-pha-an">Hồ sơ phá án</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat/tu-van">Tư vấn</a></h2></li>
                            </ul>
                        </div>
                        <div class="lineFmenu">
                            <ul class="ulBlockMenu">
                                <li class="liFirst"><h2><a class="mnu_suckhoe" href="<?php echo $this->configView['url_skh']; ?>">Sức khỏe</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_skh']; ?>/tin-tuc/cac-benh">Các bệnh</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_skh']; ?>/tin-tuc/khoe-dep">Khỏe đẹp</a></h2></li>
                                <li class="liFollow"><h2><a href="<?php echo $this->configView['url_skh']; ?>/tin-tuc/dinh-duong">Dinh dưỡng</a></h2></li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst dulich">
                                    <h2><a class="mnu_dulich" href="<?php echo $this->configView['url_dli']; ?>">Du lịch</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_dli']; ?>/tin-tuc/viet-nam">Việt Nam</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_dli']; ?>/tin-tuc/quoc-te">Quốc tế</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_dli']; ?>/tin-tuc/cong-dong">Cộng đồng</a></h2>
                                </li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst">
                                    <h2><a class="mnu_khoahoc" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc">Khoa học</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc/moi-truong">Môi trường</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc/ky-thuat-moi">Công nghệ mới</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc/hoi-dap">Hỏi - Đáp</a></h2>
                                </li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst digitizing">
                                    <h2><a class="mnu_sohoa" href="<?php echo $this->configView['url_sho']; ?>">Số hóa</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_sho']; ?>/tin-tuc/san-pham">Sản phẩm</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_sho']; ?>/danh-gia">Đánh giá</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_sho']; ?>/tin-tuc/doi-song-so">Đời sống số</a></h2>
                                </li>
                            </ul>
                            <ul class="ulBlockMenu">
                                <li class="liFirst">
                                    <h2><a class="mnu_xe" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may">Xe</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may/tu-van">Tư vấn</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may/thi-truong">Thị trường</a></h2>
                                </li>
                                <li class="liFollow">
                                    <h2><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may/dien-dan">Diễn đàn</a></h2>
                                </li>
                            </ul>
                            <ul class="ulBlockMenu ulMainMenu">
                                <li class="liFirst">
                                    <h2><a class="mnu_bandoc" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cong-dong">Cộng đồng</a></h2>
                                </li>
                                <li class="liFirst">
                                    <h2><a class="mnu_tamsu" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/tam-su">Tâm sự</a></h2>
                                </li>
                                <li class="liFirst">
                                    <h2><a class="mnu_cuoi" href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cuoi">Cười</a></h2>
                                </li>
                                <li class="liFirst">
                                    <h2><a class="mnu_raovat" href="http://raovat.vnexpress.net">Rao vặt</a></h2>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <ul class="list_menu_small">
                        <li><a href="<?php echo $this->configView['url_vne']; ?>">Trang chủ</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/thoi-su">Thời sự</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/goc-nhin">Góc nhìn</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/the-gioi">Thế giới</a></li>
                        <li><a href="<?php echo $this->configView['url_kdo']; ?>">Kinh doanh</a></li>
                        <li><a href="<?php echo $this->configView['url_gti']; ?>">Giải trí</a></li>
                        <li><a href="/">Thể thao</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/phap-luat">Pháp luật</a></li>
                        <li><a href="<?php echo $this->configView['url_dso']; ?>">Giáo dục</a></li>
                        <li><a href="<?php echo $this->configView['url_skh']; ?>">Sức khỏe</a></li>
                        <li><a href="<?php echo $this->configView['url_dso']; ?>">Gia đình</a></li>
                        <li><a href="<?php echo $this->configView['url_dli']; ?>">Du lịch</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/khoa-hoc">Khoa học</a></li>
                        <li><a href="<?php echo $this->configView['url_sho']; ?>">Số hóa</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/oto-xe-may">Xe</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cong-dong">Cộng đồng</a></li>
                        <li><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/tam-su">Tâm sự</a></li>
                        <li class="end"><a href="http://video.vnexpress.net">Video</a></li>
                        <li class="end"><a href="<?php echo $this->configView['url_vne']; ?>/tin-tuc/cuoi">Cười</a></li>
                        <li class="end"><a href="http://raovat.vnexpress.net">Rao vặt</a></li>
                    </ul>
                    <div class="ft-bot">
                        <div class="ft-botl">
                            <a href="<?php echo $this->configView['url_vne']; ?>" title="vnexpress.net"><img src="<?php echo $this->configView['images']; ?>/graphics/img_logo_vne.jpg" alt="vnexpress.net" /></a>
                        </div>
                        <div class="ft-botm txt_666">
                            <p>&copy; <span>Copyright 1997 VnExpress.net,</span>  All rights reserved.</p>
                            <p>&reg; VnExpress giữ bản quyền nội dung trên website này.</p>
                        </div>
                        <div class="ft-botr">
                            <p><a href="http://vnexpress.net/tuyen-dung.html">VnExpress tuyển dụng</a> <a href="<?php echo $this->configView['url_vne']; ?>/lien-he-quang-cao/">Liên hệ quảng cáo</a> / <a href="<?php echo $this->configView['url_vne']; ?>/lien-he-toa-soan/?p=thethao">Liên hệ Tòa soạn</a></p>
                            <p><a href="<?php echo $this->configView['url_vne']; ?>/contact.htm" target="_blank" style="color: #686E7A;font: 11px arial;padding: 0 4px;text-decoration: none;">Thông tin Tòa soạn.</a> <span>0123.888.0123</span> (HN) - <span>0129.233.3555</span> (TP HCM)</p>
                        </div>
                        <div class="coppy_right_small">
                            <div class="tttoasoan">
                                <div class="txt_up width_common">
                                    <div class="width_50 "><a href="<?php echo $this->configView['url_vne']; ?>/lien-he-toa-soan/?p=thethao"><img src="<?php echo $this->configView['images']; ?>/icons/hotline.gif" alt="" />Liên hệ Toà soạn</a></div>
                                    <div class="width_50"><a href="<?php echo $this->configView['url_vne']; ?>/contact.htm" target="_blank"><img src="<?php echo $this->configView['images']; ?>/icons/icon_thongtintoasoan.gif" alt="" />Thông tin Toà soạn</a></div>
                                </div>
                                <div class="txt_down width_common">
                                    <div class="width_50 "><b>0123.888.0123</b> (HN) </div>
                                    <div class="width_50"><b>0129.233.3555</b> (TP HCM)</div>
                                </div>
                            </div>
                            <div class="coppy_right">
                                <p>&copy; <span>Copyright 1997 VnExpress.net,</span>  All rights reserved.</p>
                                <p>&reg; VnExpress giữ bản quyền nội dung trên website này.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="block_close_menu">&nbsp;</div>
        </div>
        <a href="javascript:;" id="to_top"><img src="<?php echo $this->configView['vnecdn']['images']; ?>/icons/icon_gototop.png" alt="totop"/></a>
		<div class="clear"></div>
        <?php
        $pageFolder = ($this->intCategoryId > 0 ? $this->intCategoryId : SITE_ID);
        ?>
        <script type="text/javascript">
            var PageHot = <?php echo $this->isArticleHotVnE ? 1 : 0; ?>,
                PAGE_FOLDER = <?php echo $this->isArticleHotVnE ? '20000' : $pageFolder; ?>,
                PAGE_DETAIL = <?php echo isset($this->intArticleId) ? 1 : 0 ?>;
            $(function(){
                if(typeof(Parser) != "undefined"){
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
        </script>
        <?php
        echo $this->headScript();
        ?>
        <script src="<?php echo $this->configView['js']; ?>/thethao.js"></script>
        <script async="true" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/cmt.widget.js"></script>
        <script src="<?php echo $this->configView['myvne']['js']; ?>/myvne_users.js"></script>
        <script src="<?php echo $this->configView['myvne']['js']; ?>/plugins/vne.js"></script>
        <script src="<?php echo $this->configView['polyads']['core']; ?>/Ads.js"></script>
        <?php
        if ($this->isArticleHotVnE)
        {
            ?>
            <script src="<?php echo $this->configView['polyads']['url'], '/Vals/1/0/20000/Val.js'; ?>"></script>
            <script src="<?php echo $this->configView['polyads']['url'], '/Vals/46/0/20000/Val.js'; ?>"></script>
            <?php
        }
        else {
            ?>
            <script src="<?php echo $this->configView['polyads']['url'], '/Vals/50/0/', $pageFolder, '/Val.js'; ?>"></script>
            <?php
        }
        ?>
        <script type="text/javascript">
            try {Poly_showads();}catch(ex){};
			$(document).ready(function() {
				<?php
                if ($_SERVER['HTTP_HOST'] == 'demo.thethao.vnexpress.net')
                {
                    ?>
                    var serverHostName = window.location.hostname == 'demo.thethao.vnexpress.net' ? 'demo.' : '';
                    if (serverHostName == 'demo.') {
                        $('a').each(function(){
                            var value1 = $(this).attr('href');
                            if (typeof (value1) != 'undefined'){
                                if (value1.indexOf('ione.vnexpress.net') < 0 && value1.indexOf('raovat.vnexpress.net') < 0 && value1.indexOf('vnexpress.net') > 0 && value1.indexOf(serverHostName) < 0) {
                                    var new_val = value1.replace('http://', 'http://' + serverHostName);
                                    $(this).attr('href', new_val);
                                }
                            }
                        });
                    }
                    <?php
                }
                ?>
            });
        </script>
        <script id="image_load_ajax" type="text/x-handlebars-template">
            <div style="text-align: center;"><p style="padding: 25px 0;"><img src="<?php echo $this->configView['images'] . '/graphics/icon-loading.gif'; ?>"></p></div>
        </script>
    </body>
</html>