<a class="btn_facebook" rel="nofollow" href="javascript:;" title="Chia sẻ bài viết lên facebook">
    <img alt="Chia sẻ bài viết lên facebook" src="<?php echo $this->configView['images']; ?>/graphics/icon_fb.gif" />
</a>
<a class="btn_twitter" rel="nofollow" href="javascript:;" id="twitter" data-url="<?php echo $this->arrArticleDetail['share_url']; ?>" title="Chia sẻ bài viết lên twitter">
    <img alt="Chia sẻ bài viết lên twitter" src="<?php echo $this->configView['images']; ?>/graphics/icon_tw.gif" />
</a>
<a class="btn_google" rel="nofollow" href="javascript:;" title="Chia sẻ bài viết lên google+">
    <img alt="Chia sẻ bài viết lên google+" src="<?php echo $this->configView['images']; ?>/graphics/icon_google.gif" />
</a>
<span class="drash_share">|</span>
<a rel="nofollow" href="javascript:;" onclick="common.printContent();" title="Print"><img alt="Print" src="<?php echo $this->configView['images']; ?>/graphics/icon_print.gif" alt="Gửi mail cho bạn bè" /></a>
<a rel="nofollow" href="javascript:;" class="login_5" title="Email"><img alt="Email" src="<?php echo $this->configView['images']; ?>/graphics/icon_letter.gif" alt="In bài viết này" /></a>