<div id="thongbao_infor_popup" style="display:none;">
    <div class="lightbox-content01">
        <!--Begin Inform-->
        <div class="main_box_vipham">
            <div class="box_suscess">
                <div class="main_content_suscess">
                    <p class="txt_center" id="postContent"><b>Vui lòng nhập đầy đủ thông tin trong form</b></p>
                </div>
                <div id="btn_close" class="txt_bottom txt_note txt_center">
                    <input id="bt_close_empty_comment_from" type="button" value="Đóng" class="btn_finish">
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
        <!--End Inform-->
    </div>
</div>
<link href="<?php echo $this->configView['css']; ?>/lightbox/lightbox.css" media="screen" rel="stylesheet" type="text/css" />