<!DOCTYPE html>
<html>
    <head>
        <link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

        <!-- InstanceBeginEditable name="doctitle" -->
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php
        $tt_category_id = isset($this->intCategoryId) ? $this->intCategoryId : SEA_GAMES;
        $tt_article_id  = isset($this->intArticleId) ? $this->intArticleId : $tt_category_id;
        ?>
        <meta name="tt_category_id" content="<?php echo $tt_category_id; ?>" />
        <meta name="tt_article_id" content="<?php echo $tt_article_id; ?>" />
        <meta name="tt_site_id" content="<?php echo SITE_ID; ?>" />
        <!-- CSS -->
        <link rel="stylesheet" href="<?php echo $this->configView['vnecdn']['css']; ?>/mgeneral.css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->configView['css']; ?>/mseagame.css" media="all" />
        <?php echo $this->headLink(); ?>
        <!-- JS -->
        <script type="text/javascript">
            var site_id = <?php echo SITE_ID; ?>;
            var img_url = '<?php echo $this->configView['images']; ?>';
            var css_url = '<?php echo $this->configView['css']; ?>';
            var base_url = '<?php echo $this->configView['url']; ?>';
            var device_env = <?php echo DEVICE_ENV; ?>;
            var article_id = <?php echo isset($this->intArticleId) ? $this->intArticleId : 0; ?>;
            var vne_url = '<?php echo $this->configView['url_vne']; ?>';
            var interactions_url = '<?php echo $this->configView['comment']; ?>';
            var predict_with_captcha = <?php echo ACTIVE_CAPCHA; ?>;
            document.domain = '<?php echo DOMAIN_VNE ?>';
            var application_env = '<?php echo APPLICATION_ENV; ?>';
        </script>
        <!-- JS -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['libs']; ?>/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/interactions/parser_v3.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->configView['vnecdn']['js']; ?>/utils/mutils.js"></script>

        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
            /*GA - Tracking pageview*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-249346-5']);
            _gaq.push(['_setDomainName', 'vnexpress.net']);
            _gaq.push(['_trackPageview']);

            _gaq.push(['a._setAccount', 'UA-249346-18']);
            _gaq.push(['a._trackPageview']);

            _gaq.push(['b._setAccount', 'UA-249346-37']);
            _gaq.push(['b._trackPageview']);

            _gaq.push(['c._setAccount', 'UA-29374284-26']);
            _gaq.push(['c._trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

            var _siteId="11";
            (function(){
                var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="http://st.l.a.eclick.vn/ea.js";
                var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)
            })();
        </script>
    </head>
    <body>
        <div>
            <div id="wrapper_page">
                <div id="wrapper_container">
                    <div id="container">
                    <div class="line_page width_common">
                    <div id="col_left">
                    <div class="block_2mid_col line_mid_col width_common">
                    <div id="block_folder_detail" class="block_two_col_mid width_common block_two_col_folder">
                    <div id="box_details_news" class="block_col_mid_common block_col_mid_folder">
                    <div class="main_content_detail width_common">
                    <div class="div-fbook width_common title_div_fbook">
                        <div class="block_timer left txt_666"><?php echo $this->DateTimeFormat($this->arrArticleDetail['publish_time'], 'long'); ?></div>
                    </div>
                    <div class="title_news">
                        <h1><?php echo $this->arrArticleDetail['title']; ?></h1>
                    </div>
                    <div class="short_intro txt_666">
                        <?php echo $this->arrArticleDetail['lead']; ?>
                    </div>
                    <?php
                    if (!empty($this->arrArticleDetail['reference_detail'])) {
                        $arrRef = array();
                        foreach ($this->arrArticleDetail['reference_detail'] as $reference) {
                            $reference['share_url'] = $this->ShareurlSeagame($reference['share_url']);
                            $arrRef[] = '<a class="txt_666 txt_11" alt="' . $reference['title_format'] . '" title="' . $reference['title_format'] . '" href="' . $this->ShareurlSeagame($reference['share_url']) . '">' . $reference['title'] . '</a>';
                        }
                        ?>
                        <div class="relative_new">
                            <p>
                                <b>
                                    <span class="icon_tinlienquan">&nbsp;</span>
                                    <?php
                                    echo implode(' / ', $arrRef);
                                    ?>
                                </b>
                            </p>
                        </div>
                    <?php
                    }
                    ?>
                    <div class="fck_detail width_common">
                        <?php echo $this->arrArticleDetail['content']; ?>
                    </div>
                    <script type="text/javascript">
                        if(typeof(Parser) != "undefined"){
                            Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                            Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                            Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                            Parser.SITE_ID = <?php echo SITE_ID; ?>;
                            Parser.AUTO_PLAY = 1;
                            Parser.parseAll();
                        }
                        if (typeof(common.parserAdsFullScreen) != 'undefined') {
                            common.parserAdsFullScreen();
                        }
                        if (typeof(common.resizeImageDetail) != 'undefined') {
                            common.resizeImageDetail();
                            $(window).resize(function() {
                                common.delayFireOnce(1000).done(function() {
                                    common.resizeImageDetail();
                                });
                            });
                        }
                    </script>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <div class="clear"></div>
        <script type="text/javascript">
            var timeTemp = '<?php echo time(); ?>';
            //document ready
            $(function() {
                //Show parser
                if (typeof (Parser) != "undefined") {
                    Parser.SITE_URL = "<?php echo $this->configView['url_vne']; ?>";
                    Parser.URL = "<?php echo $this->configView['vnecdn']['js']; ?>";
                    Parser.FLASH_URL = "<?php echo $this->configView['flash']; ?>";
                    Parser.SITE_ID = <?php echo SITE_ID; ?>;
                    Parser.AUTO_PLAY = 1;
                    Parser.parseAll();
                }
            });
        </script>

    </body>
</html>