<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
    $arrData = $this->arrData;
?>
<title><?php echo $arrData['title_format']; ?></title>
<link type="image/x-icon" href="<?php echo $this->configView['images']; ?>/favicon.ico" rel="shortcut icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='<?php echo $this->configView['vnecdn']['css']; ?>/general.css' media='screen' rel='stylesheet' type='text/css' />
<link href='<?php echo $this->configView['css']; ?>/print.css' media='screen' rel='stylesheet' type='text/css' />
</head>
<body>
  <div id="print_page">
    <div class="header_page">
      <div class="header_left_logo left">
        <a href="<?php echo $this->configView['url_vne']; ?>" title="VnExpress"><img src="<?php echo $this->configView['images']; ?>/graphics/img_logo_vne_web.gif" alt="vnexpress logo"></a>
      </div>
      <div class="header_right_print right">
          <a href="javascript:;" onclick="return window.print();" title="In trang"><img src="<?php echo $this->configView['images']; ?>/graphics/icon_print.gif"><span>In trang</span> (Ctr + P)</a>
      </div>
    </div>
    <div id="detail_page" class="width_common line_col">
            <div class="box_width_common" id="box_details_news">
              <div class="w670 left">
                <div class="main_content_detail width_common">
                	<div class="block_timer_share">
                    	<div class="block_timer left txt_666">
                            <?php echo $this->DateTimeFormat($arrData['publish_time'], 'long'); ?>
                        </div>
                    </div>
                	<div class="title_news">
                         <h1><?php echo $arrData['title_format']; ?></h1>
                    </div>
                	<div class="short_intro txt_666"><?php echo $arrData['lead']; ?></div>
                    <?php if ($this->type == TYPE_PHOTO)
                    {
                        ?>
                        <div class="width_common space_bottom_20">
                            <div class="block_content_slide_showdetail">
                                <?php
                                if (!empty($this->arrPhoto))
                                {
                                    foreach ($this->arrPhoto as $photo)
                                    {
                                        $captionCheck   = trim(strip_tags($photo['caption']));
                                        $captionCheck   = !empty($captionCheck);
                                        ?>
                                        <div class="item_slide_show">
                                            <div class="block_thumb_slide_show">
                                                <img src="<?php echo $this->ImageurlArticle($photo, 'size3', -1); ?>" alt="" class="left" />
                                            </div>
                                            <?php
                                            if($captionCheck)
                                            {
                                            ?>
                                            <div class="desc_cation"><?php echo $photo['caption']; ?></div>
                                            <?php
                                            }//end if
                                            else
                                            {
                                            ?>
                                            <div class="clear">&nbsp;</div>
                                            <?php
                                            }
                                            ?>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                <div class="fck_detail width_common"><?php echo $arrData['content']; ?></div>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </div>
                        <?php
                    }
                    else
                    {
                        ?>
                        <div class="width_common space_bottom_20">
                            <div class="block_col_480">
                                <div class="fck_detail width_common"><?php echo $arrData['content']; ?></div>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </div>
                        <?php
                    }
                    ?>
                </div>
              </div>
            </div>
        </div>
  </div>
</body>
</html>