<?php
$arrDetailMatch = $this->arrDetailMatch;
$arrDate = $this->arrDate;
$objTeam = $this->objObject->getTeam();
?>
<div class="width_common box m_sub_guess space_box" id="vong16" style="display:none;">
    <div class="title">Vòng 1/8</div>
    <?php
    if (count($arrDetailMatch['vong_16']) == 8)
    {
        $j = 0;
        $i = 49;
        foreach ($arrDate['vong_16'] as $arrVong16)
        {
            $arrData = array_slice($arrDetailMatch['vong_16'], $j, $arrVong16);
            ?>
            <table class="width_common m_none space_box">
                <caption id="<?php echo date("dmY", $arrData[0]['datetime_happen']); ?>"><?php echo $this->DateTimeFormat($arrData[0]['datetime_happen'], 'long_fixture'); ?></caption>
                <?php
                $l = 1;
                foreach ($arrData as $data)
                {
                    $objTeam->setId(array($data['team1'], $data['team2']));
                    $team1 = $objTeam->getDetailObjectBasic($data['team1']);
                    $team2 = $objTeam->getDetailObjectBasic($data['team2']);
                    $title = Fpt_Filter::setSeoLink('tran-' . $team1['name'] . ' vs ' . $team2['name']);
                    if ($data['status'] == 2 || $this->currTime > $data['datetime_happen'])
                    {
                        ?>
                        <tbody <?php echo $l == $arrVong16 ? 'class="last"' : ''; ?>>
                            <tr class="m_time">
                                <td></td>
                                <td>FT</td>
                                <td></td>
                            </tr>
                            <tr class="m_time">
                                <td colspan="3" style="border-bottom:none;">
                                    <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                                </td>
                            </tr>
                            <tr class="m_info">
                                <td class="m_team_a">
                                    <span class="m_board"><?php echo $i; ?></span>
                                    <div class="m_team">
                                        <a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><img width="41" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>"></a>
                                        <span><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><?php echo $team1['name']; ?></a></span>
                                    </div>
                                </td>
                                <td class="m_score">
                                    <?php
                                    echo $data['goal1'] . ' - ' . $data['goal2'];
                                    if($data['penalty1'] > 0 || $data['penalty2'] > 0)
                                    {
                                    ?>
                                        <p class="txt_11">penalty</p>
                                        <p class="txt_11" style="color:red">(<?php echo $data['penalty1'],' - ', $data['penalty2'] ;?>)</p>
                                    <?php
                                    }
                                    else if((int)$data['matchTime'] > 119) {
                                        echo '<p class="txt_11">(Sau 120\')</p>';
                                    }
                                    ?>
                                </td>
                                <td class="m_team_b">
                                    <div class="m_team">
                                        <a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><img width="41" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>"></a>
                                        <span><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><?php echo $team2['name']; ?></a></span>
                                    </div>
                                    <a class="m_btn_next ico" href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>"></a>
                                </td>
                            </tr>
                        </tbody>
                        <?php
                    }
                    elseif ($data['status'] == 1 && $this->currTime < $data['datetime_happen'])
                    {
                        ?>
                        <tbody <?php echo $l == $arrVong16 ? 'class="last"' : ''; ?>>
                            <tr class="m_time">
                                <td></td>
                                <td><?php echo date('H:i', $data['datetime_happen']); ?></td>
                                <td></td>
                            </tr>
                            <tr class="m_time">
                                <td colspan="3" style="border-bottom:none;">
                                    <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                                </td>
                            </tr>
                            <tr class="m_info">
                                <td class="m_team_a">
                                    <span class="m_board"><?php echo $i; ?></span>
                                    <div class="m_team">
                                        <?php
                                        if (!empty($team1['thumbnail']))
                                        {
                                        ?>
                                        <a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>">
                                            <img width="41" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                        </a>
                                        <?php
                                        }
                                        ?>
                                        <p><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><?php echo $team1['name']; ?></a></p>
                                    </div>
                                </td>
                                <td class="m_score"><input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team1" data-match-id="<?php echo $data['id']; ?>"> - <input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team2" data-match-id="<?php echo $data['id']; ?>"></td>
                                <td class="m_team_b">
                                    <div class="m_team">
                                        <?php
                                        if (!empty($team2['thumbnail']))
                                        {
                                        ?>
                                        <a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><img width="41" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>"></a>
                                        <?php
                                        }
                                        ?>
                                        <p><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><?php echo $team2['name']; ?></a></p>
                                    </div>
                                    <a class="m_btn_next ico" href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>"></a>
                                </td>
                            </tr>
                            <tr class="no_border collapse collapse_2 class_match_<?php echo $data['id']; ?>" style="display:none;">
                                <td colspan="3" class="text_center">
                                    <a href="javascript:;" class="txt_icon_arrow_up btn_guess_2 btn_collapse" title="Dự đoán của bạn" data-match-id="<?php echo $data['id']; ?>">Dự đoán của bạn<i class="ico"></i></a>
                                </td>
                            </tr>
                            <tr class="m_guess collapse collapse_2 class_match_<?php echo $data['id']; ?> noborder" style="display:none;">
                                <td colspan="3" class="text_center">
                                    <div class="m_btn_gr">
                                        <a href="javascript:;" class="btn green predict-match" data-rel="<?php echo $data['id']; ?>" data-predict-type="6" data-time="<?php echo $data['matchTime']; ?>" data-predict-text="<?php echo $team1['name']; ?> vs <?php echo $team2['name']; ?>" onclick="_gaq.push(['_trackEvent', 'Trang Lịch thi đấu World Cup', 'Click button Gửi trong box', 'Box Dự đoán']);">Gửi</a>
                                        <a href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>" class="btn gray">Gợi ý <i class="ico"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                        <?php
                    }
                    else
                    {
                        ?>
                        <tbody <?php echo $l == $arrVong16 ? 'class="last"' : ''; ?>>
                            <tr class="m_time">
                                <td></td>
                                <td>
                                    <?php
                                    $text = '';
                                    switch ((int)$data['status'])
                                    {
                                        case 4:
                                            $text = 'Hết hiệp 1';
                                            break;
                                        case 6:
                                            $text = 'Hết hiệp 2';
                                            break;
                                        case 8:
                                            $text = 'Hết hiệp phụ thứ nhất';
                                            break;
                                        case 10:
                                            $text = 'Hết hiệp phụ thứ hai';
                                            break;
                                        case 11:
                                            $text = 'Penalty';
                                            break;
                                        default:
                                            $text = $data['matchTime'] . "'";
                                            break;
                                    }
                                    echo $text;
                                    ?>
                                </td>
                                <td></td>
                            </tr>
                            <tr class="m_time">
                                <td colspan="3" style="border-bottom:none;">
                                    <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                                </td>
                            </tr>
                            <tr class="m_info">
                                <td class="m_team_a">
                                    <span class="m_board"><?php echo $i; ?></span>
                                    <div class="m_team">
                                        <a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><img width="41" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>"></a>
                                        <p><a href="<?php echo $this->ShareurlWorldcup($team1['share_url']); ?>" title="<?php echo $team1['name_format']; ?>"><?php echo $team1['name']; ?></a></p>
                                    </div>
                                </td>

                                <td class="m_score"><?php echo $data['goal1'] . ' - ' . $data['goal2']; ?></td>
                                <td class="m_team_b">
                                    <div class="m_team">
                                        <a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><img width="41" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>"></a>
                                        <p><a href="<?php echo $this->ShareurlWorldcup($team2['share_url']); ?>" title="<?php echo $team2['name_format']; ?>"><?php echo $team2['name']; ?></a></p>
                                    </div>
                                    <a class="m_btn_next ico" href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>"></a>
                                </td>
                            </tr>
                            <?php
                            $arrDetailMatchExtendScorecard = $data['scoreCard'];
                            $arrGoal = array();
                            $arrCard = array();
                            $arrSubs = array();
                            if (!empty($arrDetailMatchExtendScorecard))
                            {
                                foreach ($arrDetailMatchExtendScorecard as $key => $value)
                                {
                                    if (isset($value['score']))
                                    {
                                        foreach ($value['score'] as $score)
                                        {
                                            $arrGoal[$score['!scoreType']][$score['!teamId']][] = $score['Name'] . ' '. $key;
                                        }
                                    }
                                    if (isset($value['card']))
                                    {
                                        foreach ($value['card'] as $card)
                                        {
                                            $arrCard[$card['!cardType']][$card['!teamId']][] = $card['Name'] . ' '. $key;
                                        }
                                    }
                                    if ($value['substitution'])
                                    {
                                        foreach ($value['substitution'] as $substitution)
                                        {
                                            foreach ($substitution['substitution'] as $player)
                                            {
                                                if(!empty($player['Player'][0]['Name']))
                                                {
                                                    $arrSubs[$substitution['!teamId']][] = $player['Player'][0]['Name'] . ' - ' . '<span class="text_999">'.$player['Player'][1]['Name'].'</span>' . ' ' .$key;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if (isset($arrGoal) && !empty($arrGoal))
                            {
                                foreach ($arrGoal as $goalType => $goal)
                                {
                                    ?>
                                    <tr class="goal">
                                        <td colspan="3" class="text_right"><?php echo implode(', ', $goal[$data['team1']]); ?></td>
                                        <td class="text_center">
                                            <img src="<?php echo $this->configView['images']; ?>/icons/<?php echo $goalType; ?>.png" alt="">
                                        </td>
                                        <td><?php echo implode(', ', $goal[$data['team2']]); ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            if (isset($arrCard) && !empty($arrCard))
                            {
                                foreach ($arrCard as $cardType => $card)
                                {
                                    ?>
                                    <tr class="ticket">
                                        <td colspan="3" class="text_right">
                                            <?php
                                            if (isset($arrSubs[$data['team1']])) {
                                                echo implode(', ', $arrSubs[$data['team1']]);
                                            }
                                            ?>
                                        </td>
                                        <td class="text_center">
                                            <img src="<?php echo $this->configView['images']; ?>/icons/<?php echo $cardType; ?>.png" alt="">
                                        </td>
                                        <td>
                                            <?php
                                            if (isset($arrSubs[$data['team2']])) {
                                                echo implode(', ', $arrSubs[$data['team2']]);
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            }
                            if (isset($arrSubs) && !empty($arrSubs))
                            {
                                ?>
                                <tr class="ticket">
                                    <td colspan="3" class="text_right"><?php echo implode(', ', $arrSubs[$data['team1']]); ?></td>
                                    <td class="text_center">
                                        <img src="<?php echo $this->configView['images']; ?>/icons/in_out.png" alt="">
                                    </td>
                                    <td><?php echo implode(', ', $arrSubs[$data['team2']]); ?></td>
                                </tr>
                                <?php

                            }
                            ?>
                            <tr class="noborder">
                                <td colspan="3" class="text_center"><a href="javascript:;" class="txt_icon_arrow_up btn_guess_2 btn_collapse" title="Dự đoán của bạn" data-match-id="<?php echo $data['id']; ?>">Dự đoán của bạn<i class="ico"></i></a></td>
                            </tr>
                            <tr class="m_guess collapse class_match_<?php echo $data['id']; ?> noborder" style="display:none;">
                                <td colspan="3" class="m_score"><input type="text" class="input_focus_col" data-rel="<?php echo $data['id']; ?>-team1" data-match-id="<?php echo $data['id']; ?>"> - <input type="text" class="input_focus_col" data-rel="<?php echo $data['id']; ?>-team2" data-match-id="<?php echo $data['id']; ?>"></td>
                            </tr>
                            <tr class="m_guess collapse collapse_2 class_match_<?php echo $data['id']; ?> noborder" style="display:none;">
                                <td colspan="3" class="text_center">
                                    <div class="m_btn_gr">
                                        <a href="javascript:;" class="btn green predict-match" data-rel="<?php echo $data['id']; ?>" data-predict-type="6" data-time="<?php echo $data['matchTime']; ?>" data-predict-text="<?php echo $team1['name']; ?> vs <?php echo $team2['name']; ?>" onclick="_gaq.push(['_trackEvent', 'Trang Lịch thi đấu World Cup', 'Click button Gửi trong box', 'Box Dự đoán']);">Gửi</a>
                                        <a href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>" class="btn gray">Gợi ý <i class="ico"></i></a>
                                    </div>
                                </td>
                            </tr>
                            </body>
                            <?php
                        }
                        $i++;
                        $j++;
                        $l++;
                    }
                    ?>
            </table>
            <?php
        }
    }
    else
    {
        ?>
        <table class="width_common m_none space_box">
            <caption id="<?php echo '28062014'; ?>">Thứ bảy, 28/06/2014</caption>
            <tbody class="last">
                <tr class="m_time">
                    <td></td>
                    <td>23:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="1"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">49</span>
                        <div class="m_team">
                            <strong>Nhất bảng A&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng B</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="width_common m_none space_box">
            <caption id="<?php echo '29062014'; ?>">Chủ nhật, 29/06/2014</caption>
            <tbody>
                <tr class="m_time">
                    <td></td>
                    <td>03:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="2"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">50</span>
                        <div class="m_team">
                            <strong>Nhất bảng C&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng D</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
            <tbody class="last">
                <tr class="m_time">
                    <td></td>
                    <td>23:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="3"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">51</span>
                        <div class="m_team">
                            <strong>Nhất bảng B&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng A</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="width_common m_none space_box">
            <caption id="<?php echo '30062014'; ?>">Thứ hai, 30/06/2014</caption>
            <tbody>
                <tr class="m_time">
                    <td></td>
                    <td>03:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="4"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">52</span>
                        <div class="m_team">
                            <strong>Nhất bảng D&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng C</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
            <tbody class="last">
                <tr class="m_time">
                    <td></td>
                    <td>23:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="5"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">53</span>
                        <div class="m_team">
                            <strong>Nhất bảng E&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng F</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="width_common m_none space_box">
            <caption id="<?php echo '01072014'; ?>">Thứ ba, 01/07/2014</caption>
            <tbody>
                <tr class="m_time">
                    <td></td>
                    <td>03:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="6"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">54</span>
                        <div class="m_team">
                            <strong>Nhất bảng G&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng H</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
            <tbody class="last">
                <tr class="m_time">
                    <td></td>
                    <td>23:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="7"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">55</span>
                        <div class="m_team">
                            <strong>Nhất bảng F&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng E</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="width_common m_none space_box">
            <caption id="<?php echo '02072014'; ?>">Thứ tư, 02/07/2014</caption>
            <tbody class="last">
                <tr class="m_time">
                    <td></td>
                    <td>03:00</td>
                    <td></td>
                </tr>
                <tr class="m_time">
                    <td colspan="3" style="border-bottom:none;">
                        <div class="daiphatsong" data-schedule-match="8"></div>
                    </td>
                </tr>
                <tr class="m_info">
                    <td class="m_team_a">
                        <span class="m_board">56</span>
                        <div class="m_team">
                            <strong>Nhất bảng H&nbsp;</strong>
                        </div>
                    </td>
                    <td class="m_score"> - </td>
                    <td class="m_team_b">
                        <div class="m_team">
                            <strong>&nbsp;Nhì bảng G</strong>
                        </div>
                        <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    </td>
                </tr>
            </tbody>
        </table>
        <?php
    }
    ?>
</div>