<div class="board width_common" id="board">
    <div class="title">Sơ đồ thi đấu</div>
    <div class="body">
        <div class="vongloai_vongbang">
            <div class="content active" id="tab_vongloai">
                <div class="round_1_16 width">
                    <div class="title">Vòng 1/8</div>
                    <div class="group_top">
                        <div class="box">
                            <div class="round a">Brazil</div>
                            <div class="date">[49] 28/06</div>
                            <div class="round b">Chile</div>
                        </div>
                        <div class="box">
                            <div class="round a">Colombia</div>
                            <div class="date">[50] 29/06</div>
                            <div class="round b">Uruguay</div>
                        </div>
                    </div>
                    <div class="group_bottom">
                        <div class="box">
                            <div class="round a">France</div>
                            <div class="date">[53] 29/06</div>
                            <div class="round b">Nigeria</div>
                        </div>
                        <div class="box">
                            <div class="round a">Germany</div>
                            <div class="date">[54] 01/07</div>
                            <div class="round b">Algeria</div>
                        </div>
                    </div>
                </div>
                <div class="round_4 width">
                    <div class="title">Tứ kết</div>
                    <div class="group_top">
                        <div class="box">
                            <div class="round a">Brazil<span class="line"></span></div>
                            <div class="date">[58] 05/07</div>
                            <div class="round b">Colombia<span class="line"></span></div>
                        </div>
                    </div>
                    <div class="group_bottom">
                        <div class="box">
                            <div class="round a">France <span class="line"></span></div>
                            <div class="date">[57] 04/07</div>
                            <div class="round b">Germany<span class="line"></span></div>
                        </div>
                    </div>
                </div>

                <div class="round_2 width">
                    <div class="title">Bán kết</div>
                    <div class="box">
                        <div class="round a">Brazil<span class="line"></span></div>
                        <div class="date a">[61] 09/07</div>
                        <div class="date">[61] 09/07</div>
                        <div class="round a">Germany<span class="line"></span></div>
                    </div>
                </div>

                <div class="round_1 width">
                    <div class="title">Chung kết</div>
                    <div class="box">
                        <div class="round a">Germany<span class="line"></span></div>
                        <div class="date">[64] 14/07</div>
                        <div class="round b">Argentina<span class="line right"></span></div>
                    </div>

                    <div class="title giai_3">Tranh giải 3</div>
                    <div class="box">
                        <div class="row a">Brazil</div>
                        <div class="date giai_3">[63] 13/07</div>
                        <div class="row b">Netherlands</div>
                    </div>
                </div>

                <div class="round_2 width right">
                    <div class="title">Bán kết</div>
                    <div class="box">
                        <div class="round a">Argentina<span class="line right"></span></div>
                        <div class="date a">[62] 10/07</div>
                        <div class="date">[62] 10/07</div>
                        <div class="round a">Netherlands<span class="line right"></span></div>
                    </div>
                </div>

                <div class="round_4 width right">
                    <div class="title">Tứ kết</div>
                    <div class="group_top">
                        <div class="box">
                            <div class="round a">Netherlands<span class="line right"></span></div>
                            <div class="date">[60] 06/07</div>
                            <div class="round b">Costa Rica<span class="line right"></span></div>
                        </div>
                    </div>
                    <div class="group_bottom">
                        <div class="box">
                            <div class="round a">Argentina<span class="line right"></span></div>
                            <div class="date">[59] 05/07</div>
                            <div class="round b">Belgum<span class="line right"></span></div>
                        </div>
                    </div>
                </div>
                <div class="round_1_16 width right">
                    <div class="title">Vòng 1/8</div>
                    <div class="group_top">
                        <div class="box">
                            <div class="round a">Netherlands</div>
                            <div class="date">[51] 30/06</div>
                            <div class="round b">Mexico</div>
                        </div>
                        <div class="box">
                            <div class="round a">Costa Rica</div>
                            <div class="date">[52] 30/06</div>
                            <div class="round b">Greece</div>
                        </div>
                    </div>
                    <div class="group_bottom">
                        <div class="box">
                            <div class="round a">Argentina</div>
                            <div class="date">[55] 01/07</div>
                            <div class="round b">Switzerland</div>
                        </div>
                        <div class="box">
                            <div class="round a">Belgum</div>
                            <div class="date">[56] 02/07</div>
                            <div class="round b">USA</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>