<?php
$arrDetailMatch = $this->arrDetailMatch;
$arrDate = $this->arrDate;
$objTeam = $this->objObject->getTeam();
?>
<div class="width_common box sub_guess space_box">
    <div class="title">Vòng 1/8</div>
    <a href="#board" class="ico"></a>
    <?php
    if (count($arrDetailMatch['vong_16']) == 8)
    {
        $j = 0;
        $i = 49;
        foreach ($arrDate['vong_16'] as $arrVong16)
        {
            $arrData = array_slice($arrDetailMatch['vong_16'], $j, $arrVong16);
            ?>
            <table class="width_common">
                <caption id="<?php echo date("dmY", $arrData[0]['datetime_happen']); ?>"><?php echo $this->DateTimeFormat($arrData[0]['datetime_happen'], 'long_fixture'); ?></caption>
                <?php
                foreach ($arrData as $data)
                {
                    $objTeam->setId(array($data['team1'],$data['team2']));
                    $team1 = $objTeam->getDetailObjectBasic($data['team1']);
                    $team2 = $objTeam->getDetailObjectBasic($data['team2']);
                    $title = Fpt_Filter::setSeoLink('tran-' . $team1['name'] . ' vs ' . $team2['name']);
                    if ($data['status'] == 2 || $this->currTime > $data['datetime_happen'])
                    {
                        ?>
                        <tr class="now">
                            <td class="time"><?php echo date('H:i', $data['datetime_happen']); ?></td>
                            <td class="group"><?php echo $i; ?></td>
                            <td class="main_team">
                                <span><?php echo $team1['name']; ?></span>
                                <img width="18" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                            </td>
                            <td class="score">
                                <strong><?php echo $data['goal1'] . ' - ' . $data['goal2']; ?></strong>
                                <?php
                                if($data['penalty1'] > 0 || $data['penalty2'] > 0)
                                {
                                ?>
                                    <p class="txt_11">penalty</p>
                                    <p class="txt_11" style="color:red">(<?php echo $data['penalty1'],' - ', $data['penalty2'] ;?>)</p>
                                <?php
                                }
                                else if((int)$data['matchTime'] > 119) {
                                    echo '<p class="txt_11">(Sau 120\')</p>';
                                }
                                ?>
                            </td>
                            <td class="sub_team">
                                <img width="18" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                <span><?php echo $team2['name']; ?></span>
                                <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>">Chi tiết</a></div>
                                <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                            </td>
                        </tr>
                        <?php
                    }
                    elseif ($data['status'] == 1 && $this->currTime < $data['datetime_happen'])
                    {
                        ?>
                        <tr class="now">
                            <td class="time"><?php echo date('H:i', $data['datetime_happen']); ?></td>
                            <td class="group"><?php echo $i; ?></td>
                            <td class="main_team">
                                <span><?php echo $team1['name']; ?></span>
                                <?php
                                if (!empty($team1['thumbnail']))
                                {
                                ?>
                                <img width="18" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                <?php
                                }
                                ?>
                            </td>
                            <td class="score"><input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team1" data-match-id="<?php echo $data['id']; ?>"> - <input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team2" data-match-id="<?php echo $data['id']; ?>"></td>
                            <td class="sub_team">
                                <?php
                                if (!empty($team2['thumbnail']))
                                {
                                ?>
                                <img width="18" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                <?php
                                }
                                ?>
                                <span><?php echo $team2['name']; ?></span>
                                <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>">Chi tiết</a></div>
                                <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                            </td>
                        </tr>
                        <tr class="no_border collapse collapse_2 class_match_<?php echo $data['id']; ?>">
                            <td colspan="5" class="text_center">
                                <a href="javascript:;" class="txt_icon_arrow_up btn_guess_2 btn_collapse" title="Dự đoán của bạn" data-match-id="<?php echo $data['id']; ?>">Dự đoán của bạn<i class="ico"></i></a>
                            </td>
                        </tr>
                        <tr class="collapse collapse_2 class_match_<?php echo $data['id']; ?>">
                            <td colspan="5" class="text_center">
                                <a href="javascript:;" class="btn green predict-match" data-rel="<?php echo $data['id']; ?>" data-time="<?php echo $data['matchTime']; ?>" data-predict-type="6" data-predict-text="<?php echo $team1['name'], ' vs ', $team2['name']; ?>" onclick="_gaq.push(['_trackEvent', 'Trang Lịch thi đấu World Cup', 'Click button Gửi trong box', 'Box Dự đoán']);">Gửi</a>
                                <a href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>" class="btn gray">Gợi ý <i class="ico"></i></a>
                            </td>
                        </tr>
                        <?php
                    }
                    else
                    {
                        ?>
                        <tbody class="small">
                            <tr class="now">
                                <td class="time">
                                    <?php
                                    $text = '';
                                    switch ((int)$data['status'])
                                    {
                                        case 4:
                                            $text = 'Hết hiệp 1';
                                            break;
                                        case 6:
                                            $text = 'Hết hiệp 2';
                                            break;
                                        case 8:
                                            $text = 'Hết hiệp phụ thứ nhất';
                                            break;
                                        case 10:
                                            $text = 'Hết hiệp phụ thứ hai';
                                            break;
                                        case 11:
                                            $text = 'Penalty';
                                            break;
                                        default:
                                            $text = $data['matchTime'] . "'";
                                            break;
                                    }
                                    echo $text;
                                    ?>
                                </td>
                                <td class="group"><?php echo $i; ?></td>
                                <td class="main_team">
                                    <span><?php echo $team1['name']; ?></span>
                                    <img width="18" src="<?php echo $this->Imageurl($team1['thumbnail'], 'size1'); ?>" alt="<?php echo $team1['name_format']; ?>">
                                </td>
                                <td class="score"><?php echo $data['goal1'] . ' - ' . $data['goal2']; ?></td>
                                <td class="sub_team">
                                    <img width="18" src="<?php echo $this->Imageurl($team2['thumbnail'], 'size1'); ?>" alt="<?php echo $team2['name_format']; ?>">
                                    <span><?php echo $team2['name']; ?></span>
                                    <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'] . "/tuong-thuat/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>">Trực tiếp</a></div>
                                    <div class="daiphatsong" data-schedule-match="<?php echo $data['id']; ?>"></div>
                                </td>
                            </tr>
                            <?php
                            $arrDetailMatchExtendScorecard = $data['scoreCard'];
                            $arrGoal = array();
                            $arrCard = array();
                            $arrSubs = array();
                            if (!empty($arrDetailMatchExtendScorecard))
                            {
                                foreach ($arrDetailMatchExtendScorecard as $key => $value)
                                {
                                    if (isset($value['score']))
                                    {
                                        foreach ($value['score'] as $score)
                                        {
                                            $arrGoal[$score['!scoreType']][$score['!teamId']][] = $score['Name'] . ' '. $key;
                                        }
                                    }
                                    if (isset($value['card']))
                                    {
                                        foreach ($value['card'] as $card)
                                        {
                                            $arrCard[$card['!cardType']][$card['!teamId']][] = $card['Name'] . ' '. $key;
                                        }
                                    }
                                    if ($value['substitution'])
                                    {
                                        foreach ($value['substitution'] as $substitution)
                                        {
                                            foreach ($substitution['substitution'] as $player)
                                            {
                                                if(!empty($player['Player'][0]['Name']))
                                                {
                                                    $arrSubs[$substitution['!teamId']][] = $player['Player'][0]['Name'] . ' - ' . '<span class="text_999">'.$player['Player'][1]['Name'].'</span>' . ' ' .$key;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if (isset($arrGoal) && !empty($arrGoal))
                            {
                                foreach ($arrGoal as $goalType => $goal)
                                {
                                    ?>
                                    <tr class="goal">
                                        <td colspan="3" class="text_right"><?php echo implode(', ', $goal[$data['team1']]); ?></td>
                                        <td class="text_center">
                                            <img src="<?php echo $this->configView['images']; ?>/icons/<?php echo $goalType; ?>.png" alt="">
                                        </td>
                                        <td><?php echo implode(', ', $goal[$data['team2']]); ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            if (isset($arrCard) && !empty($arrCard))
                            {
                                foreach ($arrCard as $cardType => $card)
                                {
                                    ?>
                                    <tr class="ticket">
                                        <td colspan="3" class="text_right"><?php echo implode(', ', $card[$data['team1']]); ?></td>
                                        <td class="text_center">
                                            <img src="<?php echo $this->configView['images']; ?>/icons/<?php echo $cardType; ?>.png" alt="">
                                        </td>
                                        <td><?php echo implode(', ', $card[$data['team2']]); ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            if (isset($arrSubs) && !empty($arrSubs))
                            {
                                ?>
                                <tr class="ticket">
                                    <td colspan="3" class="text_right">
                                        <?php
                                        if (isset($arrSubs[$data['team1']])) {
                                            echo implode(', ', $arrSubs[$data['team1']]);
                                        }
                                        ?>
                                    </td>
                                    <td class="text_center">
                                        <img src="<?php echo $this->configView['images']; ?>/icons/in_out.png" alt="">
                                    </td>
                                    <td>
                                        <?php
                                        if (isset($arrSubs[$data['team2']])) {
                                            echo implode(', ', $arrSubs[$data['team2']]);
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <?php

                            }
                            ?>
                            <tr>
                                <td colspan="5" class="text_center"><a href="javascript:;" class="txt_icon_arrow_up btn_guess_2 btn_collapse" title="Dự đoán của bạn" data-match-id="8801">Dự đoán của bạn<i class="ico"></i></a></td>
                            </tr>
                            <tr class="score collapse class_match_<?php echo $data['id']; ?>"><td colspan="5"><input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team1" data-match-id="<?php echo $data['id']; ?>"> - <input type="text" class="input_focus_col btn_collapse_input" data-rel="<?php echo $data['id']; ?>-team2" data-match-id="<?php echo $data['id']; ?>"></td></tr>
                            <tr class="collapse collapse_2 class_match_<?php echo $data['id']; ?>">
                                <td colspan="5" class="text_center">
                                    <a href="javascript:;" class="btn green predict-match" data-rel="<?php echo $data['id']; ?>" data-predict-type="6" data-time="<?php echo $data['matchTime'];?>" data-predict-text="<?php echo $team1['name']; ?> vs <?php echo $team2['name']; ?>" onclick="_gaq.push(['_trackEvent', 'Trang Lịch thi đấu World Cup', 'Click button Gửi trong box', 'Box Dự đoán']);">Gửi</a>
                                    <a href="<?php echo $this->configView['url'] . "/thong-ke/{$title}-{$data['id']}" ?>" title="Thống kê trận đấu <?php echo $data['name_format']; ?>" class="btn gray">Gợi ý <i class="ico"></i></a>
                                </td>
                            </tr>
                            </body>
                            <?php
                        }
                        ?>
                        <?php
                        $i++;
                        $j++;
                    }
                    ?>
            </table>
            <?php
        }
    }
    else
    {
        ?>
        <table class="width_common">
            <caption id="<?php echo '28062014'; ?>">Thứ bảy, 28/06/2014</caption>
            <tr class="now">
                <td class="time">23:00</td>
                <td class="group">49</td>
                <td class="main_team">
                    <strong>Nhất bảng A&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng B</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="1"></div>

                </td>
            </tr>
        </table>
        <table class="width_common">
            <caption id="<?php echo '29062014'; ?>">Chủ nhật, 29/06/2014</caption>
            <tr class="now">
                <td class="time">03:00</td>
                <td class="group">50</td>
                <td class="main_team">
                    <strong>Nhất bảng C&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng D</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="2"></div>
                </td>
            </tr>
            <tr class="now">
                <td class="time">23:00</td>
                <td class="group">51</td>
                <td class="main_team">
                    <strong>Nhất bảng B&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng A</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="3"></div>
                </td>
            </tr>
        </table>
        <table class="width_common">
            <caption id="<?php echo '30062014'; ?>">Thứ hai, 30/06/2014</caption>
            <tr class="now">
                <td class="time">03:00</td>
                <td class="group">52</td>
                <td class="main_team">
                    <strong>Nhất bảng D&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng C</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="4"></div>
                </td>
            </tr>
            <tr class="now">
                <td class="time">23:00</td>
                <td class="group">53</td>
                <td class="main_team">
                    <strong>Nhất bảng E&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng F</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="5"></div>
                </td>
            </tr>
        </table>
        <table class="width_common">
            <caption id="<?php echo '01072014'; ?>">Thứ ba, 01/07/2014</caption>
            <tr class="now">
                <td class="time">03:00</td>
                <td class="group">54</td>
                <td class="main_team">
                    <strong>Nhất bảng G&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng H</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="6"></div>
                </td>
            </tr>
            <tr class="now">
                <td class="time">23:00</td>
                <td class="group">55</td>
                <td class="main_team">
                    <strong>Nhất bảng F&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng E</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="7"></div>
                </td>
            </tr>
        </table>
        <table class="width_common">
            <caption id="<?php echo '02072014'; ?>">Thứ tư, 02/07/2014</caption>
            <tr class="now">
                <td class="time">03:00</td>
                <td class="group">56</td>
                <td class="main_team">
                    <strong>Nhất bảng H&nbsp;</strong>
                </td>
                <td class="score"> <strong> - </strong></td>
                <td class="sub_team">
                    <strong>&nbsp;Nhì bảng G</strong>
                    <!--<div class="txt_view_more"><a class="txt_666" href="#">Chi tiết</a></div>-->
                    <div class="daiphatsong" data-schedule-match="8"></div>
                </td>
            </tr>
        </table>
        <?php
    }
    ?>
</div>