<div class="line_gray line_page width_common">
    <div id="col_left">
        <?php
        if (!empty($this->arrHotNews))
        {
            ?>
            <div class="width_common" id="box_news_top">
                <div class="line_col_midnews_top line_gray width_common">
                    <?php
                    $idFirstNews = array_shift($this->arrHotNews);
                    $firstNews = $this->objArticle->getArticleBasic($idFirstNews);
                    ?>
                    <div class="box_hot_news">
                        <div class="block_news_big">
                            <a href="<?php echo $this->ShareurlWorldcup($firstNews['share_url']); ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>" class="txt_link">
                                <img src="<?php echo $this->ImageurlArticle($firstNews, 'size2'); ?>" alt="<?php echo $firstNews['title_format']; ?>" title="<?php echo $firstNews['title_format']; ?>" class="width_image_common" />
                            </a>
                            <?php echo $this->ArticleTypeIcon($firstNews); ?>
                        </div>
                        <div class="title_news">
                            <a href="<?php echo $this->ShareurlWorldcup($firstNews['share_url']); ?>" class="txt_link" title="<?php echo $firstNews['title_format']; ?>"><?php echo $firstNews['title']; ?></a>
                            <span class="no_wrap">
                                <?php echo $this->ArticleViewIcon($firstNews['article_icon']); ?>
                                <?php echo $this->ArticleComment($firstNews); ?>
                            </span>
                        </div>
                        <div class="news_lead">
                            <?php echo $this->CropWord($firstNews['lead'], 30, $this->ShareurlWorldcup($firstNews['share_url'])); ?>
                        </div>
                        <?php
                        if (sizeof($firstNews['reference_detail']) > 0)
                        {
                            $i = 1;
                            $arrRef = '';
                            foreach ($firstNews['reference_detail'] as $reference)
                            {
                                if ($i > 1)
                                {
                                    break;
                                }
                                $arrRef = '<a href="' . $this->ShareurlWorldcup($reference['share_url']) . '" title="' . $reference['title_format'] . '" alt="' . $reference['title_format'] . '">' . $reference['title'] . '</a>';
                                $i++;
                            }
                            ?>
                            <ul class="list_news_dot_3x3_300">
                                <li>
                                    <p>
        <?php echo $arrRef; ?>
                                    </p>
                                </li>
                            </ul>
                            <?php
                            unset($arrRef);
                        }
                        //icon tai tro
                        echo $this->IconCommercial($firstNews, $this->intCategoryId);
                        ?>
                    </div>
                    <?php
                    if (!empty($this->arrHotNews))
                    {
                        ?>
                        <div class="box_sub_hot_news">
                            <div class="scroll-pane">
                                <div class="content_scoller width_common">
                                    <ul>
                                        <?php
                                        $count = count($this->arrHotNews) - 1;
                                        foreach ($this->arrHotNews as $key => $id)
                                        {
                                            $article = $this->objArticle->getArticleBasic($id);
                                            if (empty($article))
                                            {
                                                continue;
                                            }
                                            ?>
                                            <li <?php echo $count == $key ? 'class="end"' : ''; ?>>
                                                <?php
                                                if (!empty($article['thumbnail_url']))
                                                {
                                                    ?>
                                                    <div class="thumb">
                                                        <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" class="txt_link" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                            <img src="<?php echo $this->ImageurlArticle($article, 'size11'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                                        </a>
                                                        <?php echo $this->ArticleTypeIcon($article); ?>
                                                    </div>
                                                    <?php
                                                }
                                                ?>
                                                <div class="title_news">
                                                    <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" class="txt_link" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                                        <?php echo $article['title']; ?>
                                                    </a>
                                                    <span class="no_wrap">
                                                        <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                                        <?php echo $this->ArticleComment($article); ?>
                                                    </span>
                                                </div>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                </div>

            </div>
            <?php
        }
        ?>

        <div class="block_2mid_col line_gray line_mid_col width_common">
                <?php echo $this->render('mobile/list_paging.phtml'); ?>
            <div class="block_mid_col_right">
                <?php
                if (!empty($this->arrListVideo))
                {
                    ?>
                    <div class="box_category width_common space_box">
                        <div class="title_box_category width_common">
                            <div class="txt_main_category"><a href="<?php echo $this->configView['url'] . '/video'; ?>">Video</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <ul class="list_tin_180">
                                <?php
                                foreach ($this->arrListVideo as $id)
                                {
                                    $video = $this->objArticle->getArticleBasic($id);
                                    ?>
                                    <li>
                                        <div class="block_image_news width_common">
                                            <?php
                                            if (!empty($video['thumbnail_url']))
                                            {
                                                ?>
                                                <div class="block_thumb_lead">
                                                    <div class="thumb">
                                                        <a href="<?php echo $this->ShareurlWorldcup($video['share_url']); ?>" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                                            <img src="<?php echo $this->ImageurlArticle($video, 'size1'); ?>" alt="<?php echo $video['title_format']; ?>" title="<?php echo $video['title_format']; ?>" />
                                                        </a>
                                                <?php echo $this->ArticleTypeIcon($video); ?>
                                                    </div>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                            <div class="title_news">
                                                <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($video['share_url']); ?>" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                                    <?php echo $video['title']; ?>
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                            <div class="line_view_more">
                                <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'] . '/video'; ?>">Xem tất cả</a></div>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="banner_180 space_box">
                    <?php
                    if (DEVICE_ENV != 1)
                    {
                    ?>
                    <div class="banner_468 banner_common">
                        <div class="banner_468x90">
                            <script type="text/javascript">try{Poly_Article();}catch(e){}</script>
                        </div>
                    </div>
                    <?php
                    }
                    ?>
                </div>
                <?php
                if (!empty($this->arrListPhoto))
                {
                    ?>
                    <div class="box_category width_common space_box">
                        <div class="title_box_category width_common">
                            <div class="txt_main_category"><a href="<?php echo $this->configView['url'] . '/photo'; ?>">Ảnh</a></div>
                        </div>
                        <div class="content_box_category width_common">
                            <ul class="list_tin_180">
                                <?php
                                foreach ($this->arrListPhoto as $id)
                                {
                                    $photo = $this->objArticle->getArticleBasic($id);
                                    ?>
                                    <li>
                                        <div class="block_image_news width_common">
                                            <?php
                                            if (!empty($photo['thumbnail_url']))
                                            {
                                                ?>
                                                <div class="block_thumb_lead">
                                                    <div class="thumb">
                                                        <a href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo['title_format']; ?>" alt="<?php echo $photo['title_format']; ?>">
                                                            <img src="<?php echo $this->ImageurlArticle($photo, 'size1'); ?>" alt="<?php echo $photo['title_format']; ?>" title="<?php echo $photo['title_format']; ?>" />
                                                        </a>
                                                        <?php echo $this->ArticleTypeIcon($photo); ?>
                                                    </div>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                            <div class="title_news">
                                                <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo['title_format']; ?>" alt="<?php echo $photo['title_format']; ?>">
                                                <?php echo $photo['title']; ?>
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                            <div class="line_view_more">
                                <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'] . '/photo'; ?>">Xem tất cả</a></div>
                            </div>

                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
    <div id="col_right">
<?php echo $this->GetBlock('left'); ?>
    </div>
</div>