<div class="line_gray line_page width_common">
    <div id="col_left">
       <div class="block_slder_top space_box" id="top_fixture_worldcup">
            <div style="text-align: center;"><p style="padding: 25px 0;">Đang tải dữ liệu...</p></div>
        </div>
        <?php
        if (!empty($this->arrHotNews))
        {
            $firstNews = array_shift($this->arrHotNews);
        ?>
        <div id="spotlight" class="width_common space_box">
            <?php
            if(!empty($firstNews['thumbnail_url']))
            {
            ?>
            <div class="block_image">
                <a href="<?php echo $this->ShareurlWorldcup($firstNews['share_url']); ?>" title="<?php echo $firstNews['title_format']; ?>" alt="<?php echo $firstNews['title_format']; ?>">
                    <img src="<?php echo $this->ImageurlArticle($firstNews, 'size4'); ?>" alt="<?php echo $firstNews['title_format']; ?>" title="<?php echo $firstNews['title_format']; ?>" />
                </a>
            </div>
            <?php
            }
            ?>
            <div class="block_title">
                <div class="txt_title">
                    <a href="<?php echo $this->ShareurlWorldcup($firstNews['share_url']); ?>" title="<?php echo $firstNews['title_format']; ?>"><?php echo $firstNews['title']; ?></a>
                </div>
                <div class="block_lead"><?php echo $this->CropWord($firstNews['lead'],30, $this->ShareurlWorldcup($firstNews['share_url'])); ?></div>
            </div>
        </div>
        <?php
        }
        ?>
        <?php
        if (!empty($this->arrData))
        {
        ?>
        <div class="block_2mid_col line_gray line_mid_col width_common">
            <div class="block_mid_col_left">
                <ul class="list_news">
                    <?php
                    $arrDataAbove = array_slice($this->arrData, 0,5);
                    $this->arrData = array_diff($this->arrData, $arrDataAbove);
                    foreach($arrDataAbove as $id)
                    {
                        $article = $this->objArticle->getArticleBasic($id);
                    ?>
                        <li>
                            <div class="block_image_news width_common">
                                <?php
                                if (!empty($article['thumbnail_url']))
                                {
                                    ?>
                                <div class="thumb">
                                    <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                        <img src="<?php echo $this->ImageurlArticle($article, 'size11'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                    </a>
                                    <?php echo $this->ArticleTypeIcon($article); ?>
                                </div>
                                <?php
                                }
                                ?>
                                <div class="title_news">
                                    <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>" class="txt_link">
                                        <?php echo $article['title']; ?>
                                    </a>
                                    <span class="no_wrap">
                                        <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                        <?php echo $this->ArticleComment($article); ?>
                                </span>
                                </div>
                            </div>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
                <div class="block_banner_mid_2col width_common space_box">
                    <?php
                    if (DEVICE_ENV != 1)
                    {
                    ?>
                    <div class="banner_468 banner_common">
                        <div class="banner_468x90">
                            <script type="text/javascript">try{Poly_Article();}catch(e){}</script>
                        </div>
                    </div>
                    <?php
                    }
                    ?>
                </div>
                <?php
                if(!empty($this->arrData))
                {
                ?>
                <ul class="list_news" id="news_home">
                    <?php
                    foreach($this->arrData as $id)
                    {
                        $article = $this->objArticle->getArticleBasic($id);
                    ?>
                        <li>
                            <div class="block_image_news width_common">
                                <?php
                                if (!empty($article['thumbnail_url']))
                                {
                                    ?>
                                <div class="thumb">
                                    <a href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>">
                                        <img src="<?php echo $this->ImageurlArticle($article, 'size11'); ?>" alt="<?php echo $article['title_format']; ?>" title="<?php echo $article['title_format']; ?>" />
                                    </a>
                                    <?php echo $this->ArticleTypeIcon($article); ?>
                                </div>
                                <?php
                                }
                                ?>
                                <div class="title_news">
                                    <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($article['share_url']); ?>" title="<?php echo $article['title_format']; ?>" alt="<?php echo $article['title_format']; ?>" class="txt_link">
                                        <?php echo $article['title']; ?>
                                    </a>
                                    <span class="no_wrap">
                                        <?php echo $this->ArticleViewIcon($article['article_icon']); ?>
                                        <?php echo $this->ArticleComment($article); ?>
                                    </span>
                                </div>
                                <?php
                                //icon tai tro
                                echo $this->IconCommercial($firstNews, $this->intCategoryId);
                                ?>
                            </div>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
                 <?php
                $arrExclude = array_slice($this->arrData, -5, 5);
                array_push($arrExclude, $firstNews['article_id']);
                ?>
                <div class="xemtiep hiddenweb"><a href="<?php echo $this->configView['url'] . '/mobile/listcategory/category_id/' . $this->intCategoryId; ?>" data-container="#news_home" data-params="<?php echo $this->escape(Zend_Json::encode(array('limit' => LIMIT_LIST_MORE, 'offset' => LIMIT_LIST, 'total' => $this->arrParamPaging['total'], 'exclude' => implode(',', $arrExclude)))); ?>">Xem tiếp</a></div>
                <?php
                }
                ?>

            </div>
            <div class="block_mid_col_right">
                <?php
                if(!empty($this->arrListVideo))
                {
                ?>
                <div class="box_category width_common space_box">
                    <div class="title_box_category width_common">
                        <div class="txt_main_category"><a href="<?php echo $this->configView['url'].'/video'; ?>">Video</a></div>
                    </div>
                    <div class="content_box_category width_common">
                        <ul class="list_tin_180">
                            <?php
                            foreach($this->arrListVideo as $id)
                            {
                                $video = $this->objArticle->getArticleBasic($id);
                            ?>
                            <li>
                                <div class="block_image_news width_common">
                                    <?php
                                    if (!empty($video['thumbnail_url']))
                                    {
                                        ?>
                                    <div class="block_thumb_lead">
                                        <div class="thumb">
                                            <a href="<?php echo $this->ShareurlWorldcup($video['share_url']); ?>" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                                <img src="<?php echo $this->ImageurlArticle($video, 'size1'); ?>" alt="<?php echo $video['title_format']; ?>" title="<?php echo $video['title_format']; ?>" />
                                            </a>
                                            <?php echo $this->ArticleTypeIcon($video); ?>
                                        </div>
                                    </div>
                                    <?php
                                    }
                                    ?>
                                    <div class="title_news">
                                        <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($video['share_url']); ?>" title="<?php echo $video['title_format']; ?>" alt="<?php echo $video['title_format']; ?>">
                                            <?php echo $video['title']; ?>
                                        </a>
                                   </div>
                                </div>
                            </li>
                            <?php
                            }
                            ?>
                        </ul>
                        <div class="line_view_more">
                            <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'].'/video'; ?>">Xem tất cả</a></div>
                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
                <div class="banner_180 space_box">
                    <script type="text/javascript">try {Poly_SpecialRight();}catch(ex){};</script>
                </div>
                <?php
                if(!empty($this->arrListPhoto))
                {
                ?>
                <div class="box_category width_common space_box">
                    <div class="title_box_category width_common">
                        <div class="txt_main_category"><a href="<?php echo $this->configView['url'].'/photo'; ?>">Ảnh</a></div>
                    </div>
                    <div class="content_box_category width_common">
                        <ul class="list_tin_180">
                            <?php
                            foreach($this->arrListPhoto as $id)
                            {
                                $photo = $this->objArticle->getArticleBasic($id);
                            ?>
                            <li>
                                <div class="block_image_news width_common">
                                    <?php
                                    if (!empty($photo['thumbnail_url']))
                                    {
                                        ?>
                                    <div class="block_thumb_lead">
                                        <div class="thumb">
                                            <a href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo['title_format']; ?>" alt="<?php echo $photo['title_format']; ?>">
                                                <img src="<?php echo $this->ImageurlArticle($photo, 'size1'); ?>" alt="<?php echo $photo['title_format']; ?>" title="<?php echo $photo['title_format']; ?>" />
                                            </a>
                                            <?php echo $this->ArticleTypeIcon($photo); ?>
                                        </div>
                                    </div>
                                    <?php
                                    }
                                    ?>
                                    <div class="title_news">
                                        <a class="txt_link" href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo['title_format']; ?>" alt="<?php echo $photo['title_format']; ?>">
                                            <?php echo $photo['title']; ?>
                                        </a>
                                   </div>
                                </div>
                            </li>
                            <?php
                            }
                            ?>
                        </ul>
                        <div class="line_view_more">
                            <div class="txt_view_more"><a class="txt_666" href="<?php echo $this->configView['url'].'/photo'; ?>">Xem tất cả</a></div>
                        </div>

                    </div>
                </div>
                <?php
                }
                ?>
            </div>
        </div>
        <?php
        }
        ?>
    </div>
    <div id="col_right">
        <?php echo $this->GetBlock('left'); ?>
    </div>
</div>