<?php
if (!empty ($this->arrData))
{
?>
<div class="block_mid_new">
    <ul class="list_news" id="news_home">
        <?php
        foreach ($this->arrData as $id)
        {
            $articleDetail = $this->objArticle->getArticleBasic($id);
        ?>
        <li>
            <div class="block_image_news width_common">
                <?php
                if (!empty($articleDetail['thumbnail_url']))
                {
                ?>
                <div class="thumb">
                    <a href="<?php echo $this->ShareurlWorldcup($articleDetail['share_url']); ?>" title="<?php echo $articleDetail['title_format']; ?>" alt="<?php echo $articleDetail['title_format']; ?>">
                        <img src="<?php echo $this->ImageurlArticle($articleDetail, 'size11'); ?>" alt="<?php echo $articleDetail['title_format']; ?>" title="<?php echo $articleDetail['title_format']; ?>" />
                    </a>
                    <?php echo $this->ArticleTypeIcon($articleDetail); ?>
                </div>
                <?php
                }
                ?>
                <div class="title_news">
                    <a href="<?php echo $this->ShareurlWorldcup($articleDetail['share_url']); ?>" title="<?php echo $articleDetail['title_format']; ?>" alt="<?php echo $articleDetail['title_format']; ?>" class="txt_link">
                        <?php echo $articleDetail['title']; ?>
                    </a>
                    <span class="no_wrap">
                        <?php echo $this->ArticleViewIcon($articleDetail['article_icon']); ?>
                        <?php echo $this->ArticleComment($articleDetail); ?>
                    </span>
                </div>
            </div>
            <?php
            //icon tai tro
            echo $this->IconCommercial($articleDetail, $this->intCategoryId);
            ?>
        </li>
        <?php
            $j++;
        }
        ?>
    </ul>
    <div class="xemtiep hiddenweb"><a href="<?php echo $this->configView['url'] . '/mobile/listcategory/category_id/' . $this->intCategoryId; ?>" data-container="#news_home" data-params="<?php echo $this->escape(Zend_Json::encode(array('limit' => LIMIT_LIST_MORE, 'offset' => LIMIT_LIST, 'total' => $this->arrParamPaging['total'], 'exclude' => implode(',', array_slice($this->arrData, -5, 5))))); ?>">Xem tiếp</a></div>
</div>
<?php
}
?>