<?php
if(!empty($this->arrData))
{
    $count = count($this->arrData);
    $index = 0;
    foreach ($this->arrData as $id)
    {
        $articleDetail = $this->objArticle->getArticleBasic($id);
        if (empty($articleDetail))
            continue;
        ?>
        <li>
            <div class="block_image_news width_common">
                <?php
                if (!empty($articleDetail['thumbnail_url']))
                {
                    ?>
                    <div class="thumb">
                        <a href="<?php echo $this->ShareurlWorldcup($articleDetail['share_url']); ?>" title="<?php echo $articleDetail['title_format']; ?>" class="txt_link"><img src="<?php echo $this->ImageurlArticle($articleDetail, 'size11'); ?>" alt="<?php echo $articleDetail['title_format']; ?>"></a>
                        <?php echo $this->ArticleTypeIcon($articleDetail); ?>
                    </div>
                    <?php
                }
                ?>
                <div class="title_news">
                    <a href="<?php echo $this->ShareurlWorldcup($articleDetail['share_url']); ?>" title="<?php echo $articleDetail['title_format']; ?>" class="txt_link"><?php echo $articleDetail['title']; ?></a>
                    <span class="no_wrap">
                        <img class="icon_content icon_title_<?php echo intval($articleDetail['article_icon']); ?>" src="<?php echo $this->configView['images']; ?>/graphics/img_blank.gif" alt="icon title" />
                        <?php
                        echo $this->ArticleComment($articleDetail);
                        ?>
                    </span>
                </div>
               <?php
                //icon tai tro
                echo $this->IconCommercial($articleDetail, $this->intCategoryId);
                ?>
            </div>
        </li>
        <?php
    }

    /*chi chay tren beta*/
    if (APPLICATION_ENV == 'production')
    {
        ?>
        <script type="text/javascript">
            //slideshow photo
            if (typeof(common.initLinkSlideshow) != 'undefined') {
                common.initLinkSlideshow();
            }
        </script>
        <?php
    }
}
?>