<?php
foreach ($this->arrData as $id)
{
    $photo = $this->objArticle->getArticleBasic($id);
    ?>
    <li>
        <div class="thumb_140">
            <a title="video name" href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo["title_format"]; ?>"><img alt="<?php echo $photo["title_format"]; ?>" src="<?php echo $this->Imageurl($photo['thumbnail_url'], 'size6'); ?>">  </a>
            <?php echo $this->ArticleTypeIcon($photo); ?>
        </div>
        <div class="title_news"><a class="txt_link" href="<?php echo $this->ShareurlWorldcup($photo['share_url']); ?>" title="<?php echo $photo["title_format"]; ?>"><?php echo $photo["title"]; ?></a></div>
    </li>
    <?php
}
/*chi chay tren beta*/
if (APPLICATION_ENV == 'production')
{
    ?>
    <script type="text/javascript">
        //slideshow photo
        if (typeof(common.initLinkSlideshow) != 'undefined') {
            common.initLinkSlideshow();
        }
    </script>
    <?php
}
?>