<style>
    .ico {
    background: url("http://st.f3.vnecdn.net/responsive/c/v28/images/icons/icon_sprite.png") no-repeat scroll 0 0 rgba(0, 0, 0, 0);
    display: inline-block;
    }
    .light_box .ico.close-lb {
        background-position: -150px 0;
        height: 10px;
        margin-top: 5px;
        width: 10px;
    }
</style>


<div class="banner_300x250 banner_common space_box">
    
	<div class="box_category width_common hidden320"> <div class="banner_300x250"> <script type="text/javascript"> Poly_Large(1); </script> </div> </div>
</div>
<div id="thele_dovui" class="box_category width_common news_box_300">
  <div class="title_box_category width_common">
    <div class="txt_main_category"><a href="#">Thể lệ</a></div>
  </div>
  <div class="content_box_category width_common">
  	<p class="p_thele_dovui">
    	Cuộc thi <b>"Đố Vui Bóng Tròn" </b> do báo điện tử VnExpress (<a style='color:blue;' href='http://vnexpress.net'>http://vnexpress.net</a>) phối hợp với nhãn hàng "CLEAR MEN - Đàn ông đỉnh cao phong độ" tổ chức là cuộc thi hỏi đáp, thử tài hiểu biết của người hâm mộ về lịch sử World Cup.
        Cuộc thi sẽ diễn ra từ ngày 10/06/2014 cho tới ngày 21/07/2014...
    
    </p>
    <div class="txt_view_more thele"><a class="txt_666" href="javascript:;" >Xem chi tiết</a></div>
  </div>
</div>
<script type="text/javascript">
    var html_thele ='\
		<div class="light_box trandau dovui_lightbox" >\
			<div class="title"><span>\
				Thể lệ\
			</span>\
            <i class="ico close-lb right"></i><div class="clear"></div></div>\
			<div class="body" style="height:250px;overflow:scroll;"><p>\
            Cuộc thi <b>"Đố Vui Bóng Tròn"</b> do báo điện tử VnExpress (<a style="color:blue;" href="http://vnexpress.net">http://vnexpress.net</a>)\
            phối hợp với nhãn hàng "CLEAR MEN - Đàn ông đỉnh cao phong độ" tổ chức là cuộc thi hỏi đáp, thử tài hiểu biết của người hâm mộ về lịch sử World Cup.\
            Cuộc thi sẽ diễn ra từ ngày 10/06/2014 cho tới ngày 21/07/2014.<br>\
            <b>Điều 1: Đối tượng tham gia</b><br>\
            Tất cả độc giả VnExpress đang cư trú tại Việt Nam.</br>Cán bộ, nhân viên của báo điện tử VnExpress và Nhà tài trợ không được tham gia chương trình này.<br>\
			<b>Điều 2: Cách thức tham gia</b><br>- Từ 08h00 ngày 10/06/2014 đến 08h00 ngày 21/07/2014, Ban tổ chức sẽ đăng 10 câu hỏi tại <a style="color:blue;" href="http://worldcup.vnexpress.net/dovui">http://worldcup.vnexpress.net/dovui</a> mỗi ngày vào lúc 08h00. Người tham gia cần gửi câu trả lời của mình cho những câu hỏi này trước 07h59 ngày hôm sau. Mỗi cá nhân đều có quyền tham gia trả lời tất cả 420 câu hỏi trong suốt 42 ngày diễn ra cuộc thi để gia tăng cơ hội nhận các giải thưởng hấp dẫn từ Ban tổ chức.\
            <br>- Khi hoàn tất việc gửi câu trả lời hàng ngày, người tham gia cần cung cấp cho Ban tổ chức thông tin cá nhân gồm họ tên, email và số điện thoại. Sau khi tổng kết và công bố người thắng cuộc, Ban tổ chức sẽ liên hệ người nhận giải thông qua email và số điện thoại này để hướng dẫn người nhận giải cung cấp thêm các thông tin để xác minh và trao giải bao gồm: họ tên, ngày sinh, nơi cư trú, số CMND.\
            <br>- Mỗi thông tin email/số điện thoại chỉ hợp lệ cho duy nhất một lần gửi câu trả lời trong ngày.<br>\
            <b>Lưu ý: </b>Để được tích điểm xét nhận giải chung cuộc, người tham gia cần cung cấp email và số điện thoại giống nhau trong tất cả các ngày tham gia. Nếu có bất kỳ sự thay đổi, sai sót đối với những thông tin này, Ban tổ chức sẽ không đảm bảo việc tính điểm tích lũy cho người tham gia.<br>\
            <b>Điều 3: Cung cấp và sử dụng thông tin cá nhân</b><br>\
            - Người tham gia phải chịu trách nhiệm về tính xác thực của thông tin cá nhân trong trường hợp thắng giải. Nếu cung cấp thông tin không đúng sự thật cho Ban tổ chức, người tham gia sẽ bị loại hoặc tước giải thưởng ở bất kỳ giai đoạn nào, kể cả sau khi giải thưởng đã được trao.<br>\
            - Ban tổ chức chỉ công bố họ tên, quận/huyện/ và thành phố/tỉnh cư trú hoặc 04 số điện thoại cuối của người thắng giải trên các phương tiện thông tin đại chúng.<br>\
            <b>Điều 4: Giải thưởng</b><br>Cơ cấu giải thưởng bao gồm:<br>\
            - 42 giải ngày, mỗi giải bao gồm <b>01 thẻ điện thoại trị giá 500,000 VND.</b><br>\
            - 01 giải chung cuộc, bao gồm: <b>01 năm sử dụng Clear Men và 01 áo thi đấu đến từ CLB Manchester United.</b><br>\
            - Các giải ngày sẽ được trao cho người tham gia có số lượng câu trả lời đúng nhiều nhất và nhanh nhất đối với bộ 10 câu hỏi của ngày hôm đó.<br>\
            - Giải chung cuộc sẽ được trao cho người tham gia có <b>tổng</b> số câu trả lời đúng nhiều nhất và <b>tổng</b> thời gian trả lời câu hỏi nhanh nhất trong suốt 42 ngày diễn ra cuộc thi.<br>\
            - Thời gian tham dự: từ 08h00 ngày 10/06/2014 đến 07h59 ngày 22/07/2014.<br>\
            - Người thắng giải ngày sẽ được công bố vào lúc 08h00 ngày hôm sau và giải thưởng sẽ được gửi đến người thắng giải trong vòng 5-7 ngày làm việc.<br>\
            Người thắng giải chung cuộc sẽ được công bố vào ngày 26/07/2014 trên <a style="color:blue;" href="http://worldcup.vnexpress.net/dovui">http://worldcup.vnexpress.net/dovui</a>. Giải chung cuộc sẽ được trao trước ngày 08/08/2014.<br>\
            Trường hợp các cá nhân đạt giải không đến nhận giải hoặc cung cấp thông tin nhận giải không chính xác, Ban tổ chức sẽ được toàn quyền định đoạt đối với các giải thưởng đó.<br>\
            <b>Điều 5: Bản quyền</b><br>\
            -	Nhà tài trợ chỉ có quyền sử dụng hình ảnh của người tham gia nếu có sự đồng thuận của Báo điện tử VnExpress.</br>\
            <b>Điều 6: Hạn chế trách nhiệm</b><br>\
            -	Ban tổ chức không chịu trách nhiệm về những thông tin không đúng thực tế do người tham gia dự thi cung cấp.<br>\
           <div style="border: 1px dotted #ccc; display:block; overflow:hidden; padding:10px; margin-bottom:10px;margin-top:10px;"><lable style="color:#667788">Chuyên trang World Cup 2014 của VnExpress có sự đồng hành, tài trợ độc quyền của nhãn hàng “CLEAR MEN – Đàn ông đỉnh cao phong độ”.</lable></div>\
            </p>\
			</div></div>\
	';
    
    $('.thele').click(function(){
		Sexy.notice(html_thele);		
	})
</script>