<div id="detail_page" class="width_common line_col">
    <div id="col_660" class="left">
        <div class="box_width_common" id="box_details_news">
            <div class="w670 left">
                <div class="main_content_detail width_common">
                    <div class="div-fbook width_common title_div_fbook">
                        <div class="block_timer left txt_666"><?php echo $this->DateTimeFormat($this->arrArticleDetail['publish_time'], 'long'); ?></div>
                    </div>
                    <div class="title_news">
                        <h1><?php echo $this->arrArticleDetail['title_format']; ?></h1>
                    </div>
                    <div class="short_intro txt_666"><?php echo $this->arrArticleDetail['lead']; ?></div>
                    <!--Tin lien quan-->
                    <?php
                    if ( !empty($this->arrArticleDetail['reference_detail']) )
                    {
                    ?>
                    <div class="relative_new">
                        <ul class="list_news_dot_3x3_300">
                            <li>
                            <?php
                            $arrRefDetail   = array();
                            foreach ( $this->arrArticleDetail['reference_detail'] as $reference )
                            {
                                $arrRefDetail[] = '<a href="' . $this->ShareurlM240($reference['share_url']) . '" title="' . $reference['title_format'] . '">' . $reference['title_format'] . '</a>';
                            }//end foreach
                            echo DEVICE_ENV==1?implode('&nbsp;&nbsp;/&nbsp;&nbsp;', $arrRefDetail):implode('&nbsp;/&nbsp;', $arrRefDetail);
                            unset($arrRefDetail);
                            ?>
                            </li>
                        </ul>
                    </div>
                    <?php
                    }//end if
                    ?>
                    <div class="width_common space_bottom_20">
                        <div class="block_content_slide_showdetail">
                            <div id="article_content">
                            <?php
                            if ( !empty($this->arrPhoto) )
                            {
                                foreach ( $this->arrPhoto as $photo )
                                {
                                    $captionCheck   = trim(strip_tags($photo['caption']));
                                    $captionCheck   = !empty($captionCheck);
                            ?>
                                <div class="item_slide_show">
                                    <div class="block_thumb_slide_show">
                                        <img src="<?php echo $this->ImageurlArticle($photo, 'size2'); ?>" class="left" alt="<?php echo $captionCheck?addslashes($photo['caption_format']):''; ?>" />
                                    </div>
                                    <?php
                                    if ( $captionCheck )
                                    {
                                    ?>
                                    <div class="desc_cation"><?php echo $photo['caption']; ?></div>
                                    <?php
                                    }//end if
                                    ?>
                                </div>
                            <?php
                                }//end foreach
                            }//end if
                            ?>
                            </div>
                            <div class="fck_detail width_common">
                                <?php echo $this->arrArticleDetail['content']; ?>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                    <?php
                    if ( !empty($this->arrArticleDetail['list_tag']) )
                    {
                    ?>
                        <div class="block_tag width_common space_bottom_20">
                            <div class="txt_tag">Tags</div>
                            <?php
                            foreach ( $this->arrArticleDetail['list_tag'] as $tagDetail )
                            {
                            ?>
                                <a href="<?php echo $this->configView['url_vne'],$tagDetail['tag_url']; ?>" title="<?php echo $tagDetail['tag_name_format']; ?>" class="tag_item"><?php echo $this->MbUcfirst($tagDetail['tag_name']); ?></a>
                            <?php
                            }//end foreach
                            ?>
                        </div>
                    <?php
                    }//end if

                    /*Block other news*/
                    if ( !empty($this->arrOtherNews) )
                    {
                    ?>
                    <div id="box_tinkhac_detail" data-tracking="true" class="box_category width_common style_03">
                        <?php echo $this->render('m240/box/othernews.phtml');?>
                    </div>
                    <?php
                    }//end if
                    ?>
                </div>
            </div>
		</div>
	</div>
</div>